/**************************************************************************** 
 * Job:             mac_resu.counterparty_risk            A5M8HTKH.BO0000J7 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mac/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Tables:   mac_dm.COUNTERPARTY_RISK              A5M8HTKH.BB0000OH * 
 *                  mac_ctrl.PAR_INVALID_ROW_RULES        A5M8HTKH.BB00019B * 
 * Target Table:    mac_resu.COUNTERPARTY_RISK            A5M8HTKH.BB0000SF * 
 *                                                                          * 
 * Generated on:    Tuesday, August 20, 2019 3:19:57 PM EEST                * 
 * Generated by:    mrantonen                                               * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000J7);
%let etls_jobName = %nrquote(mac_resu.counterparty_risk);
%let etls_userID = %nrquote(mrantonen);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001RH * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_dm.COUNTERPARTY_RISK              A5M8HTKH.BB0000OH * 
 * Target Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR00016O * 
 *                   work.counterparty_risk_orig                            * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001RH);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_dm.COUNTERPARTY_RISK); 

%let _INPUT_count = 1; 
%let _INPUT = mac_dm.COUNTERPARTY_RISK;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.COUNTERPARTY_RISK%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Counterparty Risk dataset);

%let _INPUT0 = mac_dm.COUNTERPARTY_RISK;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.COUNTERPARTY_RISK%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Counterparty Risk dataset);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.counterparty_risk_orig;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR00016O%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default bank_id name 
        pd_class_pct loaded_dt;

%let _OUTPUT0 = work.counterparty_risk_orig;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR00016O%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default bank_id name 
        pd_class_pct loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete counterparty_risk_orig;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default bank_id name 
        pd_class_pct loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default bank_id name 
        pd_class_pct loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            code_converter                        A5M8HTKH.BU0001RI * 
 * Transform:       code_converter                                          * 
 * Description:     Convert data to AnaCredit codevalues                    * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR00016O * 
 *                   work.counterparty_risk_orig                            * 
 * Target Table:    code_converter_OUTPUT0 -              A5M8HTKH.BR00016P * 
 *                   work.W7ETSR1C                                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001RI);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.counterparty_risk_orig); 

%let _INPUT_count = 1; 
%let _INPUT = work.counterparty_risk_orig;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR00016O%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.counterparty_risk_orig;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR00016O%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W7ETSR1C;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/code_converter_OUTPUT0_A5M8HTKH.BR00016P%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default;
%let _OUTPUT_col_count = 5;
%let _OUTPUT_col0_name = information_date;
%let _OUTPUT_col0_table = work.W7ETSR1C;
%let _OUTPUT_col0_length = 4;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = FINDFDD10.;
%let _OUTPUT_col0_informat = DDMMYY10.;
%let _OUTPUT_col0_label = %nrquote(Information date of the record);
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = reporting_agent_identifier;
%let _OUTPUT_col1_table = work.W7ETSR1C;
%let _OUTPUT_col1_length = 60;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(Reporting agent identifier);
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input_count = 0;
%let _OUTPUT_col2_name = observed_agent_identifier;
%let _OUTPUT_col2_table = work.W7ETSR1C;
%let _OUTPUT_col2_length = 60;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Observed agent identifier);
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input_count = 0;
%let _OUTPUT_col3_name = counterparty_identifier;
%let _OUTPUT_col3_table = work.W7ETSR1C;
%let _OUTPUT_col3_length = 60;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = ;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(Counterparty identifier);
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input_count = 0;
%let _OUTPUT_col4_name = probability_of_default;
%let _OUTPUT_col4_table = work.W7ETSR1C;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 15.4;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(Probability of default);
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input_count = 0;

%let _OUTPUT0 = work.W7ETSR1C;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/code_converter_OUTPUT0_A5M8HTKH.BR00016P%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default;
%let _OUTPUT0_col_count = 5;
%let _OUTPUT0_col0_name = information_date;
%let _OUTPUT0_col0_table = work.W7ETSR1C;
%let _OUTPUT0_col0_length = 4;
%let _OUTPUT0_col0_type = ;
%let _OUTPUT0_col0_format = FINDFDD10.;
%let _OUTPUT0_col0_informat = DDMMYY10.;
%let _OUTPUT0_col0_label = %nrquote(Information date of the record);
%let _OUTPUT0_col0_exp = ;
%let _OUTPUT0_col0_input_count = 0;
%let _OUTPUT0_col1_name = reporting_agent_identifier;
%let _OUTPUT0_col1_table = work.W7ETSR1C;
%let _OUTPUT0_col1_length = 60;
%let _OUTPUT0_col1_type = $;
%let _OUTPUT0_col1_format = ;
%let _OUTPUT0_col1_informat = ;
%let _OUTPUT0_col1_label = %nrquote(Reporting agent identifier);
%let _OUTPUT0_col1_exp = ;
%let _OUTPUT0_col1_input_count = 0;
%let _OUTPUT0_col2_name = observed_agent_identifier;
%let _OUTPUT0_col2_table = work.W7ETSR1C;
%let _OUTPUT0_col2_length = 60;
%let _OUTPUT0_col2_type = $;
%let _OUTPUT0_col2_format = ;
%let _OUTPUT0_col2_informat = ;
%let _OUTPUT0_col2_label = %nrquote(Observed agent identifier);
%let _OUTPUT0_col2_exp = ;
%let _OUTPUT0_col2_input_count = 0;
%let _OUTPUT0_col3_name = counterparty_identifier;
%let _OUTPUT0_col3_table = work.W7ETSR1C;
%let _OUTPUT0_col3_length = 60;
%let _OUTPUT0_col3_type = $;
%let _OUTPUT0_col3_format = ;
%let _OUTPUT0_col3_informat = ;
%let _OUTPUT0_col3_label = %nrquote(Counterparty identifier);
%let _OUTPUT0_col3_exp = ;
%let _OUTPUT0_col3_input_count = 0;
%let _OUTPUT0_col4_name = probability_of_default;
%let _OUTPUT0_col4_table = work.W7ETSR1C;
%let _OUTPUT0_col4_length = 8;
%let _OUTPUT0_col4_type = ;
%let _OUTPUT0_col4_format = 15.4;
%let _OUTPUT0_col4_informat = ;
%let _OUTPUT0_col4_label = %nrquote(Probability of default);
%let _OUTPUT0_col4_exp = ;
%let _OUTPUT0_col4_input_count = 0;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W7ETSR1C;
quit;

%let target_table = %nrquote(COUNTERPARTY_RISK               );

/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default;
%code_converter(source=&_INPUT0.,target=&target_table., output=&_OUTPUT0.,keep=&_OUTPUT0_keep.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end code_converter **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001ZA * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_ctrl.PAR_INVALID_ROW_RULES        A5M8HTKH.BB00019B * 
 * Target Table:    shadow_OUTPUT0 - work.WGGZHMC         A5M8HTKH.BR0001C0 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001ZA);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_ctrl.PAR_INVALID_ROW_RULES); 

%let _INPUT_count = 1; 
%let _INPUT = mac_ctrl.PAR_INVALID_ROW_RULES;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_INVALID_ROW_RULES%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Parameter table to rule out invalid rows from the data);

%let _INPUT0 = mac_ctrl.PAR_INVALID_ROW_RULES;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_INVALID_ROW_RULES%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Parameter table to rule out invalid rows from the data);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.WGGZHMC;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0001C0%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;

%let _OUTPUT0 = work.WGGZHMC;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0001C0%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete WGGZHMC;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001ZB * 
 * Transform:       Extract                                                 * 
 * Description:     Only COUNTERPARTY_RISK table deletions                  * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 - work.WGGZHMC         A5M8HTKH.BR0001C0 * 
 * Target Table:    Extract -                             A5M8HTKH.BR0001C1 * 
 *                   work.COUNTERPARTY_RISK_DELETIONS                       * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001ZB);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.WGGZHMC); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete COUNTERPARTY_RISK_DELETIONS;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.COUNTERPARTY_RISK_DELETIONS as
      select
         information_date,
         where_clause
   from &SYSLAST
      where UPPER(TRIM(target_table))='COUNTERPARTY_RISK'
   ;
quit;

%let SYSLAST = work.COUNTERPARTY_RISK_DELETIONS;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*---- Start of User Written Code  ----*/ 

%include "//sasdw/prod/mac/programs/macros/deletewithparam.sas" / source2;

%deletewithparam(W7ETSR1C, COUNTERPARTY_RISK_DELETIONS);

/*---- End of User Written Code  ----*/ 

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001RJ * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    code_converter_OUTPUT0 -              A5M8HTKH.BR00016P * 
 *                   work.W7ETSR1C                                          * 
 * Target Table:    Extract - work.W7ETTZN1               A5M8HTKH.BR00016Q * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001RJ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W7ETSR1C); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W7ETTZN1;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W7ETTZN1 as
      select
         (&active_date.) as information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date of the record',
         reporting_agent_identifier,
         observed_agent_identifier,
         counterparty_identifier,
         probability_of_default,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W7ETTZN1;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0001RK * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W7ETTZN1               A5M8HTKH.BR00016Q * 
 * Target Table:    mac_resu.COUNTERPARTY_RISK            A5M8HTKH.BB0000SF * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001RK);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W7ETTZN1); 

%let _INPUT_count = 1; 
%let _INPUT = work.W7ETTZN1;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR00016Q%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W7ETTZN1;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR00016Q%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mac_resu.COUNTERPARTY_RISK;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mac/data/resu/mac_resu.COUNTERPARTY_RISK%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Counterparty Risk dataset);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default loaded_dt;

%let _OUTPUT0 = mac_resu.COUNTERPARTY_RISK;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mac/data/resu/mac_resu.COUNTERPARTY_RISK%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Counterparty Risk dataset);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier observed_agent_identifier 
        counterparty_identifier probability_of_default loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mac_resu nolist; 
   modify COUNTERPARTY_RISK(ALTER=&alterpass ); 
      index create primary_index = (information_date reporting_agent_identifier 
                      observed_agent_identifier counterparty_identifier)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

