/**************************************************************************** 
 * Job:             mac_dm.counterparty_reference         A5ZNM6KG.BO0004J2 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mac/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Tables:   mac_ctrl.PAR_FILTERS                  A5ZNM6KG.BG0006IN * 
 *                  mac_ctrl.PAR_CODE_CONVERTER           A5ZNM6KG.BG0006IV * 
 *                  dw_dw.RISK_CUSTOMER_COMPANY           A5ZNM6KG.BG0003VQ * 
 *                  dw_dw.CUSTOMER_RESTRICT_WARN          A5ZNM6KG.BG0003UQ * 
 *                  dw_dw.CUSTOMER                        A5ZNM6KG.BG0002EQ * 
 *                  dw_dw.EXCHANGE_RATES_H                A5ZNM6KG.BG0003H3 * 
 *                  mac_dm.COUNTERPARTY_INSTRUMENT        A5ZNM6KG.BG0006J6 * 
 *                  mac_dm.PROTECTION_PROVIDERS           A5ZNM6KG.BG0006J7 * 
 * Target Table:    mac_dm.COUNTERPARTY_REFERENCE         A5ZNM6KG.BG0006IZ * 
 *                                                                          * 
 * Generated on:    Thursday, May 2, 2019 10:57:44 AM EEST                  * 
 * Generated by:    ier                                                     * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0004J2);
%let etls_jobName = %nrquote(mac_dm.counterparty_reference);
%let etls_userID = %nrquote(ier);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005FL * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.CUSTOMER                        A5ZNM6KG.BG0002EQ * 
 * Target Table:    shadow_OUTPUT0 - work.customer        A5ZNM6KG.BV0004JO * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.CUSTOMER); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.CUSTOMER;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CUSTOMER%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Customer data);

%let _INPUT0 = dw_dw.CUSTOMER;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CUSTOMER%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Customer data);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.customer;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JO%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.customer;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JO%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete customer;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005FI * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.RISK_CUSTOMER_COMPANY           A5ZNM6KG.BG0003VQ * 
 * Target Table:    shadow_OUTPUT0 -                      A5ZNM6KG.BV0004JL * 
 *                   work.risk_customer_company                             * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FI);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.RISK_CUSTOMER_COMPANY); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.RISK_CUSTOMER_COMPANY;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.RISK_CUSTOMER_COMPANY%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.RISK_CUSTOMER_COMPANY;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.RISK_CUSTOMER_COMPANY%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.risk_customer_company;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JL%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id customer_id special_lending_flag 
        closing_period_txt form_type_cd raiting_date payment_notice_flag 
        rating_class_cd rating_point uc_pct turnover_amt total_assets_amt 
        employee_cnt equity_ratio ebit_amt equity_capital_amt 
        group_turnover_amt group_total_assets_amt group_employee_cnt 
        source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.risk_customer_company;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JL%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id customer_id special_lending_flag 
        closing_period_txt form_type_cd raiting_date payment_notice_flag 
        rating_class_cd rating_point uc_pct turnover_amt total_assets_amt 
        employee_cnt equity_ratio ebit_amt equity_capital_amt 
        group_turnover_amt group_total_assets_amt group_employee_cnt 
        source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete risk_customer_company;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id customer_id special_lending_flag 
        closing_period_txt form_type_cd raiting_date payment_notice_flag 
        rating_class_cd rating_point uc_pct turnover_amt total_assets_amt 
        employee_cnt equity_ratio ebit_amt equity_capital_amt 
        group_turnover_amt group_total_assets_amt group_employee_cnt 
        source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id customer_id special_lending_flag 
        closing_period_txt form_type_cd raiting_date payment_notice_flag 
        rating_class_cd rating_point uc_pct turnover_amt total_assets_amt 
        employee_cnt equity_ratio ebit_amt equity_capital_amt 
        group_turnover_amt group_total_assets_amt group_employee_cnt 
        source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005FG * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_ctrl.PAR_FILTERS                  A5ZNM6KG.BG0006IN * 
 * Target Table:    shadow_OUTPUT0 - work.par_filters     A5ZNM6KG.BV0004JJ * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FG);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_ctrl.PAR_FILTERS); 

%let _INPUT_count = 1; 
%let _INPUT = mac_ctrl.PAR_FILTERS;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_FILTERS%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Filtering data for AnaCredit);

%let _INPUT0 = mac_ctrl.PAR_FILTERS;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_FILTERS%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Filtering data for AnaCredit);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.par_filters;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JJ%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;

%let _OUTPUT0 = work.par_filters;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JJ%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete par_filters;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005FM * 
 * Transform:       Join                                                    * 
 * Description:     Create customer data                                    * 
 *                                                                          * 
 * Source Tables:   shadow_OUTPUT0 - work.customer        A5ZNM6KG.BV0004JO * 
 *                  shadow_OUTPUT0 -                      A5ZNM6KG.BV0004JL * 
 *                   work.risk_customer_company                             * 
 *                  shadow_OUTPUT0 - work.par_filters     A5ZNM6KG.BV0004JJ * 
 * Target Table:    Join - work.customer_data             A5ZNM6KG.BV0004JP * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete customer_data;
quit;

proc sql;
   create view work.customer_data as
   select
      customer.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      customer.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      customer.customer_id length = 9   
         label = 'CBS Customer ID',
      cat(customer.bank_id, customer.customer_id) as counterparty_identifier length = 60   
         label = 'Counterparty Identifier',
      customer.ssn_id length = 20   
         label = 'Social security / organisation number',
      customer.customer_type length = 3   
         format = 3.
         label = '1=Private, 2=Coorp.cust.',
      customer.name length = 150   
         label = 'Customer Name (All customers)',
      customer.street_address length = 50   
         label = 'Street address',
      customer.post_office_number length = 10   
         label = 'Post office number',
      customer.country_cd length = 2   
         label = 'Address-country code',
      customer.post_office_name length = 40   
         label = 'Post office name',
      customer.legal_form_cd length = 2   
         label = 'Juridisk Form',
      customer.stat_sector_cd length = 6   
         label = 'Sektorkod. Obs : 6 siffror.',
      customer.stat_branch_cd length = 6   
         label = 'Näringsgren. Obs: 6 siffror i kundreg. Ngrenkp färre siffror (fyll ut med nollor)',
      customer.occupational_status_cd length = 1   
         label = 'Occupational status (1=worker, 2=lower officer, 3=higher officer…..) of private customer',
      customer.lei length = 20   
         label = ' Legal Entity Identifier',
      customer.lei_expiry_date length = 4   
         format = findfdd10.
         label = 'Date when the LEI expires',
      risk_customer_company.raiting_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Rating date',
      (case when customer.bank_id = 'B' then 'SEK'
       else 'EUR'
      end) as currency_cd length = 3   
         label = 'Currency code',
      risk_customer_company.turnover_amt length = 8   
         format = 15.2
         label = 'Turnover',
      risk_customer_company.total_assets_amt length = 8   
         format = 15.2
         label = 'Balance sheet total assets (sv. balansomslutning)',
      risk_customer_company.employee_cnt length = 4   
         format = 8.
         label = 'Number of employees'
   from
      work.customer as customer left join 
      work.risk_customer_company as risk_customer_company
         on
         (
            customer.information_date = risk_customer_company.information_date
            and customer.bank_id = risk_customer_company.bank_id
            and customer.customer_id = risk_customer_company.customer_id
         ) left join 
      work.par_filters as par_filters_customer_type
         on
         (
            customer.information_date = par_filters_customer_type.information_date
            and customer.bank_id = par_filters_customer_type.bank_id
            and customer.customer_type = par_filters_customer_type.code_value_num
            and par_filters_customer_type.target_column = 'customer_type'
         ) left join 
      work.par_filters as par_filters_sector_cd
         on
         (
            customer.information_date = par_filters_sector_cd.information_date
            and customer.bank_id = par_filters_sector_cd.bank_id
            and customer.stat_sector_cd = par_filters_sector_cd.code_value_char
            and par_filters_sector_cd.target_column = 'stat_sector_cd'
         )
   where
      par_filters_customer_type.code_value_num IS MISSING 
      and par_filters_sector_cd.code_value_char IS MISSING 
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005FN * 
 * Transform:       Join                                                    * 
 * Description:     Create rating for B-bank                                * 
 *                                                                          * 
 * Source Tables:   shadow_OUTPUT0 - work.customer        A5ZNM6KG.BV0004JO * 
 *                  shadow_OUTPUT0 -                      A5ZNM6KG.BV0004JL * 
 *                   work.risk_customer_company                             * 
 *                  dw_dw.EXCHANGE_RATES_H                A5ZNM6KG.BG0003H3 * 
 * Target Table:    Join - work.bbank_rating              A5ZNM6KG.BV0004JQ * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete bbank_rating;
quit;

proc sql;
   create view work.bbank_rating as
   select
      customer.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      customer.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      customer.customer_id length = 9   
         label = 'CBS Customer ID',
      risk_customer_company.raiting_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Rating date',
      risk_customer_company.turnover_amt length = 8   
         format = 15.2
         label = 'Turnover',
      risk_customer_company.total_assets_amt length = 8   
         format = 15.2
         label = 'Balance sheet total assets (sv. balansomslutning)',
      risk_customer_company.employee_cnt length = 4   
         format = 8.
         label = 'Number of employees',
      EXCHANGE_RATES_H.mid_rate length = 8   
         format = 10.6
         label = 'Mean value of one base currency unit in currency (värdet på basvalutan i valutan)',
      (case when customer.bank_id = 'B' then 'SEK' else 'EUR' end) as currency_cd length = 3   
         label = 'Currency code'
   from
      work.customer as customer left join 
      work.risk_customer_company as risk_customer_company
         on
         (
            customer.information_date = risk_customer_company.information_date
            and customer.bank_id = risk_customer_company.bank_id
            and customer.customer_id = risk_customer_company.customer_id
         ) left join 
      dw_dw.EXCHANGE_RATES_H as EXCHANGE_RATES_H
         on
         (
            risk_customer_company.raiting_date = EXCHANGE_RATES_H.information_date
         )
   where
      customer.bank_id = 'B'
      and EXCHANGE_RATES_H.bank_id = 'A'
      and EXCHANGE_RATES_H.currency_cd = 'SEK'
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005FO * 
 * Transform:       Join                                                    * 
 * Description:     Create counterparty data                                * 
 *                                                                          * 
 * Source Tables:   Join - work.customer_data             A5ZNM6KG.BV0004JP * 
 *                  Join - work.bbank_rating              A5ZNM6KG.BV0004JQ * 
 * Target Table:    Join - work.counterparty_data         A5ZNM6KG.BV0004JR * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete counterparty_data;
quit;

proc sql;
   create view work.counterparty_data as
   select
      customer_data.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      customer_data.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      customer_data.customer_id length = 9   
         label = 'CBS Customer ID',
      customer_data.counterparty_identifier length = 60   
         label = 'Counterparty Identifier',
      customer_data.ssn_id length = 20   
         label = 'Social security / organisation number',
      customer_data.customer_type length = 3   
         format = 3.
         label = '1=Private, 2=Coorp.cust.',
      customer_data.name length = 150   
         label = 'Customer Name (All customers)',
      customer_data.street_address length = 50   
         label = 'Street address',
      customer_data.post_office_number length = 10   
         label = 'Post office number',
      customer_data.country_cd length = 2   
         label = 'Address-country code',
      customer_data.post_office_name length = 40   
         label = 'Post office name',
      customer_data.legal_form_cd length = 2   
         label = 'Juridisk Form',
      customer_data.stat_sector_cd length = 6   
         label = 'Sektorkod. Obs : 6 siffror.',
      customer_data.stat_branch_cd length = 6   
         label = 'Näringsgren. Obs: 6 siffror i kundreg. Ngrenkp färre siffror (fyll ut med nollor)',
      customer_data.occupational_status_cd length = 1   
         label = 'Occupational status (1=worker, 2=lower officer, 3=higher officer…..) of private customer',
      customer_data.lei length = 20   
         label = ' Legal Entity Identifier',
      customer_data.lei_expiry_date length = 4   
         format = findfdd10.
         label = 'Date when the LEI expires',
      customer_data.raiting_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Rating date',
      customer_data.currency_cd length = 3   
         label = 'Currency code',
      customer_data.turnover_amt length = 8   
         format = 15.2
         label = 'Turnover',
      customer_data.total_assets_amt length = 8   
         format = 15.2
         label = 'Balance sheet total assets (sv. balansomslutning)',
      customer_data.employee_cnt length = 4   
         format = 8.
         label = 'Number of employees',
      (case when customer_data.bank_id = 'A' then 1 else (case when bbank_rating.mid_rate is not missing then bbank_rating.mid_rate end) end) as mid_rate length = 8   
         format = 10.6
         label = 'Mean value of one base currency unit in currency (värdet på basvalutan i valutan)'
   from
      work.customer_data as customer_data left join 
      work.bbank_rating as bbank_rating
         on
         (
            customer_data.information_date = bbank_rating.information_date
            and customer_data.bank_id = bbank_rating.bank_id
            and customer_data.customer_id = bbank_rating.customer_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005FK * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.CUSTOMER_RESTRICT_WARN          A5ZNM6KG.BG0003UQ * 
 * Target Table:    shadow_OUTPUT0 -                      A5ZNM6KG.BV0004JN * 
 *                   work.customer_restrict_warn                            * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FK);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.CUSTOMER_RESTRICT_WARN); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.CUSTOMER_RESTRICT_WARN;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CUSTOMER_RESTRICT_WARN%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.CUSTOMER_RESTRICT_WARN;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CUSTOMER_RESTRICT_WARN%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.customer_restrict_warn;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JN%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id customer_ssn_id surrow_id customer_warning_cd 
        valid_from_date valid_to_date customer_2_ssn_id warning_text 
        source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.customer_restrict_warn;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JN%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id customer_ssn_id surrow_id customer_warning_cd 
        valid_from_date valid_to_date customer_2_ssn_id warning_text 
        source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete customer_restrict_warn;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id customer_ssn_id surrow_id customer_warning_cd 
        valid_from_date valid_to_date customer_2_ssn_id warning_text 
        source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id customer_ssn_id surrow_id customer_warning_cd 
        valid_from_date valid_to_date customer_2_ssn_id warning_text 
        source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005FH * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_ctrl.PAR_CODE_CONVERTER           A5ZNM6KG.BG0006IV * 
 * Target Table:    shadow_OUTPUT0 - work.code_converter  A5ZNM6KG.BV0004JK * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FH);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_ctrl.PAR_CODE_CONVERTER); 

%let _INPUT_count = 1; 
%let _INPUT = mac_ctrl.PAR_CODE_CONVERTER;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_CODE_CONVERTER%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Code converter);

%let _INPUT0 = mac_ctrl.PAR_CODE_CONVERTER;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_CODE_CONVERTER%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Code converter);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.code_converter;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JK%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date surrow_id bank_id code_type code_value_char 
        code_value_num code_description target_table target_column 
        internal_value_type internal_value_prio internal_column 
        internal_value_char internal_value_num internal_value_num_start 
        internal_value_num_end internal_value_clause loaded_dt;

%let _OUTPUT0 = work.code_converter;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004JK%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date surrow_id bank_id code_type code_value_char 
        code_value_num code_description target_table target_column 
        internal_value_type internal_value_prio internal_column 
        internal_value_char internal_value_num internal_value_num_start 
        internal_value_num_end internal_value_clause loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete code_converter;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date surrow_id bank_id code_type code_value_char 
        code_value_num code_description target_table target_column 
        internal_value_type internal_value_prio internal_column 
        internal_value_char internal_value_num internal_value_num_start 
        internal_value_num_end internal_value_clause loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date surrow_id bank_id code_type code_value_char 
        code_value_num code_description target_table target_column 
        internal_value_type internal_value_prio internal_column 
        internal_value_char internal_value_num internal_value_num_start 
        internal_value_num_end internal_value_clause loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005FP * 
 * Transform:       Join                                                    * 
 * Description:     Create legal proceedings                                * 
 *                                                                          * 
 * Source Tables:   shadow_OUTPUT0 -                      A5ZNM6KG.BV0004JN * 
 *                   work.customer_restrict_warn                            * 
 *                  shadow_OUTPUT0 - work.code_converter  A5ZNM6KG.BV0004JK * 
 * Target Table:    Join - work.legalproceedings_orig     A5ZNM6KG.BV0004JS * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete legalproceedings_orig;
quit;

proc sql;
   create view work.legalproceedings_orig as
   select
      customer_restrict_warn.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      customer_restrict_warn.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      customer_restrict_warn.customer_ssn_id length = 11   
         label = 'Customer´s SSN',
      customer_restrict_warn.customer_warning_cd length = 3   
         label = 'Restriction code (CODES.code_number_cd=''16'')',
      customer_restrict_warn.valid_from_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'First date when restriction/warning is valid',
      customer_restrict_warn.customer_2_ssn_id length = 11   
         label = 'Other customers´ SSN If warning connected to another customer',
      customer_restrict_warn.warning_text length = 90   
         label = 'Free text',
      code_converter.code_value_char length = 14   
         label = 'Code value character',
      code_converter.internal_value_prio length = 8   
         format = 8.
         label = 'Calculation priority order',
      count(*) as dup_seq length = 8
   from
      work.customer_restrict_warn as customer_restrict_warn left join 
      work.code_converter as code_converter
         on
         (
            customer_restrict_warn.information_date = code_converter.information_date
            and customer_restrict_warn.bank_id = code_converter.bank_id
            and customer_restrict_warn.customer_warning_cd = code_converter.internal_value_char
         )
   where
      code_converter.code_type = 'CL_LGL_PRCDNG_STTS_AC'
      and customer_restrict_warn.valid_from_date <= customer_restrict_warn.information_date
      and (customer_restrict_warn.valid_to_date >= customer_restrict_warn.information_date
      or customer_restrict_warn.valid_to_date IS MISSING )
   group by
      customer_restrict_warn.customer_ssn_id
   order by
      customer_restrict_warn.information_date,
      customer_restrict_warn.bank_id,
      customer_restrict_warn.customer_ssn_id,
      code_converter.internal_value_prio
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0005FQ * 
 * Transform:       Extract                                                 * 
 * Description:     Select proceedings:(min(internal_value_prio))           * 
 *                                                                          * 
 * Source Table:    Join - work.legalproceedings_orig     A5ZNM6KG.BV0004JS * 
 * Target Table:    Extract - work.proceedings_prio       A5ZNM6KG.BV0004JT * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.legalproceedings_orig); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete proceedings_prio;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.proceedings_prio as
      select
         information_date,
         bank_id,
         customer_ssn_id,
         (min(internal_value_prio)) as min_of_internal_value_prio length = 8
   from &SYSLAST
   group by
      information_date,
      bank_id,
      customer_ssn_id
   ;
quit;

%let SYSLAST = work.proceedings_prio;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005FR * 
 * Transform:       Join                                                    * 
 * Description:     Find legal_proceedings date                             * 
 *                                                                          * 
 * Source Tables:   Extract - work.proceedings_prio       A5ZNM6KG.BV0004JT * 
 *                  Join - work.legalproceedings_orig     A5ZNM6KG.BV0004JS * 
 * Target Table:    Join - work.legal_proceedings         A5ZNM6KG.BV0004JU * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FR);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete legal_proceedings;
quit;

proc sql;
   create view work.legal_proceedings as
   select
      proceedings_prio.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      proceedings_prio.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      proceedings_prio.customer_ssn_id length = 11   
         label = 'Customer´s SSN',
      legalproceedings_orig.code_value_char length = 14   
         label = 'Code value character',
      min(legalproceedings_orig.valid_from_date) as min_of_valid_from_date length = 4   
         format = findfdd10.
   from
      work.proceedings_prio as proceedings_prio left join 
      work.legalproceedings_orig as legalproceedings_orig
         on
         (
            proceedings_prio.information_date = legalproceedings_orig.information_date
            and proceedings_prio.bank_id = legalproceedings_orig.bank_id
            and proceedings_prio.customer_ssn_id = legalproceedings_orig.customer_ssn_id
            and proceedings_prio.min_of_internal_value_prio = legalproceedings_orig.internal_value_prio
         )
   group by
      proceedings_prio.information_date,
      proceedings_prio.bank_id,
      proceedings_prio.customer_ssn_id,
      legalproceedings_orig.code_value_char
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005FS * 
 * Transform:       Join                                                    * 
 * Description:     Select Distinct                                         * 
 *                                                                          * 
 * Source Tables:   Join - work.legal_proceedings         A5ZNM6KG.BV0004JU * 
 *                  Join - work.legalproceedings_orig     A5ZNM6KG.BV0004JS * 
 * Target Table:    Join - work.legal_proceedings_final   A5ZNM6KG.BV0004JV * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FS);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete legal_proceedings_final;
quit;

proc sql;
   create view work.legal_proceedings_final as
   select distinct
      legal_proceedings.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      legal_proceedings.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      legal_proceedings.customer_ssn_id length = 11   
         label = 'Customer´s SSN',
      legal_proceedings.code_value_char length = 14   
         label = 'Code value character',
      legal_proceedings.min_of_valid_from_date length = 4   
         format = findfdd10.,
      legalproceedings_orig.customer_warning_cd length = 3   
         label = 'Restriction code (CODES.code_number_cd=''16'')'
   from
      work.legal_proceedings as legal_proceedings left join 
      work.legalproceedings_orig as legalproceedings_orig
         on
         (
            legal_proceedings.information_date = legalproceedings_orig.information_date
            and legal_proceedings.bank_id = legalproceedings_orig.bank_id
            and legal_proceedings.customer_ssn_id = legalproceedings_orig.customer_ssn_id
            and legal_proceedings.min_of_valid_from_date = legalproceedings_orig.valid_from_date
            and legal_proceedings.code_value_char = legalproceedings_orig.code_value_char
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005FT * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Join - work.counterparty_data         A5ZNM6KG.BV0004JR * 
 *                  Join - work.legal_proceedings_final   A5ZNM6KG.BV0004JV * 
 *                  shadow_OUTPUT0 - work.par_filters     A5ZNM6KG.BV0004JJ * 
 * Target Table:    Join -                                A5ZNM6KG.BV0004JW * 
 *                   work.counterparty_reference_orig                       * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FT);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete counterparty_reference_orig;
quit;

proc sql;
   create view work.counterparty_reference_orig as
   select
      counterparty_data.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      counterparty_data.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      counterparty_data.counterparty_identifier length = 60   
         label = 'Counterparty Identifier',
      counterparty_data.ssn_id length = 20   
         label = 'Social security / organisation number',
      counterparty_data.customer_type length = 3   
         format = 3.
         label = '1=Private, 2=Coorp.cust.',
      counterparty_data.name length = 150   
         label = 'Customer Name (All customers)',
      counterparty_data.street_address length = 50   
         label = 'Street address',
      counterparty_data.post_office_number length = 10   
         label = 'Post office number',
      counterparty_data.country_cd length = 2   
         label = 'Address-country code',
      counterparty_data.post_office_name length = 40   
         label = 'Post office name',
      counterparty_data.legal_form_cd length = 2   
         label = 'Juridisk Form',
      counterparty_data.stat_sector_cd length = 6   
         label = 'Sektorkod. Obs : 6 siffror.',
      counterparty_data.stat_branch_cd length = 6   
         label = 'Näringsgren. Obs: 6 siffror i kundreg. Ngrenkp färre siffror (fyll ut med nollor)',
      counterparty_data.occupational_status_cd length = 1   
         label = 'Occupational status (1=worker, 2=lower officer, 3=higher officer…..) of private customer',
      counterparty_data.lei length = 20   
         label = ' Legal Entity Identifier',
      counterparty_data.lei_expiry_date length = 4   
         format = findfdd10.
         label = 'Date when the LEI expires',
      counterparty_data.raiting_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Rating date',
      counterparty_data.currency_cd length = 3   
         label = 'Currency code',
      counterparty_data.turnover_amt length = 8   
         format = 15.2
         label = 'Turnover',
      counterparty_data.total_assets_amt length = 8   
         format = 15.2
         label = 'Balance sheet total assets (sv. balansomslutning)',
      counterparty_data.employee_cnt length = 4   
         format = 8.
         label = 'Number of employees',
      counterparty_data.mid_rate length = 8   
         format = 10.6
         label = 'Mean value of one base currency unit in currency (värdet på basvalutan i valutan)',
      legal_proceedings_final.min_of_valid_from_date as valid_from_date length = 4   
         format = findfdd10.,
      legal_proceedings_final.customer_warning_cd length = 3   
         label = 'Restriction code (CODES.code_number_cd=''16'')'
   from
      work.counterparty_data as counterparty_data left join 
      work.legal_proceedings_final as legal_proceedings_final
         on
         (
            counterparty_data.information_date = legal_proceedings_final.information_date
            and counterparty_data.bank_id = legal_proceedings_final.bank_id
            and counterparty_data.ssn_id = legal_proceedings_final.customer_ssn_id
         ) left join 
      work.par_filters as par_filters
         on
         (
            counterparty_data.information_date = par_filters.information_date
            and counterparty_data.bank_id = par_filters.bank_id
            and (counterparty_data.customer_id = par_filters.code_value_char
            and par_filters.target_column = 'customer_id')
         )
   where
      par_filters.code_value_char IS MISSING 
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005IZ * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_dm.COUNTERPARTY_INSTRUMENT        A5ZNM6KG.BG0006J6 * 
 * Target Table:    shadow_OUTPUT0 - work.counterparty    A5ZNM6KG.BV0004ML * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005IZ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_dm.COUNTERPARTY_INSTRUMENT); 

%let _INPUT_count = 1; 
%let _INPUT = mac_dm.COUNTERPARTY_INSTRUMENT;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.COUNTERPARTY_INSTRUMENT%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Counterparty-instrument dataset);

%let _INPUT0 = mac_dm.COUNTERPARTY_INSTRUMENT;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.COUNTERPARTY_INSTRUMENT%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Counterparty-instrument dataset);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.counterparty;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004ML%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id counterparty_identifier 
        counterparty_role account_number_official original_account_id 
        loaded_dt;

%let _OUTPUT0 = work.counterparty;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004ML%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id counterparty_identifier 
        counterparty_role account_number_official original_account_id 
        loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete counterparty;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id counterparty_identifier 
        counterparty_role account_number_official original_account_id 
        loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id counterparty_identifier 
        counterparty_role account_number_official original_account_id 
        loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005J0 * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_dm.PROTECTION_PROVIDERS           A5ZNM6KG.BG0006J7 * 
 * Target Table:    shadow_OUTPUT0 -                      A5ZNM6KG.BV0004MM * 
 *                   work.protection_providers                              * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005J0);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_dm.PROTECTION_PROVIDERS); 

%let _INPUT_count = 1; 
%let _INPUT = mac_dm.PROTECTION_PROVIDERS;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.PROTECTION_PROVIDERS%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Protection Providers dataset);

%let _INPUT0 = mac_dm.PROTECTION_PROVIDERS;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.PROTECTION_PROVIDERS%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Protection Providers dataset);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.protection_providers;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004MM%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id protection_identifier 
        protection_provider_identifier name stat_sector_cd loaded_dt;

%let _OUTPUT0 = work.protection_providers;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004MM%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id protection_identifier 
        protection_provider_identifier name stat_sector_cd loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete protection_providers;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id protection_identifier 
        protection_provider_identifier name stat_sector_cd loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id protection_identifier 
        protection_provider_identifier name stat_sector_cd loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005J1 * 
 * Transform:       Join                                                    * 
 * Description:     Select distinct counterparty_reference filtered by      * 
 *                   counterparties and protection_providers                * 
 *                                                                          * 
 * Source Tables:   Join -                                A5ZNM6KG.BV0004JW * 
 *                   work.counterparty_reference_orig                       * 
 *                  shadow_OUTPUT0 - work.counterparty    A5ZNM6KG.BV0004ML * 
 *                  shadow_OUTPUT0 -                      A5ZNM6KG.BV0004MM * 
 *                   work.protection_providers                              * 
 * Target Table:    Join - work.W4MQWBTP                  A5ZNM6KG.BV0004MN * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005J1);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W4MQWBTP;
quit;

proc sql;
   create view work.W4MQWBTP as
   select distinct
      counterparty_reference_orig.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      counterparty_reference_orig.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      counterparty_reference_orig.counterparty_identifier length = 60   
         label = 'Counterparty Identifier',
      counterparty_reference_orig.ssn_id length = 20   
         label = 'Social security / organisation number',
      counterparty_reference_orig.customer_type length = 3   
         format = 3.
         label = '1=Private, 2=Coorp.cust.',
      counterparty_reference_orig.name length = 150   
         label = 'Customer Name (All customers)',
      counterparty_reference_orig.street_address length = 50   
         label = 'Street address',
      counterparty_reference_orig.post_office_number length = 10   
         label = 'Post office number',
      counterparty_reference_orig.country_cd length = 2   
         label = 'Address-country code',
      counterparty_reference_orig.post_office_name length = 40   
         label = 'Post office name',
      counterparty_reference_orig.legal_form_cd length = 2   
         label = 'Juridisk Form',
      counterparty_reference_orig.stat_sector_cd length = 6   
         label = 'Sektorkod. Obs : 6 siffror.',
      counterparty_reference_orig.stat_branch_cd length = 6   
         label = 'Näringsgren. Obs: 6 siffror i kundreg. Ngrenkp färre siffror (fyll ut med nollor)',
      counterparty_reference_orig.occupational_status_cd length = 1   
         label = 'Occupational status (1=worker, 2=lower officer, 3=higher officer…..) of private customer',
      counterparty_reference_orig.lei length = 20   
         label = ' Legal Entity Identifier',
      counterparty_reference_orig.lei_expiry_date length = 4   
         format = findfdd10.
         label = 'Date when the LEI expires',
      counterparty_reference_orig.raiting_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Rating date',
      counterparty_reference_orig.currency_cd length = 3   
         label = 'Currency code',
      counterparty_reference_orig.turnover_amt length = 8   
         format = 15.2
         label = 'Turnover',
      counterparty_reference_orig.total_assets_amt length = 8   
         format = 15.2
         label = 'Balance sheet total assets (sv. balansomslutning)',
      counterparty_reference_orig.employee_cnt length = 4   
         format = 8.
         label = 'Number of employees',
      counterparty_reference_orig.mid_rate length = 8   
         format = 10.6
         label = 'Mean value of one base currency unit in currency (värdet på basvalutan i valutan)',
      counterparty_reference_orig.valid_from_date length = 4   
         format = findfdd10.,
      counterparty_reference_orig.customer_warning_cd length = 3   
         label = 'Restriction code (CODES.code_number_cd=''16'')'
   from
      work.counterparty_reference_orig as counterparty_reference_orig left join 
      work.counterparty as counterparty
         on
         (
            counterparty_reference_orig.information_date = counterparty.information_date
            and counterparty_reference_orig.counterparty_identifier = counterparty.counterparty_identifier
         ) left join 
      work.protection_providers as protection_providers
         on
         (
            counterparty_reference_orig.information_date = protection_providers.information_date
            and counterparty_reference_orig.counterparty_identifier = protection_providers.protection_provider_identifier
         )
   where
      counterparty.counterparty_identifier NOT IS MISSING 
      or protection_providers.protection_provider_identifier NOT IS MISSING 
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0005FV * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W4MQWBTP                  A5ZNM6KG.BV0004MN * 
 * Target Table:    Extract - work.W13191UH               A5ZNM6KG.BV0004JX * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FV);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4MQWBTP); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W13191UH;
quit;

data _null_;
   put "NOTE: The following column(s) do not have a column mapping, so the"
        " value(s) will be set to missing: reporting_agent_identifier,"
        " legal_entity_identifier_lei,    counterparty_id_type,"
        " counterparty_id_desc, national_identifier,   "
        " international_identifier, riad, head_office_undertaking_id,   "
        " immediate_parent_undertaking_id, ultimate_parent_undertaking_id,   "
        " address_street, address_city_town_village, address_postal_code,   "
        " address_country, legal_form, institutional_sector,"
        " economic_activity,    status_of_legal_proceedings,"
        " date_of_init_of_legal_proceed, enterprise_size,   "
        " date_of_enterprise_size, number_of_employees, balance_sheet_total, "
        "   annual_turnover, accounting_standard";
run;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W13191UH as
      select
         information_date,
         "" as reporting_agent_identifier length = 60
            label = 'Reporting agent identifier',
         counterparty_identifier,
         "" as legal_entity_identifier_lei length = 20
            label = 'Legal entity identifier (LEI)',
         "" as counterparty_id_type length = 30
            label = 'Identifier type',
         "" as counterparty_id_desc length = 255
            label = 'Description of Other identifier type',
         "" as national_identifier length = 50
            label = 'National identifier',
         "" as international_identifier length = 30
            label = 'International organisation identifier',
         "" as riad length = 50
            label = 'RIAD code',
         "" as head_office_undertaking_id length = 60
            label = 'Head office undertaking identifier',
         "" as immediate_parent_undertaking_id length = 60
            label = 'Immediate parent undertaking identifier',
         "" as ultimate_parent_undertaking_id length = 60
            label = 'Ultimate parent undertaking identifier',
         name,
         "" as address_street length = 255
            label = 'Address: street',
         "" as address_city_town_village length = 255
            label = 'Address: city/town/village',
         "" as address_postal_code length = 255
            label = 'Address: postal code',
         "" as address_country length = 2
            label = 'Address: country',
         "" as legal_form length = 20
            label = 'Legal form',
         "" as institutional_sector length = 15
            label = 'Institutional sector',
         "" as economic_activity length = 5
            label = 'Economic activity',
         "" as status_of_legal_proceedings length = 15
            label = 'Status of legal proceedings',
         . as date_of_init_of_legal_proceed length = 8
            format = findfdd10.
            label = 'Date of initiation of legal proceedings',
         "" as enterprise_size length = 15
            label = 'Enterprise size',
         . as date_of_enterprise_size length = 8
            format = findfdd10.
            label = 'Date of enterprise size',
         . as number_of_employees length = 8
            format = 15.4
            label = 'Number of employees',
         . as balance_sheet_total length = 8
            format = 15.2
            label = 'Balance sheet total',
         . as annual_turnover length = 8
            format = 15.2
            label = 'Annual turnover',
         "" as accounting_standard length = 15
            label = 'Accounting standard',
         bank_id,
         ssn_id,
         customer_type,
         street_address,
         post_office_number,
         country_cd,
         post_office_name,
         legal_form_cd,
         stat_sector_cd,
         stat_branch_cd,
         occupational_status_cd,
         lei,
         lei_expiry_date,
         raiting_date,
         currency_cd,
         turnover_amt,
         total_assets_amt,
         employee_cnt,
         mid_rate,
         valid_from_date,
         customer_warning_cd,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = datetime20.
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W13191UH;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0005FU * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W13191UH               A5ZNM6KG.BV0004JX * 
 * Target Table:    mac_dm.COUNTERPARTY_REFERENCE         A5ZNM6KG.BG0006IZ * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005FU);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W13191UH); 

%let _INPUT_count = 1; 
%let _INPUT = work.W13191UH;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004JX%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W13191UH;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV0004JX%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mac_dm.COUNTERPARTY_REFERENCE;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.COUNTERPARTY_REFERENCE%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Counterparty Reference dataset);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier counterparty_identifier 
        legal_entity_identifier_lei counterparty_id_type counterparty_id_desc 
        national_identifier international_identifier riad 
        head_office_undertaking_id immediate_parent_undertaking_id 
        ultimate_parent_undertaking_id name address_street 
        address_city_town_village address_postal_code address_country 
        legal_form institutional_sector economic_activity 
        status_of_legal_proceedings date_of_init_of_legal_proceed 
        enterprise_size date_of_enterprise_size number_of_employees 
        balance_sheet_total annual_turnover accounting_standard bank_id ssn_id 
        customer_type street_address post_office_number country_cd 
        post_office_name legal_form_cd stat_sector_cd stat_branch_cd 
        occupational_status_cd lei lei_expiry_date customer_warning_cd 
        valid_from_date raiting_date currency_cd mid_rate employee_cnt 
        total_assets_amt turnover_amt loaded_dt;

%let _OUTPUT0 = mac_dm.COUNTERPARTY_REFERENCE;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.COUNTERPARTY_REFERENCE%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Counterparty Reference dataset);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier counterparty_identifier 
        legal_entity_identifier_lei counterparty_id_type counterparty_id_desc 
        national_identifier international_identifier riad 
        head_office_undertaking_id immediate_parent_undertaking_id 
        ultimate_parent_undertaking_id name address_street 
        address_city_town_village address_postal_code address_country 
        legal_form institutional_sector economic_activity 
        status_of_legal_proceedings date_of_init_of_legal_proceed 
        enterprise_size date_of_enterprise_size number_of_employees 
        balance_sheet_total annual_turnover accounting_standard bank_id ssn_id 
        customer_type street_address post_office_number country_cd 
        post_office_name legal_form_cd stat_sector_cd stat_branch_cd 
        occupational_status_cd lei lei_expiry_date customer_warning_cd 
        valid_from_date raiting_date currency_cd mid_rate employee_cnt 
        total_assets_amt turnover_amt loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier counterparty_identifier 
        legal_entity_identifier_lei counterparty_id_type counterparty_id_desc 
        national_identifier international_identifier riad 
        head_office_undertaking_id immediate_parent_undertaking_id 
        ultimate_parent_undertaking_id name address_street 
        address_city_town_village address_postal_code address_country 
        legal_form institutional_sector economic_activity 
        status_of_legal_proceedings date_of_init_of_legal_proceed 
        enterprise_size date_of_enterprise_size number_of_employees 
        balance_sheet_total annual_turnover accounting_standard bank_id ssn_id 
        customer_type street_address post_office_number country_cd 
        post_office_name legal_form_cd stat_sector_cd stat_branch_cd 
        occupational_status_cd lei lei_expiry_date customer_warning_cd 
        valid_from_date raiting_date currency_cd mid_rate employee_cnt 
        total_assets_amt turnover_amt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier counterparty_identifier 
        legal_entity_identifier_lei counterparty_id_type counterparty_id_desc 
        national_identifier international_identifier riad 
        head_office_undertaking_id immediate_parent_undertaking_id 
        ultimate_parent_undertaking_id name address_street 
        address_city_town_village address_postal_code address_country 
        legal_form institutional_sector economic_activity 
        status_of_legal_proceedings date_of_init_of_legal_proceed 
        enterprise_size date_of_enterprise_size number_of_employees 
        balance_sheet_total annual_turnover accounting_standard bank_id ssn_id 
        customer_type street_address post_office_number country_cd 
        post_office_name legal_form_cd stat_sector_cd stat_branch_cd 
        occupational_status_cd lei lei_expiry_date customer_warning_cd 
        valid_from_date raiting_date currency_cd mid_rate employee_cnt 
        total_assets_amt turnover_amt loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mac_dm nolist; 
   modify COUNTERPARTY_REFERENCE(ALTER=&alterpass. ); 
      index create primary_index = (information_date bank_id counterparty_identifier)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

