/**************************************************************************** 
 * Job:             mac_resu.protection_providers         A5M8HTKH.BO0000JC * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mac/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Tables:   mac_dm.PROTECTION_PROVIDERS           A5M8HTKH.BB0000P5 * 
 *                  mac_ctrl.PAR_INVALID_ROW_RULES        A5M8HTKH.BB00019B * 
 * Target Table:    mac_resu.PROTECTION_PROVIDERS         A5M8HTKH.BB0000SZ * 
 *                                                                          * 
 * Generated on:    Tuesday, August 20, 2019 3:20:21 PM EEST                * 
 * Generated by:    mrantonen                                               * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000JC);
%let etls_jobName = %nrquote(mac_resu.protection_providers);
%let etls_userID = %nrquote(mrantonen);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001S1 * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_dm.PROTECTION_PROVIDERS           A5M8HTKH.BB0000P5 * 
 * Target Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR000173 * 
 *                   work.protection_providers_orig                         * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001S1);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_dm.PROTECTION_PROVIDERS); 

%let _INPUT_count = 1; 
%let _INPUT = mac_dm.PROTECTION_PROVIDERS;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.PROTECTION_PROVIDERS%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Protection Providers dataset);

%let _INPUT0 = mac_dm.PROTECTION_PROVIDERS;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.PROTECTION_PROVIDERS%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Protection Providers dataset);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.protection_providers_orig;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000173%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        bank_id protection_provider_identifier name stat_sector_cd loaded_dt;

%let _OUTPUT0 = work.protection_providers_orig;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000173%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        bank_id protection_provider_identifier name stat_sector_cd loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete protection_providers_orig;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        bank_id protection_provider_identifier name stat_sector_cd loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        bank_id protection_provider_identifier name stat_sector_cd loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            code_converter                        A5M8HTKH.BU0001S2 * 
 * Transform:       code_converter                                          * 
 * Description:     Convert data to AnaCredit codevalues                    * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR000173 * 
 *                   work.protection_providers_orig                         * 
 * Target Table:    code_converter_OUTPUT0 -              A5M8HTKH.BR000174 * 
 *                   work.W7EWM1EM                                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001S2);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.protection_providers_orig); 

%let _INPUT_count = 1; 
%let _INPUT = work.protection_providers_orig;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000173%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.protection_providers_orig;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000173%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W7EWM1EM;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/code_converter_OUTPUT0_A5M8HTKH.BR000174%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type;
%let _OUTPUT_col_count = 6;
%let _OUTPUT_col0_name = information_date;
%let _OUTPUT_col0_table = work.W7EWM1EM;
%let _OUTPUT_col0_length = 4;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = FINDFDD10.;
%let _OUTPUT_col0_informat = DDMMYY10.;
%let _OUTPUT_col0_label = %nrquote(Information date of the record);
%let _OUTPUT_col0_input0 = information_date;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = information_date;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = reporting_agent_identifier;
%let _OUTPUT_col1_table = work.W7EWM1EM;
%let _OUTPUT_col1_length = 60;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(Reporting agent identifier);
%let _OUTPUT_col1_input0 = reporting_agent_identifier;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = reporting_agent_identifier;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = observed_agent_identifier;
%let _OUTPUT_col2_table = work.W7EWM1EM;
%let _OUTPUT_col2_length = 60;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Observed agent identifier);
%let _OUTPUT_col2_input0 = observed_agent_identifier;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = observed_agent_identifier;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = protection_identifier;
%let _OUTPUT_col3_table = work.W7EWM1EM;
%let _OUTPUT_col3_length = 60;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = ;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(Protection identifier);
%let _OUTPUT_col3_input0 = protection_identifier;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = protection_identifier;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = counterparty_identifier;
%let _OUTPUT_col4_table = work.W7EWM1EM;
%let _OUTPUT_col4_length = 60;
%let _OUTPUT_col4_type = $;
%let _OUTPUT_col4_format = ;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(Counterparty identifier %(i.e. protection provider identifier%));
%let _OUTPUT_col4_input0 = counterparty_identifier;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = counterparty_identifier;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = protection_provider_type;
%let _OUTPUT_col5_table = work.W7EWM1EM;
%let _OUTPUT_col5_length = 3;
%let _OUTPUT_col5_type = $;
%let _OUTPUT_col5_format = ;
%let _OUTPUT_col5_informat = ;
%let _OUTPUT_col5_label = %nrquote(Protection provider type);
%let _OUTPUT_col5_input0 = protection_provider_type;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = protection_provider_type;
%let _OUTPUT_col5_input_count = 1;

%let _OUTPUT0 = work.W7EWM1EM;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/code_converter_OUTPUT0_A5M8HTKH.BR000174%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type;
%let _OUTPUT0_col_count = 6;
%let _OUTPUT0_col0_name = information_date;
%let _OUTPUT0_col0_table = work.W7EWM1EM;
%let _OUTPUT0_col0_length = 4;
%let _OUTPUT0_col0_type = ;
%let _OUTPUT0_col0_format = FINDFDD10.;
%let _OUTPUT0_col0_informat = DDMMYY10.;
%let _OUTPUT0_col0_label = %nrquote(Information date of the record);
%let _OUTPUT0_col0_input0 = information_date;
%let _OUTPUT0_col0_exp = ;
%let _OUTPUT0_col0_input = information_date;
%let _OUTPUT0_col0_input_count = 1;
%let _OUTPUT0_col1_name = reporting_agent_identifier;
%let _OUTPUT0_col1_table = work.W7EWM1EM;
%let _OUTPUT0_col1_length = 60;
%let _OUTPUT0_col1_type = $;
%let _OUTPUT0_col1_format = ;
%let _OUTPUT0_col1_informat = ;
%let _OUTPUT0_col1_label = %nrquote(Reporting agent identifier);
%let _OUTPUT0_col1_input0 = reporting_agent_identifier;
%let _OUTPUT0_col1_exp = ;
%let _OUTPUT0_col1_input = reporting_agent_identifier;
%let _OUTPUT0_col1_input_count = 1;
%let _OUTPUT0_col2_name = observed_agent_identifier;
%let _OUTPUT0_col2_table = work.W7EWM1EM;
%let _OUTPUT0_col2_length = 60;
%let _OUTPUT0_col2_type = $;
%let _OUTPUT0_col2_format = ;
%let _OUTPUT0_col2_informat = ;
%let _OUTPUT0_col2_label = %nrquote(Observed agent identifier);
%let _OUTPUT0_col2_input0 = observed_agent_identifier;
%let _OUTPUT0_col2_exp = ;
%let _OUTPUT0_col2_input = observed_agent_identifier;
%let _OUTPUT0_col2_input_count = 1;
%let _OUTPUT0_col3_name = protection_identifier;
%let _OUTPUT0_col3_table = work.W7EWM1EM;
%let _OUTPUT0_col3_length = 60;
%let _OUTPUT0_col3_type = $;
%let _OUTPUT0_col3_format = ;
%let _OUTPUT0_col3_informat = ;
%let _OUTPUT0_col3_label = %nrquote(Protection identifier);
%let _OUTPUT0_col3_input0 = protection_identifier;
%let _OUTPUT0_col3_exp = ;
%let _OUTPUT0_col3_input = protection_identifier;
%let _OUTPUT0_col3_input_count = 1;
%let _OUTPUT0_col4_name = counterparty_identifier;
%let _OUTPUT0_col4_table = work.W7EWM1EM;
%let _OUTPUT0_col4_length = 60;
%let _OUTPUT0_col4_type = $;
%let _OUTPUT0_col4_format = ;
%let _OUTPUT0_col4_informat = ;
%let _OUTPUT0_col4_label = %nrquote(Counterparty identifier %(i.e. protection provider identifier%));
%let _OUTPUT0_col4_input0 = counterparty_identifier;
%let _OUTPUT0_col4_exp = ;
%let _OUTPUT0_col4_input = counterparty_identifier;
%let _OUTPUT0_col4_input_count = 1;
%let _OUTPUT0_col5_name = protection_provider_type;
%let _OUTPUT0_col5_table = work.W7EWM1EM;
%let _OUTPUT0_col5_length = 3;
%let _OUTPUT0_col5_type = $;
%let _OUTPUT0_col5_format = ;
%let _OUTPUT0_col5_informat = ;
%let _OUTPUT0_col5_label = %nrquote(Protection provider type);
%let _OUTPUT0_col5_input0 = protection_provider_type;
%let _OUTPUT0_col5_exp = ;
%let _OUTPUT0_col5_input = protection_provider_type;
%let _OUTPUT0_col5_input_count = 1;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W7EWM1EM;
quit;

%let target_table = %nrquote(PROTECTION_PROVIDERS            );

/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type;
%code_converter(source=&_INPUT0.,target=&target_table., output=&_OUTPUT0.,keep=&_OUTPUT0_keep.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end code_converter **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001ZZ * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_ctrl.PAR_INVALID_ROW_RULES        A5M8HTKH.BB00019B * 
 * Target Table:    shadow_OUTPUT0 - work.WGUR3YQ         A5M8HTKH.BR0001D0 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001ZZ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_ctrl.PAR_INVALID_ROW_RULES); 

%let _INPUT_count = 1; 
%let _INPUT = mac_ctrl.PAR_INVALID_ROW_RULES;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_INVALID_ROW_RULES%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Parameter table to rule out invalid rows from the data);

%let _INPUT0 = mac_ctrl.PAR_INVALID_ROW_RULES;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_INVALID_ROW_RULES%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Parameter table to rule out invalid rows from the data);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.WGUR3YQ;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0001D0%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;

%let _OUTPUT0 = work.WGUR3YQ;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0001D0%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete WGUR3YQ;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date surrow_id target_libname target_table where_clause 
        name loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU000200 * 
 * Transform:       Extract                                                 * 
 * Description:     Only PROTECTION_PROVIDERS table deletions               * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 - work.WGUR3YQ         A5M8HTKH.BR0001D0 * 
 * Target Table:    Extract -                             A5M8HTKH.BR0001D1 * 
 *                   work.PROTECTION_PROV_DELETIONS                         * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000200);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.WGUR3YQ); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete PROTECTION_PROV_DELETIONS;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.PROTECTION_PROV_DELETIONS as
      select
         information_date,
         where_clause
   from &SYSLAST
      where UPPER(TRIM(target_table))='PROTECTION_PROVIDERS'
   ;
quit;

%let SYSLAST = work.PROTECTION_PROV_DELETIONS;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*---- Start of User Written Code  ----*/ 

%include "//sasdw/prod/mac/programs/macros/deletewithparam.sas" / source2;

%deletewithparam(W7EWM1EM, PROTECTION_PROV_DELETIONS);
/*---- End of User Written Code  ----*/ 

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001S3 * 
 * Transform:       Extract                                                 * 
 * Description:     Select distinct                                         * 
 *                                                                          * 
 * Source Table:    code_converter_OUTPUT0 -              A5M8HTKH.BR000174 * 
 *                   work.W7EWM1EM                                          * 
 * Target Table:    Extract - work.W7EWNV24               A5M8HTKH.BR000175 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001S3);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W7EWM1EM); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W7EWNV24;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W7EWNV24 as
      select distinct
         (&active_date.) as information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date of the record',
         reporting_agent_identifier,
         observed_agent_identifier,
         protection_identifier,
         counterparty_identifier,
         protection_provider_type,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W7EWNV24;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0001S4 * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W7EWNV24               A5M8HTKH.BR000175 * 
 * Target Table:    mac_resu.PROTECTION_PROVIDERS         A5M8HTKH.BB0000SZ * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001S4);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W7EWNV24); 

%let _INPUT_count = 1; 
%let _INPUT = work.W7EWNV24;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR000175%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W7EWNV24;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR000175%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mac_resu.PROTECTION_PROVIDERS;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_path = %nrquote(/dw_solution/mac/data/resu/mac_resu.PROTECTION_PROVIDERS%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Protection Providers dataset);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        loaded_dt;

%let _OUTPUT0 = mac_resu.PROTECTION_PROVIDERS;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_path = %nrquote(/dw_solution/mac/data/resu/mac_resu.PROTECTION_PROVIDERS%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Protection Providers dataset);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier observed_agent_identifier 
        protection_identifier counterparty_identifier protection_provider_type 
        loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mac_resu nolist; 
   modify PROTECTION_PROVIDERS(ALTER=&alterpass. ); 
      index create primary_index = (information_date reporting_agent_identifier 
                      observed_agent_identifier protection_identifier 
                      counterparty_identifier)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

