/**************************************************************************** 
 * Job:             mac_dm.account_data                   A5M8HTKH.BO0000IQ * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: aablstgsas21                                            * 
 * Port:            8561                                                    * 
 * Location:        /dw_solution/mac/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Tables:   dw_dw.ACCOUNT_MONTHLY_INTEREST        A5M8HTKH.BB00002L * 
 *                  dw_dw.CREDIT_IN_DEFAULT               A5M8HTKH.BB00005M * 
 *                  dw_dw.ACCOUNT                         A5M8HTKH.BB000026 * 
 *                  dw_dw.CUSTOMER                        A5M8HTKH.BB000066 * 
 *                  dw_dw.CREDITS_ON_COLLECTION           A5M8HTKH.BB00005U * 
 *                  dw_dw.EXCHANGE_RATES                  A5M8HTKH.BB000073 * 
 *                  dw_dw.ACCOUNT_DAILY                   A5M8HTKH.BB00002B * 
 *                  dw_dw.ACCOUNT_DAILY_H                 A5M8HTKH.BB00002C * 
 *                  dw_dw.LOAN_ADDITIONAL_DATA            A5M8HTKH.BB00007J * 
 *                  dw_dw.UNATTENDED_LOANS                A5M8HTKH.BB0000BD * 
 *                  dw_dw.LIMIT                           A5M8HTKH.BB00007F * 
 *                  mac_ctrl.PAR_FILTERS                  A5M8HTKH.BB0000NT * 
 *                  dw_dw.EXCHANGE_RATES_H                A5M8HTKH.BB000074 * 
 *                  dw_dw.ACCOUNT_DAILY_H                 A5M8HTKH.BB00002C * 
 * Target Table:    mac_dm.ACCOUNT_DATA                   A5M8HTKH.BB0000NX * 
 *                                                                          * 
 * Generated on:    den 9 augusti 2023 kl 13:08 CEST                        * 
 * Generated by:    klindsko                                                * 
 * Version:         SAS Data Integration Studio 4.905                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000IQ);
%let etls_jobName = %nrquote(mac_dm.account_data);
%let etls_userID = %nrquote(klindsko);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%let syscc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NE * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT                         A5M8HTKH.BB000026 * 
 * Target Table:    ACCOUNT - work.account                A5M8HTKH.BR000133 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NE);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.ACCOUNT;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.ACCOUNT;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.account;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/ACCOUNT_A5M8HTKH.BR000133%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.account;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/ACCOUNT_A5M8HTKH.BR000133%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete account;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NF * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.CUSTOMER                        A5M8HTKH.BB000066 * 
 * Target Table:    CUSTOMER - work.customer              A5M8HTKH.BR000134 * 
 *                                                                          * 
 * Warnings:                                                                * 
 * Mapping of the target column sole_propietor_holder_id is too short for   * 
 * the specified source column sole_propietor_holder_id.  Values will be    * 
 *  truncated.                                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NF);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.CUSTOMER); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.CUSTOMER;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CUSTOMER%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.CUSTOMER;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CUSTOMER%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.customer;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/CUSTOMER_A5M8HTKH.BR000134%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.customer;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/CUSTOMER_A5M8HTKH.BR000134%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete customer;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id customer_id ssn_id customer_type birth_date 
        gender_cd AAB_employee_status_cd opened_date changed_date 
        deceased_date name person_last_name person_first_name co_name 
        street_address street_address2 post_office_number country_cd 
        state_province_cd post_office_name municipality_cd adress_ok_cd 
        result_office_id lang_cd citizenship_cd tax_country_cd legal_form_cd 
        stat_sector_cd stat_branch_cd phone_country_nr phone_area_nr 
        phone_number_nr work_phone_country_nr work_phone_area_nr 
        work_phone_number_nr cell_phone_country_nr cell_phone_area_nr 
        cell_phone_number_nr other_cell_phone_countr_nr 
        other_cell_phone_area_nr other_cell_phone_number_nr email work_email 
        direct_advertisment_cd electr_advertisment_cd advisor1_id advisor2_id 
        issue_country_cd foreign_tax_id deviant_tax_cd tax_pct id_doc_nr 
        id_doc_exp_date id_doc_type_cd id_doc_country_cd id_doc_copy 
        insider_cd x_sign_id tax_form_cd tax_form_date empl_situation_cd 
        empl_situation_start_date politically_exposed occupational_status_cd 
        profession service_main_purpose_cd payments_in_cnt payments_in_amt 
        payments_out_cnt payments_out_amt foreign_payments_out_cnt 
        relation_boardmember relation_boardmember_date 
        net_wage_income_monthly_amt net_capital_income_yearly_amt 
        net_other_income_monthly_amt net_total_income_monthly_amt 
        main_bank_private main_bank_corp fax_country_nr fax_area_nr 
        fax_number_nr trade_register_date trade_register_number dismissed_date 
        treaty_stmt sole_propietor_holder_id under_construction_start_date 
        fiscal_period_month_nr fiscal_period_day_nr capital_coverage_cd 
        turnover_amt assets_total_amt employees_cnt signatory1_title 
        signatory2_title signatory3_title money_laundry_checked 
        money_laundry_check_date lei lei_expiry_date source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NG * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.CREDITS_ON_COLLECTION           A5M8HTKH.BB00005U * 
 * Target Table:    CREDITS_ON_COLLECTION -               A5M8HTKH.BR000135 * 
 *                   work.credits_on_collection                             * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NG);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.CREDITS_ON_COLLECTION); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.CREDITS_ON_COLLECTION;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CREDITS_ON_COLLECTION%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Credits on collection - 424);

%let _INPUT0 = dw_dw.CREDITS_ON_COLLECTION;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CREDITS_ON_COLLECTION%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Credits on collection - 424);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.credits_on_collection;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/CREDITS_ON_COLLECTION_A5M8HTKH.BR000135%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id original_account_id collection_amt 
        juridical_case_nr source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.credits_on_collection;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/CREDITS_ON_COLLECTION_A5M8HTKH.BR000135%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id original_account_id collection_amt 
        juridical_case_nr source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete credits_on_collection;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id original_account_id collection_amt 
        juridical_case_nr source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id original_account_id collection_amt 
        juridical_case_nr source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NH * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.CREDIT_IN_DEFAULT               A5M8HTKH.BB00005M * 
 * Target Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR000136 * 
 *                   work.credit_in_default                                 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NH);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.CREDIT_IN_DEFAULT); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.CREDIT_IN_DEFAULT;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CREDIT_IN_DEFAULT%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.CREDIT_IN_DEFAULT;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.CREDIT_IN_DEFAULT%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.credit_in_default;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000136%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id create_date default_reason_cd 
        default_start_date default_end_date default_trigger_account_id 
        source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.credit_in_default;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000136%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id create_date default_reason_cd 
        default_start_date default_end_date default_trigger_account_id 
        source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete credit_in_default;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id create_date default_reason_cd 
        default_start_date default_end_date default_trigger_account_id 
        source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id create_date default_reason_cd 
        default_start_date default_end_date default_trigger_account_id 
        source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001NI * 
 * Transform:       Extract                                                 * 
 * Description:     WHERE default_end_date IS MISSING                       * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR000136 * 
 *                   work.credit_in_default                                 * 
 * Target Table:    CREDIT_IN_DEFAULT -                   A5M8HTKH.BR000137 * 
 *                   work.credit_in_default_data                            * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NI);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.credit_in_default); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete credit_in_default_data;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.credit_in_default_data as
      select
         information_date,
         bank_id,
         account_id,
         default_reason_cd,
         default_start_date,
         default_end_date,
         default_trigger_account_id
   from &SYSLAST
      where default_end_date IS MISSING
   ;
quit;

%let SYSLAST = work.credit_in_default_data;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NJ * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.EXCHANGE_RATES                  A5M8HTKH.BB000073 * 
 * Target Table:    EXCHANGE_RATES_CURRENT -              A5M8HTKH.BR000138 * 
 *                   work.exchange_rates                                    * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NJ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.EXCHANGE_RATES); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.EXCHANGE_RATES;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.EXCHANGE_RATES%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.EXCHANGE_RATES;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.EXCHANGE_RATES%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.exchange_rates;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/EXCHANGE_RATES_CURRENT_A5M8HTKH.BR000138%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.exchange_rates;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/EXCHANGE_RATES_CURRENT_A5M8HTKH.BR000138%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete exchange_rates;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NK * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT_DAILY                   A5M8HTKH.BB00002B * 
 * Target Table:    ACCOUNT_DAILY -                       A5M8HTKH.BR000139 * 
 *                   work.account_daily_active_month                        * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NK);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT_DAILY); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.ACCOUNT_DAILY;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_DAILY%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.ACCOUNT_DAILY;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_DAILY%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.account_daily_active_month;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/ACCOUNT_DAILY_A5M8HTKH.BR000139%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.account_daily_active_month;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/ACCOUNT_DAILY_A5M8HTKH.BR000139%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete account_daily_active_month;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001NL * 
 * Transform:       Extract                                                 * 
 * Description:     Last quarter data of booked_balance_amt                 * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT_DAILY_H                 A5M8HTKH.BB00002C * 
 * Target Table:    ACCOUNT_DAILY_HIST -                  A5M8HTKH.BR00013A * 
 *                   work.account_daily_prev_qtr                            * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT_DAILY_H); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete account_daily_prev_qtr;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.account_daily_prev_qtr as
      select
         bank_id,
         account_id,
         booked_balance_amt   
            label = 'Booked Balance,Amount 15,2 (2 decimals)'
   from &SYSLAST
      where information_date = INTNX('QTR',&active_date,-1,'E')
   ;
quit;

%let SYSLAST = work.account_daily_prev_qtr;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0006H2 * 
 * Transform:       Extract                                                 * 
 * Description:     Booked_balance_amt for previous month                   * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT_DAILY_H                 A5M8HTKH.BB00002C * 
 * Target Table:    ACCOUNT_DAILY_HIST2 -                 A5M8HTKH.BR0004U0 * 
 *                   work.account_daily_prev_month                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0006H2);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT_DAILY_H); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete account_daily_prev_month;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.account_daily_prev_month as
      select
         bank_id,
         account_id,
         booked_balance_amt
   from &SYSLAST
      where information_date = INTNX('MONTH',&active_date,-1,'E')
   ;
quit;

%let SYSLAST = work.account_daily_prev_month;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NM * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.LOAN_ADDITIONAL_DATA            A5M8HTKH.BB00007J * 
 * Target Table:    LOAN_ADDITIONAL_DATA -                A5M8HTKH.BR00013B * 
 *                   work.loan_additional_data                              * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.LOAN_ADDITIONAL_DATA); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.LOAN_ADDITIONAL_DATA;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.LOAN_ADDITIONAL_DATA%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Additional data for loans);

%let _INPUT0 = dw_dw.LOAN_ADDITIONAL_DATA;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.LOAN_ADDITIONAL_DATA%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Additional data for loans);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.loan_additional_data;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/LOAN_ADDITIONAL_DATA_A5M8HTKH.BR00013B%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id payment_plan_cd 
        principal_payments_per_year_cnt interest_payments_per_year_cnt 
        principal_payment_amount fixed_rate_amount annuity_amount 
        next_principal_payment_date next_principal_payment_amount 
        next_interest_payment_date next_interest_amount next_fixed_rate_amount 
        next_annuity_amount next_interest_change_date 
        interest_period_start_date purpose_of_use_cd loan_end_date 
        agriculture_finance state_guarantee_owner_occupied 
        loan_cancellation_date actual_repayment_date 
        insurance_of_loan_amount_pct additional_loan_amount 
        renegotiated_loan_amount original_loan_amount 
        withdrawable_today_amount total_withdrawable_amount 
        payment_plan_principal payment_plan_interest 
        directdebiting_account_1_id directdebiting_account_2_id 
        prior_information notification_fee fixed_interest_rate_percent 
        calculated_end_date original_end_date total_due_interest_amount 
        total_due_principal_amount penalty_interest_pct margin_pct 
        unmanaged_days_cnt unmanaged_days_max_cnt interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.loan_additional_data;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/LOAN_ADDITIONAL_DATA_A5M8HTKH.BR00013B%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id payment_plan_cd 
        principal_payments_per_year_cnt interest_payments_per_year_cnt 
        principal_payment_amount fixed_rate_amount annuity_amount 
        next_principal_payment_date next_principal_payment_amount 
        next_interest_payment_date next_interest_amount next_fixed_rate_amount 
        next_annuity_amount next_interest_change_date 
        interest_period_start_date purpose_of_use_cd loan_end_date 
        agriculture_finance state_guarantee_owner_occupied 
        loan_cancellation_date actual_repayment_date 
        insurance_of_loan_amount_pct additional_loan_amount 
        renegotiated_loan_amount original_loan_amount 
        withdrawable_today_amount total_withdrawable_amount 
        payment_plan_principal payment_plan_interest 
        directdebiting_account_1_id directdebiting_account_2_id 
        prior_information notification_fee fixed_interest_rate_percent 
        calculated_end_date original_end_date total_due_interest_amount 
        total_due_principal_amount penalty_interest_pct margin_pct 
        unmanaged_days_cnt unmanaged_days_max_cnt interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete loan_additional_data;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id payment_plan_cd 
        principal_payments_per_year_cnt interest_payments_per_year_cnt 
        principal_payment_amount fixed_rate_amount annuity_amount 
        next_principal_payment_date next_principal_payment_amount 
        next_interest_payment_date next_interest_amount next_fixed_rate_amount 
        next_annuity_amount next_interest_change_date 
        interest_period_start_date purpose_of_use_cd loan_end_date 
        agriculture_finance state_guarantee_owner_occupied 
        loan_cancellation_date actual_repayment_date 
        insurance_of_loan_amount_pct additional_loan_amount 
        renegotiated_loan_amount original_loan_amount 
        withdrawable_today_amount total_withdrawable_amount 
        payment_plan_principal payment_plan_interest 
        directdebiting_account_1_id directdebiting_account_2_id 
        prior_information notification_fee fixed_interest_rate_percent 
        calculated_end_date original_end_date total_due_interest_amount 
        total_due_principal_amount penalty_interest_pct margin_pct 
        unmanaged_days_cnt unmanaged_days_max_cnt interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id payment_plan_cd 
        principal_payments_per_year_cnt interest_payments_per_year_cnt 
        principal_payment_amount fixed_rate_amount annuity_amount 
        next_principal_payment_date next_principal_payment_amount 
        next_interest_payment_date next_interest_amount next_fixed_rate_amount 
        next_annuity_amount next_interest_change_date 
        interest_period_start_date purpose_of_use_cd loan_end_date 
        agriculture_finance state_guarantee_owner_occupied 
        loan_cancellation_date actual_repayment_date 
        insurance_of_loan_amount_pct additional_loan_amount 
        renegotiated_loan_amount original_loan_amount 
        withdrawable_today_amount total_withdrawable_amount 
        payment_plan_principal payment_plan_interest 
        directdebiting_account_1_id directdebiting_account_2_id 
        prior_information notification_fee fixed_interest_rate_percent 
        calculated_end_date original_end_date total_due_interest_amount 
        total_due_principal_amount penalty_interest_pct margin_pct 
        unmanaged_days_cnt unmanaged_days_max_cnt interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NN * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT_MONTHLY_INTEREST        A5M8HTKH.BB00002L * 
 * Target Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR00013C * 
 *                   work.account_monthly_interest                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT_MONTHLY_INTEREST); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.ACCOUNT_MONTHLY_INTEREST;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_MONTHLY_INTEREST%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Account monthly interest - 106);

%let _INPUT0 = dw_dw.ACCOUNT_MONTHLY_INTEREST;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_MONTHLY_INTEREST%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Account monthly interest - 106);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.account_monthly_interest;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR00013C%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id interest_type_cd surrow_id 
        interest_amt gl_interest_amt amount_currency_cd gl_account_id 
        ledger_code account_type gl_account2_id book_date source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.account_monthly_interest;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR00013C%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id interest_type_cd surrow_id 
        interest_amt gl_interest_amt amount_currency_cd gl_account_id 
        ledger_code account_type gl_account2_id book_date source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete account_monthly_interest;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id interest_type_cd surrow_id 
        interest_amt gl_interest_amt amount_currency_cd gl_account_id 
        ledger_code account_type gl_account2_id book_date source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id interest_type_cd surrow_id 
        interest_amt gl_interest_amt amount_currency_cd gl_account_id 
        ledger_code account_type gl_account2_id book_date source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001NO * 
 * Transform:       Extract                                                 * 
 * Description:     sum(interest_am) WHERE interest_type_cd = ' ACCRUED'    * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR00013C * 
 *                   work.account_monthly_interest                          * 
 * Target Table:    ACCRUED_INTEREST -                    A5M8HTKH.BR00013D * 
 *                   work.accrued_interest                                  * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.account_monthly_interest); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete accrued_interest;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.accrued_interest as
      select
         information_date,
         bank_id,
         account_id,
         (sum(interest_amt)) as interest_amt length = 8
            format = 15.2
            label = 'Interest amount in amount_currency_cd',
         amount_currency_cd
   from &SYSLAST
      where interest_type_cd = 'ACCRUED'
   group by
      information_date,
      bank_id,
      account_id,
      amount_currency_cd
   ;
quit;

%let SYSLAST = work.accrued_interest;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NP * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.UNATTENDED_LOANS                A5M8HTKH.BB0000BD * 
 * Target Table:    UNATTENDED_LOANS -                    A5M8HTKH.BR00013E * 
 *                   work.unattented_loans                                  * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.UNATTENDED_LOANS); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.UNATTENDED_LOANS;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.UNATTENDED_LOANS%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Unattended loans - 206);

%let _INPUT0 = dw_dw.UNATTENDED_LOANS;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.UNATTENDED_LOANS%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Unattended loans - 206);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.unattented_loans;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/UNATTENDED_LOANS_A5M8HTKH.BR00013E%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id ledger_type_cd surrow_id due_date 
        actual_due_date ledger_amt source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.unattented_loans;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/UNATTENDED_LOANS_A5M8HTKH.BR00013E%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id ledger_type_cd surrow_id due_date 
        actual_due_date ledger_amt source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete unattented_loans;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id ledger_type_cd surrow_id due_date 
        actual_due_date ledger_amt source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id ledger_type_cd surrow_id due_date 
        actual_due_date ledger_amt source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NQ * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.LIMIT                           A5M8HTKH.BB00007F * 
 * Target Table:    LIMIT - work.limit                    A5M8HTKH.BR00013F * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.LIMIT); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.LIMIT;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.LIMIT%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.LIMIT;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.LIMIT%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.limit;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/LIMIT_A5M8HTKH.BR00013F%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id purpose_cd changed_date 
        expiry_date current_limit_amt max_limit_amt provision_rate_pct 
        provision_start_date provision_end_date provision_limit_amt 
        provision_accum_amt provision_left_amt overdraft_interest_pct 
        overdraft_days_cnt overdraft_days_max_cnt limit_capitalized_mon_cnt 
        source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.limit;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/LIMIT_A5M8HTKH.BR00013F%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id purpose_cd changed_date 
        expiry_date current_limit_amt max_limit_amt provision_rate_pct 
        provision_start_date provision_end_date provision_limit_amt 
        provision_accum_amt provision_left_amt overdraft_interest_pct 
        overdraft_days_cnt overdraft_days_max_cnt limit_capitalized_mon_cnt 
        source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete limit;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id purpose_cd changed_date 
        expiry_date current_limit_amt max_limit_amt provision_rate_pct 
        provision_start_date provision_end_date provision_limit_amt 
        provision_accum_amt provision_left_amt overdraft_interest_pct 
        overdraft_days_cnt overdraft_days_max_cnt limit_capitalized_mon_cnt 
        source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id purpose_cd changed_date 
        expiry_date current_limit_amt max_limit_amt provision_rate_pct 
        provision_start_date provision_end_date provision_limit_amt 
        provision_accum_amt provision_left_amt overdraft_interest_pct 
        overdraft_days_cnt overdraft_days_max_cnt limit_capitalized_mon_cnt 
        source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001NR * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_ctrl.PAR_FILTERS                  A5M8HTKH.BB0000NT * 
 * Target Table:    PAR_FILTERS - work.par_filters        A5M8HTKH.BR00013G * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NR);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_ctrl.PAR_FILTERS); 

%let _INPUT_count = 1; 
%let _INPUT = mac_ctrl.PAR_FILTERS;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_FILTERS%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Filtering data for AnaCredit);

%let _INPUT0 = mac_ctrl.PAR_FILTERS;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/ctrl/mac_ctrl.PAR_FILTERS%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Filtering data for AnaCredit);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.par_filters;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/PAR_FILTERS_A5M8HTKH.BR00013G%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;

%let _OUTPUT0 = work.par_filters;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/PAR_FILTERS_A5M8HTKH.BR00013G%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete par_filters;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id target_column value_type code_value_char 
        code_value_num loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5M8HTKH.BU0001NS * 
 * Transform:       Join                                                    * 
 * Description:     Select distinct                                         * 
 *                                                                          * 
 * Source Tables:   ACCOUNT - work.account                A5M8HTKH.BR000133 * 
 *                  CUSTOMER - work.customer              A5M8HTKH.BR000134 * 
 *                  CREDITS_ON_COLLECTION -               A5M8HTKH.BR000135 * 
 *                   work.credits_on_collection                             * 
 *                  CREDIT_IN_DEFAULT -                   A5M8HTKH.BR000137 * 
 *                   work.credit_in_default_data                            * 
 *                  EXCHANGE_RATES_CURRENT -              A5M8HTKH.BR000138 * 
 *                   work.exchange_rates                                    * 
 *                  ACCOUNT_DAILY -                       A5M8HTKH.BR000139 * 
 *                   work.account_daily_active_month                        * 
 *                  ACCOUNT_DAILY_HIST -                  A5M8HTKH.BR00013A * 
 *                   work.account_daily_prev_qtr                            * 
 *                  LOAN_ADDITIONAL_DATA -                A5M8HTKH.BR00013B * 
 *                   work.loan_additional_data                              * 
 *                  ACCRUED_INTEREST -                    A5M8HTKH.BR00013D * 
 *                   work.accrued_interest                                  * 
 *                  UNATTENDED_LOANS -                    A5M8HTKH.BR00013E * 
 *                   work.unattented_loans                                  * 
 *                  LIMIT - work.limit                    A5M8HTKH.BR00013F * 
 *                  PAR_FILTERS - work.par_filters        A5M8HTKH.BR00013G * 
 *                  dw_dw.EXCHANGE_RATES_H                A5M8HTKH.BB000074 * 
 *                  ACCOUNT_DAILY_HIST2 -                 A5M8HTKH.BR0004U0 * 
 *                   work.account_daily_prev_month                          * 
 * Target Table:    Join - work.W4P8HXZF                  A5M8HTKH.BR00013H * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NS);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W4P8HXZF;
quit;

proc sql;
   create view work.W4P8HXZF as
   select distinct
      account.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      account.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      account.account_id length = 20   
         label = 'Account Number (=key filed to other Account databases). Same format in both Finland and Sweden',
      account.account_number_official length = 20   
         label = 'Account Number, official, In Finland this field is same as ACCNBR, in Sweden it contains the official Swedish account number.',
      account.account_type_cd length = 3   
         label = 'CBS Account Type',
      account.owner_id length = 9   
         label = 'CBS Customer ID. Account owner',
      (cat(account.bank_id, account.owner_id)) as customer_id_mod length = 60,
      customer.name length = 150   
         label = 'Customer Name (All customers)',
      customer.stat_sector_cd length = 6   
         label = 'Sektorkod. Obs : 6 siffror.',
      credits_on_collection.original_account_id length = 14   
         label = 'Credit account id before it was on collection. 0 is allowed.',
      credit_in_default_data.default_reason_cd length = 3   
         label = 'Default reason code',
      (MIN(credit_in_default_data.default_start_date)) as default_start_date length = 4   
         format = findfdd10.,
      account.currency_cd length = 3   
         label = 'Account Currency',
      exchange_rates.mid_rate length = 8   
         format = 10.6
         label = 'Mean value of one base currency unit in currency (värdet på basvalutan i valutan)',
      (case when account.currency_cd = 'EUR' then 1
           else (case when EXCHANGE_RATES_H.mid_rate is not missing then EXCHANGE_RATES_H.mid_rate
            end)
      end) as opened_date_mid_rate length = 8   
         format = 10.6,
      account_daily_active_month.booked_balance_amt length = 8   
         format = 15.2
         label = 'Booked Balance,Amount 15,2 (2 decimals)',
      account_daily_prev_month.booked_balance_amt as booked_balance_amt_prev_month length = 8   
         format = 15.2
         label = 'Booked balance amount of previous month',
      account_daily_active_month.credit_ref_interest_cd length = 10   
         label = 'Credit : Reference interest code',
      account_daily_active_month.credit_interest_rate_pct length = 8   
         format = 8.4
         label = 'Credit: Interest rate (today). Ref.rate + Margin',
      account_daily_active_month.credit_margin_rate_pct length = 8   
         format = 8.4
         label = 'Credit: Margin rate (today) - Customer marginal.',
      account_daily_active_month.overdraft_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Overdraft day 1.',
      account_daily_prev_qtr.booked_balance_amt as booked_balance_amt_prev_qtr length = 8   
         format = 15.2
         label = 'Booked balance amount of previous quarter',
      loan_additional_data.loan_end_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'The contractual loan end date',
      loan_additional_data.original_loan_amount length = 8   
         format = 15.2
         label = 'The original loan amount  that was granted',
      loan_additional_data.total_withdrawable_amount length = 8   
         format = 15.2
         label = 'Total withdrawable amount',
      loan_additional_data.payment_plan_cd length = 1   
         label = 'Payment plan (0 = No, 1= Fixed, 2 = Annuity, 3 = Straight amortization, 4= Bullet)',
      loan_additional_data.principal_payments_per_year_cnt length = 3   
         format = 2.
         label = 'Number of principal payments per year.',
      loan_additional_data.interest_payments_per_year_cnt length = 3   
         format = 2.
         label = 'Number of interest payments per year',
      loan_additional_data.next_principal_payment_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Next principal payment date',
      loan_additional_data.next_interest_change_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Next interest change date',
      loan_additional_data.purpose_of_use_cd length = 4   
         label = 'The loans purpose of use',
      loan_additional_data.interest_cap_and_floor_type length = 1   
         label = 'Interest rate cap and floor type:''1'' = Interest corridor ''2'' = Interest rate cap '' '' = N/a If type is ''2'' then the floor rate percent is not in use',
      loan_additional_data.interest_cap_n_floor_start_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Interest corridor start date',
      loan_additional_data.interest_cap_n_floor_end_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Interest corridor end date',
      loan_additional_data.interest_cap_n_floor_f_rate_pct length = 8   
         format = 8.4
         label = 'Interest corridor floor rate',
      loan_additional_data.interest_cap_n_floor_c_rate_pct length = 8   
         format = 8.4
         label = 'Interest corridor ceiling rate',
      accrued_interest.interest_amt length = 8   
         format = 15.2
         label = 'Interest amount in amount_currency_cd',
      min(unattented_loans.actual_due_date) as actual_due_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Actual due date (used for calculating penalty interest if the loan due date is not a banking day)',
      sum(unattented_loans.ledger_amt) as ledger_amt length = 8   
         format = 15.2
         label = 'Ledger amount',
      limit.expiry_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Limit expiry date',
      limit.current_limit_amt length = 8   
         format = 15.2
         label = 'Current limit amount',
      (sum(max(-account_daily_active_month.booked_balance_amt,-limit.current_limit_amt), -account_daily_active_month.credit_interest_accrued_amt, 
                  loan_additional_data.total_withdrawable_amount)) as exposures_amt length = 8   
         format = 15.2
         label = 'Sum of exposures amount',
      account.shared length = 1   
         label = 'Account shared: 0=No, 1=Shared xxxx, 2=Shared yyyy',
      account.opened_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Account opened date',
      account.changed_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Account changed date',
      account.close_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Account closed date'
   from
      work.account as account left join 
      work.customer as customer
         on
         (
            account.information_date = customer.information_date
            and account.bank_id = customer.bank_id
            and account.owner_ssn_id = customer.ssn_id
         ) left join 
      work.credits_on_collection as credits_on_collection
         on
         (
            account.information_date = credits_on_collection.information_date
            and account.bank_id = credits_on_collection.bank_id
            and account.account_id = credits_on_collection.account_id
         ) left join 
      work.credit_in_default_data as credit_in_default_data
         on
         (
            account.information_date = credit_in_default_data.information_date
            and account.bank_id = credit_in_default_data.bank_id
            and account.account_id = credit_in_default_data.account_id
         ) left join 
      work.exchange_rates as exchange_rates
         on
         (
            account.information_date = exchange_rates.information_date
            and account.currency_cd = exchange_rates.currency_cd
         ) left join 
      dw_dw.EXCHANGE_RATES_H as EXCHANGE_RATES_H
         on
         (
            account.opened_date = EXCHANGE_RATES_H.information_date
            and account.currency_cd = EXCHANGE_RATES_H.currency_cd
         ) left join 
      work.account_daily_active_month as account_daily_active_month
         on
         (
            account.information_date = account_daily_active_month.information_date
            and account.account_id = account_daily_active_month.account_id
         ) left join 
      work.account_daily_prev_qtr as account_daily_prev_qtr
         on
         (
            account.bank_id = account_daily_prev_qtr.bank_id
            and account.account_id = account_daily_prev_qtr.account_id
         ) left join 
      work.loan_additional_data as loan_additional_data
         on
         (
            account.information_date = loan_additional_data.information_date
            and account.account_id = loan_additional_data.account_id
         ) left join 
      work.accrued_interest as accrued_interest
         on
         (
            account.information_date = accrued_interest.information_date
            and account.bank_id = accrued_interest.bank_id
            and account.account_id = accrued_interest.account_id
         ) left join 
      work.unattented_loans as unattented_loans
         on
         (
            account.information_date = unattented_loans.information_date
            and account.bank_id = unattented_loans.bank_id
            and account.account_id = unattented_loans.account_id
            and unattented_loans.actual_due_date <= unattented_loans.information_date
         ) left join 
      work.limit as limit
         on
         (
            account.information_date = limit.information_date
            and account.account_id = limit.account_id
         ) left join 
      work.par_filters as par_filters_account_type
         on
         (
            account.information_date = par_filters_account_type.information_date
            and account.bank_id = par_filters_account_type.bank_id
            and account.account_type_cd = par_filters_account_type.code_value_char
            and par_filters_account_type.target_column = 'account_type_cd'
         ) left join 
      work.par_filters as par_filters_account_id
         on
         (
            account.information_date = par_filters_account_id.information_date
            and account.bank_id = par_filters_account_id.bank_id
            and account.account_id = par_filters_account_id.code_value_char
            and par_filters_account_id.target_column = 'account_id'
         ) left join 
      work.par_filters as par_filters_customer_type
         on
         (
            customer.information_date = par_filters_customer_type.information_date
            and customer.bank_id = par_filters_customer_type.bank_id
            and customer.customer_type = par_filters_customer_type.code_value_num
            and par_filters_customer_type.target_column = 'customer_type'
         ) left join 
      work.par_filters as par_filters_stat_sector
         on
         (
            customer.information_date = par_filters_stat_sector.information_date
            and customer.bank_id = par_filters_stat_sector.bank_id
            and customer.stat_sector_cd = par_filters_stat_sector.code_value_char
            and par_filters_stat_sector.target_column = 'stat_sector_cd'
         ) left join 
      work.par_filters as par_filters_customer_id
         on
         (
            customer.information_date = par_filters_customer_id.information_date
            and customer.bank_id = par_filters_customer_id.bank_id
            and customer.customer_id = par_filters_customer_id.code_value_char
            and par_filters_customer_id.target_column = 'customer_id'
         ) left join 
      work.account_daily_prev_month as account_daily_prev_month
         on
         (
            account.bank_id = account_daily_prev_month.bank_id
            and account.account_id = account_daily_prev_month.account_id
         )
   where
      par_filters_account_type.code_value_char IS MISSING 
      and par_filters_account_id.code_value_char IS MISSING 
      and par_filters_customer_type.code_value_num IS MISSING 
      and par_filters_stat_sector.code_value_char IS MISSING 
      and par_filters_customer_id.code_value_char IS MISSING 
      and exchange_rates.bank_id = 'A'
      and EXCHANGE_RATES_H.bank_id <> 'B'
      and (account.close_date IS MISSING 
      or account.close_date >= INTNX('QTR',account.information_date,-1,'E'))
   group by
      account.information_date,
      account.bank_id,
      account.owner_id,
      account.account_id,
      account.account_number_official,
      customer_id_mod,
      account.account_type_cd,
      account.currency_cd,
      account.opened_date,
      account.changed_date,
      account.close_date,
      customer.name,
      credits_on_collection.original_account_id,
      credit_in_default_data.default_reason_cd,
      exchange_rates.mid_rate,
      account_daily_active_month.booked_balance_amt,
      account_daily_active_month.credit_ref_interest_cd,
      account_daily_active_month.credit_interest_rate_pct,
      account_daily_active_month.credit_margin_rate_pct,
      account_daily_active_month.overdraft_date,
      account_daily_prev_qtr.booked_balance_amt,
      accrued_interest.interest_amt,
      loan_additional_data.total_withdrawable_amount,
      loan_additional_data.original_loan_amount,
      loan_additional_data.loan_end_date,
      loan_additional_data.next_interest_change_date,
      loan_additional_data.payment_plan_cd,
      loan_additional_data.purpose_of_use_cd,
      loan_additional_data.principal_payments_per_year_cnt,
      loan_additional_data.next_principal_payment_date,
      loan_additional_data.interest_payments_per_year_cnt,
      loan_additional_data.interest_cap_and_floor_type,
      loan_additional_data.interest_cap_n_floor_start_date,
      loan_additional_data.interest_cap_n_floor_end_date,
      loan_additional_data.interest_cap_n_floor_f_rate_pct,
      loan_additional_data.interest_cap_n_floor_c_rate_pct,
      limit.current_limit_amt,
      limit.expiry_date,
      exposures_amt,
      opened_date_mid_rate,
      account.shared
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001NT * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W4P8HXZF                  A5M8HTKH.BR00013H * 
 * Target Table:    Extract - work.W1E3DFFO               A5M8HTKH.BR00013I * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NT);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4P8HXZF); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W1E3DFFO;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W1E3DFFO as
      select
         information_date,
         bank_id,
         account_id   
            label = 'Account Number',
         account_number_official   
            label = 'Account number official, In Finland this field is same as ACCNBR, in Sweden it contains the official Swedish account number',
         original_account_id   
            label = 'Credit account id before it was on collection. 0 is allowed',
         account_type_cd,
         owner_id,
         customer_id_mod   
            label = 'Modified customer identifier',
         name   
            label = 'Customer Name (all customers)',
         stat_sector_cd,
         opened_date,
         opened_date_mid_rate   
            label = 'Mean value of one base currency nit in currency on accounts opening date',
         changed_date,
         close_date   
            label = 'Account close date',
         loan_end_date,
         purpose_of_use_cd,
         currency_cd   
            label = 'Account Currency code',
         mid_rate   
            label = 'Mean value of one base currency nit in currency',
         booked_balance_amt   
            label = 'Booked balance amount',
         booked_balance_amt_prev_month,
         booked_balance_amt_prev_qtr,
         total_withdrawable_amount,
         original_loan_amount   
            label = 'The original loan amount that was granted',
         current_limit_amt,
         expiry_date,
         interest_amt   
            label = 'Interest amount',
         credit_ref_interest_cd   
            label = 'Credit: Reference interest code',
         credit_interest_rate_pct,
         credit_margin_rate_pct   
            label = 'Credit: Margin rate (today). Customer marginal',
         next_interest_change_date,
         interest_cap_and_floor_type   
            label = 'Interest rate cap and floor type(1=Interest corridor,2=Interest rate cap, Empty=N/a, if type is 2 then the floor rate percent is not in use)',
         interest_cap_n_floor_start_date,
         interest_cap_n_floor_end_date,
         interest_cap_n_floor_f_rate_pct,
         interest_cap_n_floor_c_rate_pct,
         payment_plan_cd   
            label = 'Payment plan (0=No, 1=Fixed, 2=Annuity, 3=Straight amortization, 4=Bullet)',
         principal_payments_per_year_cnt length = 8   
            label = 'Number of principal payments per year',
         next_principal_payment_date,
         interest_payments_per_year_cnt length = 8   
            label = 'Number of principal payments per year',
         exposures_amt   
            label = 'Sum of exposures',
         ledger_amt,
         actual_due_date   
            label = 'Actual due date',
         default_reason_cd,
         default_start_date   
            informat = DDMMYY10.
            label = 'Default begin date',
         overdraft_date,
         shared   
            label = 'Account shared: 0=No, 1=Shared xxxx, 2=shared yyyy',
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W1E3DFFO;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0001NU * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W1E3DFFO               A5M8HTKH.BR00013I * 
 * Target Table:    mac_dm.ACCOUNT_DATA                   A5M8HTKH.BB0000NX * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001NU);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W1E3DFFO); 

%let _INPUT_count = 1; 
%let _INPUT = work.W1E3DFFO;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR00013I%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W1E3DFFO;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR00013I%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mac_dm.ACCOUNT_DATA;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(&altercommand.);
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.ACCOUNT_DATA%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd owner_id customer_id_mod name 
        stat_sector_cd opened_date opened_date_mid_rate changed_date 
        close_date loan_end_date purpose_of_use_cd currency_cd mid_rate 
        booked_balance_amt booked_balance_amt_prev_month 
        booked_balance_amt_prev_qtr total_withdrawable_amount 
        original_loan_amount current_limit_amt expiry_date interest_amt 
        credit_ref_interest_cd credit_interest_rate_pct credit_margin_rate_pct 
        next_interest_change_date interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        payment_plan_cd principal_payments_per_year_cnt 
        next_principal_payment_date interest_payments_per_year_cnt 
        exposures_amt ledger_amt actual_due_date default_reason_cd 
        default_start_date overdraft_date shared loaded_dt;

%let _OUTPUT0 = mac_dm.ACCOUNT_DATA;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(&altercommand.);
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.ACCOUNT_DATA%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd owner_id customer_id_mod name 
        stat_sector_cd opened_date opened_date_mid_rate changed_date 
        close_date loan_end_date purpose_of_use_cd currency_cd mid_rate 
        booked_balance_amt booked_balance_amt_prev_month 
        booked_balance_amt_prev_qtr total_withdrawable_amount 
        original_loan_amount current_limit_amt expiry_date interest_amt 
        credit_ref_interest_cd credit_interest_rate_pct credit_margin_rate_pct 
        next_interest_change_date interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        payment_plan_cd principal_payments_per_year_cnt 
        next_principal_payment_date interest_payments_per_year_cnt 
        exposures_amt ledger_amt actual_due_date default_reason_cd 
        default_start_date overdraft_date shared loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd owner_id customer_id_mod name 
        stat_sector_cd opened_date opened_date_mid_rate changed_date 
        close_date loan_end_date purpose_of_use_cd currency_cd mid_rate 
        booked_balance_amt booked_balance_amt_prev_month 
        booked_balance_amt_prev_qtr total_withdrawable_amount 
        original_loan_amount current_limit_amt expiry_date interest_amt 
        credit_ref_interest_cd credit_interest_rate_pct credit_margin_rate_pct 
        next_interest_change_date interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        payment_plan_cd principal_payments_per_year_cnt 
        next_principal_payment_date interest_payments_per_year_cnt 
        exposures_amt ledger_amt actual_due_date default_reason_cd 
        default_start_date overdraft_date shared loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd owner_id customer_id_mod name 
        stat_sector_cd opened_date opened_date_mid_rate changed_date 
        close_date loan_end_date purpose_of_use_cd currency_cd mid_rate 
        booked_balance_amt booked_balance_amt_prev_month 
        booked_balance_amt_prev_qtr total_withdrawable_amount 
        original_loan_amount current_limit_amt expiry_date interest_amt 
        credit_ref_interest_cd credit_interest_rate_pct credit_margin_rate_pct 
        next_interest_change_date interest_cap_and_floor_type 
        interest_cap_n_floor_start_date interest_cap_n_floor_end_date 
        interest_cap_n_floor_f_rate_pct interest_cap_n_floor_c_rate_pct 
        payment_plan_cd principal_payments_per_year_cnt 
        next_principal_payment_date interest_payments_per_year_cnt 
        exposures_amt ledger_amt actual_due_date default_reason_cd 
        default_start_date overdraft_date shared loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mac_dm nolist; 
   modify ACCOUNT_DATA(&altercommand. ); 
      index create primary_index = (information_date bank_id account_id)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

