/**************************************************************************** 
 * Job:             mac_dm.instrument_protection          A5M8HTKH.BO0000IZ * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mac/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Tables:   dw_dw.COLLATERAL                      A5M8HTKH.BB00004Q * 
 *                  dw_dw.ACCOUNT_COLLATERAL_LINK         A5M8HTKH.BB000027 * 
 *                  mac_dm.INSTRUMENT                     A5M8HTKH.BB0000OT * 
 *                  dw_dw.EXCHANGE_RATES                  A5M8HTKH.BB000073 * 
 *                  dw_dw.COLLATERAL_DISTRIBUTION         A5M8HTKH.BB00004R * 
 *                  dw_dw.PLEDGE                          A5M8HTKH.BB00008O * 
 * Target Table:    mac_dm.INSTRUMENT_PROTECTION          A5M8HTKH.BB0000OW * 
 *                                                                          * 
 * Generated on:    Tuesday, September 24, 2019 11:53:19 AM EEST            * 
 * Generated by:    ierkkila                                                * 
 * Version:         SAS Data Integration Studio 4.903                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000IZ);
%let etls_jobName = %nrquote(mac_dm.instrument_protection);
%let etls_userID = %nrquote(ierkkila);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001PN * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.COLLATERAL                      A5M8HTKH.BB00004Q * 
 * Target Table:    shadow_OUTPUT0 - work.collateral      A5M8HTKH.BR000152 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.COLLATERAL); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.COLLATERAL;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.COLLATERAL%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Collateral - 405);

%let _INPUT0 = dw_dw.COLLATERAL;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.COLLATERAL%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Collateral - 405);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.collateral;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000152%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id internal_collateral_id collateral_number 
        collateral_type_cd collateral_loan_value_amt 
        orig_collateral_loan_value_amt currency_cd source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.collateral;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000152%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id internal_collateral_id collateral_number 
        collateral_type_cd collateral_loan_value_amt 
        orig_collateral_loan_value_amt currency_cd source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete collateral;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id internal_collateral_id collateral_number 
        collateral_type_cd collateral_loan_value_amt 
        orig_collateral_loan_value_amt currency_cd source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id internal_collateral_id collateral_number 
        collateral_type_cd collateral_loan_value_amt 
        orig_collateral_loan_value_amt currency_cd source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001PO * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT_COLLATERAL_LINK         A5M8HTKH.BB000027 * 
 * Target Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR000153 * 
 *                   work.account_collateral_link                           * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT_COLLATERAL_LINK); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.ACCOUNT_COLLATERAL_LINK;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_COLLATERAL_LINK%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.ACCOUNT_COLLATERAL_LINK;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_COLLATERAL_LINK%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.account_collateral_link;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000153%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.account_collateral_link;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000153%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete account_collateral_link;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id internal_collateral_id 
        internal_pledge_id source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001PP * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.PLEDGE                          A5M8HTKH.BB00008O * 
 * Target Table:    shadow_OUTPUT0 - work.pledge          A5M8HTKH.BR000154 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.PLEDGE); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.PLEDGE;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.PLEDGE%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Pledge - 402);

%let _INPUT0 = dw_dw.PLEDGE;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.PLEDGE%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Pledge - 402);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.pledge;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000154%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd expiry_date limit_currency_cd limit_amt limit_text 
        third_party_pledge_flag guarantee_type_cd complementary_pledge_flag 
        credit_decision_id credit_decision_pledge_id pledge_date 
        customer_type_txt mortgagor_type_cd additional_terms_txt 
        source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.pledge;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000154%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd expiry_date limit_currency_cd limit_amt limit_text 
        third_party_pledge_flag guarantee_type_cd complementary_pledge_flag 
        credit_decision_id credit_decision_pledge_id pledge_date 
        customer_type_txt mortgagor_type_cd additional_terms_txt 
        source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete pledge;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd expiry_date limit_currency_cd limit_amt limit_text 
        third_party_pledge_flag guarantee_type_cd complementary_pledge_flag 
        credit_decision_id credit_decision_pledge_id pledge_date 
        customer_type_txt mortgagor_type_cd additional_terms_txt 
        source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id internal_pledge_id pledge_number 
        pledge_type_cd expiry_date limit_currency_cd limit_amt limit_text 
        third_party_pledge_flag guarantee_type_cd complementary_pledge_flag 
        credit_decision_id credit_decision_pledge_id pledge_date 
        customer_type_txt mortgagor_type_cd additional_terms_txt 
        source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001PQ * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mac_dm.INSTRUMENT                     A5M8HTKH.BB0000OT * 
 * Target Table:    shadow_OUTPUT0 - work.instrument      A5M8HTKH.BR000155 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mac_dm.INSTRUMENT); 

%let _INPUT_count = 1; 
%let _INPUT = mac_dm.INSTRUMENT;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.INSTRUMENT%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Instrument dataset);

%let _INPUT0 = mac_dm.INSTRUMENT;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.INSTRUMENT%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Instrument dataset);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.instrument;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000155%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd customer_id_mod name 
        stat_sector_cd booked_balance_amt total_withdrawable_amount 
        payment_plan_cd currency_cd mid_rate opened_date opened_date_mid_rate 
        changed_date close_date overdraft_date credit_ref_interest_cd 
        credit_margin_rate_pct loan_end_date original_loan_amount 
        current_limit_amt expiry_date purpose_of_use_cd 
        principal_payments_per_year_cnt next_principal_payment_date 
        interest_cap_and_floor_type interest_cap_n_floor_start_date 
        interest_cap_n_floor_end_date interest_cap_n_floor_f_rate_pct 
        interest_cap_n_floor_c_rate_pct irb_exposure_class loaded_dt;

%let _OUTPUT0 = work.instrument;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000155%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd customer_id_mod name 
        stat_sector_cd booked_balance_amt total_withdrawable_amount 
        payment_plan_cd currency_cd mid_rate opened_date opened_date_mid_rate 
        changed_date close_date overdraft_date credit_ref_interest_cd 
        credit_margin_rate_pct loan_end_date original_loan_amount 
        current_limit_amt expiry_date purpose_of_use_cd 
        principal_payments_per_year_cnt next_principal_payment_date 
        interest_cap_and_floor_type interest_cap_n_floor_start_date 
        interest_cap_n_floor_end_date interest_cap_n_floor_f_rate_pct 
        interest_cap_n_floor_c_rate_pct irb_exposure_class loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete instrument;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd customer_id_mod name 
        stat_sector_cd booked_balance_amt total_withdrawable_amount 
        payment_plan_cd currency_cd mid_rate opened_date opened_date_mid_rate 
        changed_date close_date overdraft_date credit_ref_interest_cd 
        credit_margin_rate_pct loan_end_date original_loan_amount 
        current_limit_amt expiry_date purpose_of_use_cd 
        principal_payments_per_year_cnt next_principal_payment_date 
        interest_cap_and_floor_type interest_cap_n_floor_start_date 
        interest_cap_n_floor_end_date interest_cap_n_floor_f_rate_pct 
        interest_cap_n_floor_c_rate_pct irb_exposure_class loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id account_number_official 
        original_account_id account_type_cd customer_id_mod name 
        stat_sector_cd booked_balance_amt total_withdrawable_amount 
        payment_plan_cd currency_cd mid_rate opened_date opened_date_mid_rate 
        changed_date close_date overdraft_date credit_ref_interest_cd 
        credit_margin_rate_pct loan_end_date original_loan_amount 
        current_limit_amt expiry_date purpose_of_use_cd 
        principal_payments_per_year_cnt next_principal_payment_date 
        interest_cap_and_floor_type interest_cap_n_floor_start_date 
        interest_cap_n_floor_end_date interest_cap_n_floor_f_rate_pct 
        interest_cap_n_floor_c_rate_pct irb_exposure_class loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5M8HTKH.BU0001PR * 
 * Transform:       Join                                                    * 
 * Description:     Pledge dataSelect distinct                              * 
 *                                                                          * 
 * Source Tables:   shadow_OUTPUT0 - work.collateral      A5M8HTKH.BR000152 * 
 *                  shadow_OUTPUT0 -                      A5M8HTKH.BR000153 * 
 *                   work.account_collateral_link                           * 
 *                  shadow_OUTPUT0 - work.instrument      A5M8HTKH.BR000155 * 
 *                  shadow_OUTPUT0 - work.pledge          A5M8HTKH.BR000154 * 
 * Target Table:    Join - work.pledge_data               A5M8HTKH.BR000156 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PR);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete pledge_data;
quit;

proc sql;
   create view work.pledge_data as
   select distinct
      collateral.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      collateral.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      collateral.internal_collateral_id length = 10   
         label = 'Collateral identification number',
      cat(collateral.bank_id, collateral.collateral_number) as protection_identifier length = 60   
         label = 'Protection identifier',
      account_collateral_link.account_id length = 20   
         label = 'Credit account number',
      pledge.pledge_type_cd length = 20   
         label = 'Pledge type (GENERAL_PLEDGE, GENERAL_GUARANTEE, PLEDGE, GUARANTEE)',
      instrument.account_number_official length = 20   
         label = 'Account number official, In Finland this field is same as ACCNBR, in Sweden it contains the official Swedish account number',
      instrument.original_account_id length = 14   
         label = 'Credit account id before it was on collection. 0 is allowed'
   from
      work.collateral as collateral left join 
      work.account_collateral_link as account_collateral_link
         on
         (
            collateral.information_date = account_collateral_link.information_date
            and collateral.bank_id = account_collateral_link.bank_id
            and collateral.internal_collateral_id = account_collateral_link.internal_collateral_id
         ) left join 
      work.instrument as instrument
         on
         (
            account_collateral_link.information_date = instrument.information_date
            and account_collateral_link.bank_id = instrument.bank_id
            and account_collateral_link.account_id = instrument.account_id
         ) left join 
      work.pledge as pledge
         on
         (
            account_collateral_link.information_date = pledge.information_date
            and account_collateral_link.bank_id = pledge.bank_id
            and account_collateral_link.internal_pledge_id = pledge.internal_pledge_id
         )
   where
      account_collateral_link.account_id NOT IS MISSING 
      and instrument.account_id NOT IS MISSING 
      and (collateral.orig_collateral_loan_value_amt > 1
      or collateral.collateral_loan_value_amt > 1)
      and (pledge.expiry_date IS MISSING 
      or pledge.expiry_date >= collateral.information_date)
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001PS * 
 * Transform:       Extract                                                 * 
 * Description:     count(pledge_type_cd)Group By                           * 
 *                                                                          * 
 * Source Table:    Join - work.pledge_data               A5M8HTKH.BR000156 * 
 * Target Table:    Extract - work.pledge_type_cd_count   A5M8HTKH.BR000157 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PS);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.pledge_data); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete pledge_type_cd_count;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.pledge_type_cd_count as
      select
         information_date,
         bank_id,
         internal_collateral_id,
         protection_identifier,
         account_id,
         pledge_type_cd,
         account_number_official,
         original_account_id,
         (count(pledge_type_cd)) as pledge_type_cd_count length = 8
            label = 'Count of pledge_type_cd'
   from &SYSLAST
   group by
      bank_id,
      internal_collateral_id,
      account_id
   ;
quit;

%let SYSLAST = work.pledge_type_cd_count;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001PT * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.COLLATERAL_DISTRIBUTION         A5M8HTKH.BB00004R * 
 * Target Table:    shadow_OUTPUT0 -                      A5M8HTKH.BR000158 * 
 *                   work.collateral_distribution                           * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PT);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.COLLATERAL_DISTRIBUTION); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.COLLATERAL_DISTRIBUTION;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.COLLATERAL_DISTRIBUTION%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.COLLATERAL_DISTRIBUTION;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.COLLATERAL_DISTRIBUTION%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.collateral_distribution;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000158%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id internal_collateral_id 
        market_value third_prio_value object_group_id source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.collateral_distribution;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000158%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id internal_collateral_id 
        market_value third_prio_value object_group_id source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete collateral_distribution;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id internal_collateral_id 
        market_value third_prio_value object_group_id source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id internal_collateral_id 
        market_value third_prio_value object_group_id source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU0001PU * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.EXCHANGE_RATES                  A5M8HTKH.BB000073 * 
 * Target Table:    shadow_OUTPUT0 - work.exchange_rates  A5M8HTKH.BR000159 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PU);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.EXCHANGE_RATES); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.EXCHANGE_RATES;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.EXCHANGE_RATES%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.EXCHANGE_RATES;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.EXCHANGE_RATES%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.exchange_rates;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000159%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.exchange_rates;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR000159%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete exchange_rates;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5M8HTKH.BU0001PV * 
 * Transform:       Join                                                    * 
 * Description:     Select distinct                                         * 
 *                                                                          * 
 * Source Tables:   shadow_OUTPUT0 - work.collateral      A5M8HTKH.BR000152 * 
 *                  shadow_OUTPUT0 -                      A5M8HTKH.BR000153 * 
 *                   work.account_collateral_link                           * 
 *                  shadow_OUTPUT0 - work.instrument      A5M8HTKH.BR000155 * 
 *                  shadow_OUTPUT0 -                      A5M8HTKH.BR000158 * 
 *                   work.collateral_distribution                           * 
 *                  shadow_OUTPUT0 - work.exchange_rates  A5M8HTKH.BR000159 * 
 *                  Extract - work.pledge_type_cd_count   A5M8HTKH.BR000157 * 
 * Target Table:    Join - work.W4NX4LNA                  A5M8HTKH.BR00015A * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PV);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W4NX4LNA;
quit;

proc sql;
   create view work.W4NX4LNA as
   select distinct
      collateral.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      collateral.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      collateral.internal_collateral_id length = 10   
         label = 'Collateral identification number',
      cat(collateral.bank_id, collateral.collateral_number) as protection_identifier length = 60   
         label = 'Protection identifier',
      collateral.currency_cd length = 3   
         label = 'The valuation currency',
      account_collateral_link.account_id length = 20   
         label = 'Credit account number',
      instrument.account_number_official length = 20   
         label = 'Account number official, In Finland this field is same as ACCNBR, in Sweden it contains the official Swedish account number',
      instrument.original_account_id length = 14   
         label = 'Credit account id before it was on collection. 0 is allowed',
      collateral_distribution.market_value length = 8   
         format = 15.2
         label = 'Market value of the collateral',
      collateral_distribution.third_prio_value length = 8   
         format = 15.2
         label = 'Third party prioritized loans',
      exchange_rates.mid_rate length = 8   
         format = 10.6
         label = 'Mean value of one base currency unit in currency (värdet på basvalutan i valutan)',
      case when pledge_type_cd_count.pledge_type_cd_count = 1 then pledge_type_cd_count.pledge_type_cd end as pledge_type_cd length = 20   
         label = 'Pledge type (GENERAL_PLEDGE, GENERAL_GUARANTEE, PLEDGE, GUARANTEE)'
   from
      work.collateral as collateral left join 
      work.account_collateral_link as account_collateral_link
         on
         (
            collateral.information_date = account_collateral_link.information_date
            and collateral.bank_id = account_collateral_link.bank_id
            and collateral.internal_collateral_id = account_collateral_link.internal_collateral_id
         ) left join 
      work.instrument as instrument
         on
         (
            account_collateral_link.information_date = instrument.information_date
            and account_collateral_link.bank_id = instrument.bank_id
            and account_collateral_link.account_id = instrument.account_id
         ) left join 
      work.collateral_distribution as collateral_distribution
         on
         (
            account_collateral_link.information_date = collateral_distribution.information_date
            and account_collateral_link.bank_id = collateral_distribution.bank_id
            and account_collateral_link.account_id = collateral_distribution.account_id
            and account_collateral_link.internal_collateral_id = collateral_distribution.internal_collateral_id
         ) left join 
      work.exchange_rates as exchange_rates
         on
         (
            collateral.information_date = exchange_rates.information_date
            and collateral.currency_cd = exchange_rates.currency_cd
         ) left join 
      work.pledge_type_cd_count as pledge_type_cd_count
         on
         (
            account_collateral_link.information_date = pledge_type_cd_count.information_date
            and account_collateral_link.bank_id = pledge_type_cd_count.bank_id
            and account_collateral_link.account_id = pledge_type_cd_count.account_id
            and account_collateral_link.internal_collateral_id = pledge_type_cd_count.internal_collateral_id
         )
   where
      account_collateral_link.account_id NOT IS MISSING 
      and instrument.account_id NOT IS MISSING 
      and (collateral.orig_collateral_loan_value_amt > 1
      or collateral.collateral_loan_value_amt > 1)
      and exchange_rates.bank_id = 'A'
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001PW * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W4NX4LNA                  A5M8HTKH.BR00015A * 
 * Target Table:    Extract - work.W4M0XFMH               A5M8HTKH.BR00015B * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PW);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4NX4LNA); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W4M0XFMH;
quit;

data _null_;
   put "NOTE: The following column(s) do not have a column mapping, so the"
        " value(s) will be set to missing: reporting_agent_identifier,"
        " observed_agent_identifier, contract_identifier,   "
        " instrument_identifier, protection_allocated_value,   "
        " third_party_claims_vs_protect, general_collateral";
run;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W4M0XFMH as
      select
         information_date,
         "" as reporting_agent_identifier length = 60
            label = 'Reporting agent identifier',
         "" as observed_agent_identifier length = 60
            label = 'Observed agent identifier',
         "" as contract_identifier length = 60
            label = 'Contract identifier',
         "" as instrument_identifier length = 60
            label = 'Instrument identifier',
         protection_identifier,
         . as protection_allocated_value length = 8
            format = 15.2
            label = 'Protection allocated value',
         . as third_party_claims_vs_protect length = 8
            format = 15.2
            label = 'Third party priority claims against the protection',
         "" as general_collateral length = 2
            label = 'General collateral',
         bank_id,
         account_id   
            label = 'Account Number',
         account_number_official,
         original_account_id,
         internal_collateral_id,
         currency_cd   
            label = 'Currency code',
         mid_rate   
            label = 'Mean value of one base currency nit in currency',
         market_value,
         third_prio_value,
         pledge_type_cd   
            label = 'Pledge type (GENERAL PLEDGE, GENERAL_GUARANTEE, PLEDGE, GUARANTEE)',
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W4M0XFMH;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0001PX * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W4M0XFMH               A5M8HTKH.BR00015B * 
 * Target Table:    mac_dm.INSTRUMENT_PROTECTION          A5M8HTKH.BB0000OW * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001PX);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4M0XFMH); 

%let _INPUT_count = 1; 
%let _INPUT = work.W4M0XFMH;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR00015B%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W4M0XFMH;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR00015B%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mac_dm.INSTRUMENT_PROTECTION;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.INSTRUMENT_PROTECTION%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Instrument Protection dataset);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date reporting_agent_identifier observed_agent_identifier 
        contract_identifier instrument_identifier protection_identifier 
        protection_allocated_value third_party_claims_vs_protect 
        general_collateral bank_id account_id account_number_official 
        original_account_id internal_collateral_id currency_cd mid_rate 
        market_value third_prio_value pledge_type_cd loaded_dt;

%let _OUTPUT0 = mac_dm.INSTRUMENT_PROTECTION;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _OUTPUT0_path = %nrquote(/dw_solution/mac/data/dm/mac_dm.INSTRUMENT_PROTECTION%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Instrument Protection dataset);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date reporting_agent_identifier observed_agent_identifier 
        contract_identifier instrument_identifier protection_identifier 
        protection_allocated_value third_party_claims_vs_protect 
        general_collateral bank_id account_id account_number_official 
        original_account_id internal_collateral_id currency_cd mid_rate 
        market_value third_prio_value pledge_type_cd loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date reporting_agent_identifier observed_agent_identifier 
        contract_identifier instrument_identifier protection_identifier 
        protection_allocated_value third_party_claims_vs_protect 
        general_collateral bank_id account_id account_number_official 
        original_account_id internal_collateral_id currency_cd mid_rate 
        market_value third_prio_value pledge_type_cd loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date reporting_agent_identifier observed_agent_identifier 
        contract_identifier instrument_identifier protection_identifier 
        protection_allocated_value third_party_claims_vs_protect 
        general_collateral bank_id account_id account_number_official 
        original_account_id internal_collateral_id currency_cd mid_rate 
        market_value third_prio_value pledge_type_cd loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mac_dm nolist; 
   modify INSTRUMENT_PROTECTION(ALTER=&alterpass. ); 
      index create primary_index = (information_date bank_id account_id protection_identifier)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

