/**************************************************************************** 
 * Job:             mco_dm.le_detail                      A5M8HTKH.BO0000FP * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: aablstgsas21                                            * 
 * Port:            8561                                                    * 
 * Location:        /dw_solution/mco/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Tables:   dw_dw.ACCOUNT_DAILY                   A5M8HTKH.BB00002B * 
 *                  mco_dm.TREASURY_POSITION              A5M8HTKH.BB0000XT * 
 *                  mco_dm.DET_LE_INSTITUTION_GROUPING    A5M8HTKH.BB0000WH * 
 *                  mco_dm.DET_CURRENCY_EXCHANGE_RATES    A5M8HTKH.BB0000VT * 
 *                  dw_dw.CUSTOMER                        A5M8HTKH.BB000066 * 
 *                  mco_dm.BASEL_IRB_ALL                  A5M8HTKH.BB0000UP * 
 *                  dw_dw.ACCOUNT                         A5M8HTKH.BB000026 * 
 *                  mco_dm.DET_BASEL_IRB_DER              A5M8HTKH.BB0000VD * 
 *                  mco_dm.DET_BASEL_IRB_LC               A5M8HTKH.BB0000VH * 
 *                  mco_dm.DET_LE_MANUAL_ENTRIES          A5M8HTKH.BB0000WL * 
 * Target Table:    mco_dm.LE_DETAIL                      A5M8HTKH.BB0000XL * 
 *                                                                          * 
 * Generated on:    den 2 oktober 2023 kl 10:22 CEST                        * 
 * Generated by:    miaomzhu                                                * 
 * Version:         SAS Data Integration Studio 4.905                       * 
 ****************************************************************************/ 

/*==========================================================================* 
 * Step:            Extract bonds                         A5M8HTKH.BU0001A6 * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.TREASURY_POSITION       		  A5M8HTKH.BR0000TA * 
 * Target Table:    Extract - work.W4M0U8B0               A5M8HTKH.BR0000TB * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001A6);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4Z0YTCS); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W4M0U8B0;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W4M0U8B0 as
      select
         information_date,
         deal_id,
         transaction_type_cd,
         book_value_eur_amt,
         issuer_cd,
         instrument_exposure_class_cd,
         (case when transaction_type_cd in ('SE','MM') and instrument_exposure_class_cd in ('6','12') then maturity_date
            else .
            end) as maturity_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Maturity date',
         (case when transaction_type_cd in ('SE','MM') and instrument_exposure_class_cd in ('6','12') then book_value_eur_amt
            else 0
            end) as book_value_eur_amt_orig length = 8
            format = 15.2
            label = 'Book value EUR: (Book_Value*Spot_Factor)'
   from mco_dm.TREASURY_POSITION
      where transaction_type_cd in('MM','SE') 
           and issuer_cd ne ' ' 
           and information_date=&active_date
   ;
quit;

%let SYSLAST = work.W4M0U8B0;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract bonds **/

/*==========================================================================* 
 * Step:            Extract bankaccounts                  A5M8HTKH.BU0001A7 * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.TREASURY_POSITION        A5M8HTKH.BR0000TA * 
 * Target Table:    Extract -                             A5M8HTKH.BR0000TC * 
 *                   work.extract_treasury_bankaccounts                     * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001A7);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4Z0YTCS); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete extract_treasury_bankaccounts;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.extract_treasury_bankaccounts as
      select
         information_date,
         deal_id,
         transaction_type_cd,
         book_value_eur_amt,
         instrument_exposure_class_cd,
         counterparty_name,
         bank_balance_amt
   from mco_dm.TREASURY_POSITION
      where transaction_type_cd="BA" and entity_id = "Treasury" 
          and not (counterparty_name in("ÅLANDSBANKEN SVERIGE AB","ÅAB INTERNAL"))
          and information_date=&active_date
   ;
quit;

%let SYSLAST = work.extract_treasury_bankaccounts;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract bankaccounts **/

/*==========================================================================* 
 * Step:            LE_treasury_bonds                     A5M8HTKH.BU0001A9 * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Extract - work.W4M0U8B0               A5M8HTKH.BR0000TB * 
 *                  mco_dm.DET_LE_INSTITUTION_GROUPING                              * 
 * Target Table:    Join - work.LE_treasury_bonds         A5M8HTKH.BR0000TE * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001A9);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete LE_treasury_bonds;
quit;

proc sql;
   create view work.LE_treasury_bonds as
   select
      W4M0U8B0.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Query position date',
      'Bonds' as product_name length = 40   
         format = $40.,
      shadow_inst_grouping.group_lei_id as code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      shadow_inst_grouping.client_lei_id as code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      max(W4M0U8B0.book_value_eur_amt,0) as debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      -W4M0U8B0.book_value_eur_amt
      *(W4M0U8B0.instrument_exposure_class_cd in('1','2','3','4','5','9'))     
      -(0.9*W4M0U8B0.book_value_eur_amt)*(W4M0U8B0.instrument_exposure_class_cd='12') as _amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      W4M0U8B0.issuer_cd as individual_name length = 90,
      W4M0U8B0.maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      W4M0U8B0.book_value_eur_amt_orig length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)'
   from
      work.W4M0U8B0 as W4M0U8B0, 
      mco_dm.DET_LE_INSTITUTION_GROUPING as shadow_inst_grouping
   where
      W4M0U8B0.issuer_cd = shadow_inst_grouping.client_name
      and not (calculated debt_instruments = 0
      and calculated _amounts_exempted = 0)
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end LE_treasury_bonds **/

/*==========================================================================* 
 * Step:            LE_treasury_bankaccounts              A5M8HTKH.BU0001AA * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Extract -                             A5M8HTKH.BR0000TC * 
 *                   work.extract_treasury_bankaccounts                     * 
 *                  mco_dm.DET_LE_INSTITUTION_GROUPING                              * 
 * Target Table:    Join - work.le_treasury_bankaccounts  A5M8HTKH.BR0000TF * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AA);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete le_treasury_bankaccounts;
quit;

proc sql;
   create view work.le_treasury_bankaccounts as
   select
      'Treasury_bankaccounts' as product_name length = 40   
         format = $40.,
      shadow_inst_grouping.group_lei_id as code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      shadow_inst_grouping.client_lei_id as code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      extract_treasury_bankaccounts.book_value_eur_amt as debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      extract_treasury_bankaccounts.counterparty_name as individual_name length = 90   
         label = 'counterparty name (key)',
      extract_treasury_bankaccounts.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      extract_treasury_bankaccounts.book_value_eur_amt length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)'
   from
      work.extract_treasury_bankaccounts as extract_treasury_bankaccounts, 
      mco_dm.DET_LE_INSTITUTION_GROUPING as shadow_inst_grouping
   where
      extract_treasury_bankaccounts.counterparty_name = shadow_inst_grouping.client_name
      and extract_treasury_bankaccounts.book_value_eur_amt <> 0
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

/** Step end LE_treasury_bankaccounts **/

/*==========================================================================* 
 * Step:            Extract name, ssn_id, stat_sector_cd  A5M8HTKH.BU0001AC * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    dw_dw.CUSTOMER        A5M8HTKH.BR0000TG * 
 * Target Table:    extract_customer -                    A5M8HTKH.BR0000TH * 
 *                   work.extract_customer                                  * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AC);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W596GHSE); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete extract_customer;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.extract_customer as
      select
         information_date   
            label = 'Query position date',
         bank_id,
         customer_id,
         ssn_id,
         (substr(name,1,90)) as name length = 90
            label = 'Customer Name (All customers)',
         stat_sector_cd
   from dw_dw.CUSTOMER
      where substr(stat_sector_cd,1,3) in('121','122','123','321','322','323')
   ;
quit;

%let SYSLAST = work.extract_customer;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract name, ssn_id, stat_sector_cd **/

/*==========================================================================* 
 * Step:            Extract account_id,                   A5M8HTKH.BU0001AE * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT				          A5M8HTKH.BR0000TI * 
 * Target Table:    extract_account -                     A5M8HTKH.BR0000TJ * 
 *                   work.extract_account                                   * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AE);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W59UJJNJ); 

%let ETLS_SYSLAST = &SYSLAST;
/*---- Start of Pre-Process Code  ----*/ 


/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

%let SYSLAST = &ETLS_SYSLAST;

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete extract_account;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.extract_account as
      select
         (round(information_date,1)) as information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date of the record',
         account_id   
            label = 'Account Number',
         currency_cd,
         owner_id,
         owner_ssn_id
   from dw_dw.ACCOUNT
      where not (Owner_ssn_id in('950185-830T','0145019-3','516406-0781'))
          and account_type_cd in('260','280')
   ;
quit;

%let SYSLAST = work.extract_account;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract account_id, **/

/*==========================================================================* 
 * Step:            Extract account_id,                   A5M8HTKH.BU0001AF * 
 *                   booked_balance_amt                                     * 
 * Transform:       Extract                                                 * 
 * Description:     1st date since &active_date selected in precode         * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT_DAILY                   A5M8HTKH.BB00002B * 
 * Target Table:    extract_account_daily -               A5M8HTKH.BR0000TK * 
 *                   work.extract_account_daily                             * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AF);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT_DAILY); 

%let ETLS_SYSLAST = &SYSLAST;
/*---- Start of Pre-Process Code  ----*/ 

proc sql noprint ;
*select distinct max(information_date) into :_accd_d from dw_dw.account_daily ; 
select distinct min(information_date) into :_accd_d_A from dw_dw.account_daily
where information_date >= &active_date. and bank_id='A'; 
select distinct min(information_date) into :_accd_d_B from dw_dw.account_daily
where information_date >= &active_date. and bank_id='B'; 
quit ;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

%let SYSLAST = &ETLS_SYSLAST;

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete extract_account_daily;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.extract_account_daily as
      select
         information_date   
            informat = DDMMYY10.
            label = 'Query position date',
         account_id,
         booked_balance_amt   
            label = 'Booked Balance,Amount',
         bank_id
   from &SYSLAST
      (&altercommand.)
      where ((information_date=&_accd_d_a and bank_id='A') or (information_date=&_accd_d_b and bank_id='B'))
          and booked_balance_amt<0
   ;
quit;

%let SYSLAST = work.extract_account_daily;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

/** Step end Extract account_id, booked_balance_amt **/

/*==========================================================================* 
 * Step:            LE_nostro_accounts                    A5M8HTKH.BU0001AH * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   extract_customer -                    A5M8HTKH.BR0000TH * 
 *                   work.extract_customer                                  * 
 *                  mco_dm.DET_LE_INSTITUTION_GROUPING                              * 
 *                  extract_account -                     A5M8HTKH.BR0000TJ * 
 *                   work.extract_account                                   * 
 *                  extract_account_daily -               A5M8HTKH.BR0000TK * 
 *                   work.extract_account_daily                             * 
 *                  mco_dm.DET_CURRENCY_EXCHANGE_RATES                                   * 
 * Target Table:    Join - work.LE_nostro_accounts        A5M8HTKH.BR0000TM * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AH);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete LE_nostro_accounts;
quit;

proc sql;
   create view work.LE_nostro_accounts as
   select
      'Nostro_accounts' as product_name length = 40,
      extract_customer.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Query position date',
      extract_customer.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      extract_customer.customer_id length = 9   
         label = 'CBS Customer ID',
      extract_customer.ssn_id length = 20   
         label = 'Social security / organisation number',
      extract_customer.name as individual_name length = 90   
         label = 'Customer Name (All customers)',
      extract_customer.stat_sector_cd length = 6   
         label = 'Sektorkod. Obs : 6 siffror.',
      shadow_inst_grouping.client_lei_id as code_client length = 50,
      shadow_inst_grouping.group_lei_id as code length = 50,
      extract_account.owner_ssn_id length = 20   
         label = 'Social Sec.number / Org.number. Account owner',
      ABS(extract_account_daily.booked_balance_amt/shadow_currency.exchange_rate) as debt_instruments length = 8   
         format = 15.2,
      (extract_account_daily.booked_balance_amt/shadow_currency.exchange_rate)
      *((substr(extract_customer.stat_sector_cd,1,3) in('121','321'))) as _amounts_exempted length = 8   
         format = 15.2
   from
      work.extract_customer as extract_customer left join 
      mco_dm.DET_LE_INSTITUTION_GROUPING as shadow_inst_grouping
         on
         (
            extract_customer.name = shadow_inst_grouping.client_name
         ), 
      work.extract_account as extract_account left join 
      mco_dm.DET_CURRENCY_EXCHANGE_RATES as shadow_currency
         on
         (
            extract_account.currency_cd = shadow_currency.currency_cd
         ), 
      work.extract_account_daily as extract_account_daily
   where
      extract_account.account_id = extract_account_daily.account_id
      and extract_customer.ssn_id = extract_account.owner_ssn_id
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end LE_nostro_accounts **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU0001AI * 
 * Transform:       Extract                                                 * 
 * Description:     debt_instruments (where sector codes 122X ><123X and    * 
 *                   322><323X) added                                       * 
 *                                                                          * 
 * Source Table:    Join - work.LE_nostro_accounts        A5M8HTKH.BR0000TM * 
 * Target Table:    Extract -                             A5M8HTKH.BR0000TN * 
 *                   work.Extract_Nostro_accounts                           * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AI);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.LE_nostro_accounts); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete Extract_Nostro_accounts;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.Extract_Nostro_accounts as
      select
         product_name,
         information_date,
         bank_id,
         customer_id,
         ssn_id,
         individual_name,
         stat_sector_cd,
         code_client,
         code,
         owner_ssn_id,
         debt_instruments,
         _amounts_exempted,
         (case when substr(stat_sector_cd,1,3) in ('122','123','322','323') then debt_instruments 
            else 0
            end) as debt_instruments_1 length = 8
            format = 15.2
   from LE_nostro_accounts
   ;
quit;

%let SYSLAST = work.Extract_Nostro_accounts;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

/** Step end Extract **/

/*==========================================================================* 
 * Step:            LE_retail_and_corporate               A5M8HTKH.BU0001AK * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.BASEL_IRB_ALL                              * 
 * Target Table:    LE_retail_and_corporate -             A5M8HTKH.BR0000TP * 
 *                   work.le_retail_and_corporate                           * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AK);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.shadow_basel_irb_all); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete le_retail_and_corporate;
quit;

data _null_;
   put "NOTE: The following column(s) do not have a column mapping, so the"
        " value(s) will be set to missing: individual_name";
run;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.le_retail_and_corporate as
      select
         ('Retail_and_Corporate customers') as product_name length = 40
            format = $40.,
         entity_ssn_id as code length = 50   
            format = $50.,
         customer_ssn_id as code_client length = 50   
            format = $50.,
         (b_exposure_amount
            *((pd_class_number=11) or (b_exposure_class in('10','10B')))) as defaulted length = 8
            format = 15.2,
         (b_exposure_amount*(b_balance_sheet=1)) as debt_instruments length = 8
            format = 15.2
            label = 'Book value EUR: (Book_Value*Spot_Factor)',
         (b_exposure_amount*(b_balance_sheet=0)*(1-(counterparty_risk_type in("G","F") ))) as loan_commitments length = 8
            format = 15.2
            label = 'Off balance sheet S-method exposure amount',
         (b_exposure_amount*(counterparty_risk_type in("G","F"))) as financial_guarantees length = 8
            format = 15.2,
         (b_exposure_amount*(counterparty_risk_type="XX")) as other_commitments length = 8
            format = 15.2,
         impairment_losses_amount as _value_adjust_and_provis   
            label = 'impairment_losses_amount (<0)',
         (-b_exposure_amount*(b_exposure_class in('01','02','03','04','05','06'))) as crm__financial_guarantees length = 8
            format = 15.2,
         (case 
             when (b_exposure_class="IRB" and b_row_number=1) then -crm_amount
             when b_exposure_class="CRM" then -b_exposure_amount
             else 0
            end) as _Funded_credit_prot_not_subst length = 8
            format = 15.2,
         (case 
             when (b_exposure_class="IRB" and b_row_number=1) then -housing_collateral_amount*0.5 
             when b_exposure_class="09B" then -b_exposure_amount*0.5
             else 0
            end) as _real_estate length = 8
            format = 15.2,
         "" as individual_name length = 90
            label = 'counterparty/issuer name (key)',
         information_date   
            label = 'Query position date'
   from mco_dm.BASEL_IRB_ALL
      where customer_ssn_id ne ' '
   ;
quit;

%let SYSLAST = work.le_retail_and_corporate;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

/** Step end LE_retail_and_corporate **/

/*==========================================================================* 
 * Step:            LE_derivatives                        A5M8HTKH.BU0001AM * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   mco_dm.DET_BASEL_IRB_DER                            	* 
 *                  mco_dm.DET_LE_INSTITUTION_GROUPING                      * 
 * Target Table:    LE_derivatives - work.le_derivatives  A5M8HTKH.BR0000TR * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete le_derivatives;
quit;

data _null_;
   put "NOTE: The following column(s) do not have a column mapping, so the"
        " value(s) will be set to missing: debt_instruments";
run;

proc sql;
   create view work.le_derivatives as
   select
      'Derivatives' as product_name length = 40   
         format = $40.,
      shadow_inst_grouping.group_lei_id as code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      shadow_inst_grouping.client_lei_id as code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      . as debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      shadow_basel_irb_der.exposure_at_default_amount as derivatives length = 8   
         format = 15.2,
      -shadow_basel_irb_der.collateral_received_amount as _Funded_credit_prot_not_subst length = 8   
         format = 15.2,
      substr(shadow_basel_irb_der.counterparty_name,1,90) as individual_name length = 90   
         label = 'counterparty/issuer name (key)',
      shadow_inst_grouping.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      case when shadow_basel_irb_der.sm_exposure_class in ('06','12') then shadow_basel_irb_der.maturity_date 
      else . 
      end as maturity_date length = 4   
         format = findfdd10.
         label = 'Maturity date',
      case when shadow_basel_irb_der.sm_exposure_class in ('06','12') then shadow_basel_irb_der.exposure_at_default_amount 
      else 0  
      end as exposure_at_default_amount length = 8   
         format = 15.2
   from
      work.shadow_basel_irb_der as shadow_basel_irb_der left join 
      work.shadow_inst_grouping as shadow_inst_grouping
         on
         (
            shadow_basel_irb_der.counterparty_name = shadow_inst_grouping.client_name
         )
   where
      not (shadow_basel_irb_der.exposure_at_default_amount = 0
      and shadow_basel_irb_der.collateral_received_amount = 0)
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 

/** Step end LE_derivatives **/

/*==========================================================================* 
 * Step:            LE_loan_commitments                   A5M8HTKH.BU0001AO * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.DET_BASEL_IRB_LC                               * 
 * Target Table:    le_loan_commitments -                 A5M8HTKH.BR0000TT * 
 *                   work.le_loan_commitments                               * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.shadow_basel_irb_lc); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete le_loan_commitments;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.le_loan_commitments as
      select
         ('Loan_commitments') as product_name length = 40
            format = $40.,
         account_number as code length = 50   
            format = $50.
            label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
         account_number as code_client length = 50   
            format = $50.
            label = 'Social security / organisation number',
         sm_amount_obs as loan_commitments   
            label = 'Off balance sheet S-method exposure amount',
         information_date   
            label = 'Query position date'
   from mco_dm.DET_BASEL_IRB_LC
      where loan_commitments ne 0
   ;
quit;

%let SYSLAST = work.le_loan_commitments;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end LE_loan_commitments **/

/*==========================================================================* 
 * Step:            LE_manual_entries                     A5M8HTKH.BU0001AQ * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.DET_LE_MANUAL_ENTRIES        A5M8HTKH.BR0000TU * 
 * Target Table:    LE_manual_entries -                   A5M8HTKH.BR0000TV * 
 *                   work.LE_manual_entries                                 * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W5PVP7LQ); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete LE_manual_entries;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.LE_manual_entries as
      select
         information_date,
         entry_id,
         product_name,
         code,
         code_client,
         defaulted,
         debt_instruments,
         equity_instruments,
         derivatives,
         loan_commitments,
         financial_guarantees,
         other_commitments,
         _value_adjust_and_provis,
         _financial_guarantees,
         crm__financial_guarantees,
         _funded_credit_prot_not_subst,
         _real_estate,
         _amounts_exempted,
         (case
            when code ='549300DTUYXVMJXZNY75' then 0
            when substr(code,13,1) ne '' then debt_instruments
            else 0
            end) as bucket_value_amount length = 8
            format = 15.2
   from mco_dm.DET_LE_MANUAL_ENTRIES
   ;
quit;

%let SYSLAST = work.LE_manual_entries;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end LE_manual_entries **/

/*==========================================================================* 
 * Step:            Union                                 A5M8HTKH.BU0001AR * 
 * Transform:       Set Operators                                           * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Join - work.LE_treasury_bonds         A5M8HTKH.BR0000TE * 
 *                  Join - work.le_treasury_bankaccounts  A5M8HTKH.BR0000TF * 
 *                  Extract -                             A5M8HTKH.BR0000TN * 
 *                   work.Extract_Nostro_accounts                           * 
 *                  LE_retail_and_corporate -             A5M8HTKH.BR0000TP * 
 *                   work.le_retail_and_corporate                           * 
 *                  LE_derivatives - work.le_derivatives  A5M8HTKH.BR0000TR * 
 *                  le_loan_commitments -                 A5M8HTKH.BR0000TT * 
 *                   work.le_loan_commitments                               * 
 *                  LE_manual_entries -                   A5M8HTKH.BR0000TV * 
 *                   work.LE_manual_entries                                 * 
 * Target Table:    Set Operators - work.W4VXZXZF         A5M8HTKH.BR0000TW * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AR);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W4VXZXZF;
quit;

proc sql;
   create view work.W4VXZXZF as
   /* Returns all unique rows from the two query results.  */ 
   select
      LE_treasury_bonds.product_name length = 40   
         format = $40.,
      LE_treasury_bonds.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      LE_treasury_bonds.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      . as defaulted length = 8   
         format = 15.2,
      LE_treasury_bonds.debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      . as equity_instruments length = 8   
         format = 15.2,
      . as derivatives length = 8   
         format = 15.2,
      . as loan_commitments length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      . as financial_guarantees length = 8   
         format = 15.2,
      . as other_commitments length = 8   
         format = 15.2,
      . as _value_adjust_and_provis length = 8   
         format = 15.2,
      . as _financial_guarantees length = 8   
         format = 15.2,
      . as crm__financial_guarantees length = 8   
         format = 15.2,
      . as _Funded_credit_prot_not_subst length = 8   
         format = 15.2,
      . as _real_estate length = 8   
         format = 15.2,
      LE_treasury_bonds._amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      LE_treasury_bonds.individual_name length = 90   
         label = 'counterparty name (key)',
      LE_treasury_bonds.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      "" as sector_code length = 6   
         label = 'Sector code',
      LE_treasury_bonds.maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      LE_treasury_bonds.book_value_eur_amt_orig as bucket_value_amount length = 8   
         format = 15.2
         label = 'Bucket value amount'
   from
      work.LE_treasury_bonds
   union all  
   select
      le_treasury_bankaccounts.product_name length = 40   
         format = $40.,
      le_treasury_bankaccounts.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      le_treasury_bankaccounts.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      . as defaulted length = 8   
         format = 15.2,
      le_treasury_bankaccounts.debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      . as equity_instruments length = 8   
         format = 15.2,
      . as derivatives length = 8   
         format = 15.2,
      . as loan_commitments length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      . as financial_guarantees length = 8   
         format = 15.2,
      . as other_commitments length = 8   
         format = 15.2,
      . as _value_adjust_and_provis length = 8   
         format = 15.2,
      . as _financial_guarantees length = 8   
         format = 15.2,
      . as crm__financial_guarantees length = 8   
         format = 15.2,
      . as _Funded_credit_prot_not_subst length = 8   
         format = 15.2,
      . as _real_estate length = 8   
         format = 15.2,
      0 as _Amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      le_treasury_bankaccounts.individual_name length = 90   
         label = 'counterparty name (key)',
      le_treasury_bankaccounts.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      "" as sector_code length = 6   
         label = 'Sector code',
      . as maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      le_treasury_bankaccounts.book_value_eur_amt as bucket_value_amount length = 8   
         format = 15.2
         label = 'Bucket value amount'
   from
      work.le_treasury_bankaccounts
   /* Returns all unique rows from the two query results.  */ 
   union all  
   select
      Extract_Nostro_accounts.product_name length = 40   
         format = $40.,
      Extract_Nostro_accounts.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      Extract_Nostro_accounts.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      . as defaulted length = 8   
         format = 15.2,
      Extract_Nostro_accounts.debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      . as equity_instruments length = 8   
         format = 15.2,
      . as derivatives length = 8   
         format = 15.2,
      . as loan_commitments length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      . as financial_guarantees length = 8   
         format = 15.2,
      . as other_commitments length = 8   
         format = 15.2,
      . as _value_adjust_and_provis length = 8   
         format = 15.2,
      . as _financial_guarantees length = 8   
         format = 15.2,
      . as crm__financial_guarantees length = 8   
         format = 15.2,
      . as _Funded_credit_prot_not_subst length = 8   
         format = 15.2,
      . as _real_estate length = 8   
         format = 15.2,
      Extract_Nostro_accounts._amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      Extract_Nostro_accounts.individual_name length = 90   
         label = 'counterparty name (key)',
      Extract_Nostro_accounts.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      Extract_Nostro_accounts.stat_sector_cd as sector_code length = 6   
         label = 'Sector code',
      . as maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      Extract_Nostro_accounts.debt_instruments_1 as bucket_value_amount length = 8   
         format = 15.2
         label = 'Bucket value amount'
   from
      work.Extract_Nostro_accounts
   /* Returns all unique rows from the two query results.  */ 
   union all  
   select
      le_retail_and_corporate.product_name length = 40   
         format = $40.,
      le_retail_and_corporate.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      le_retail_and_corporate.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      le_retail_and_corporate.defaulted length = 8   
         format = 15.2,
      le_retail_and_corporate.debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      . as equity_instruments length = 8   
         format = 15.2,
      . as derivatives length = 8   
         format = 15.2,
      le_retail_and_corporate.loan_commitments length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      le_retail_and_corporate.financial_guarantees length = 8   
         format = 15.2,
      le_retail_and_corporate.other_commitments length = 8   
         format = 15.2,
      le_retail_and_corporate._value_adjust_and_provis length = 8   
         format = 15.2,
      . as _financial_guarantees length = 8   
         format = 15.2,
      le_retail_and_corporate.crm__financial_guarantees length = 8   
         format = 15.2,
      le_retail_and_corporate._Funded_credit_prot_not_subst length = 8   
         format = 15.2,
      le_retail_and_corporate._real_estate length = 8   
         format = 15.2,
      0 as _Amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      le_retail_and_corporate.individual_name length = 90   
         label = 'counterparty name (key)',
      le_retail_and_corporate.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      "" as sector_code length = 6   
         label = 'Sector code',
      . as maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      0 as bucket_value_amount length = 8   
         format = 15.2
         label = 'Bucket value amount'
   from
      work.le_retail_and_corporate
   /* Returns all unique rows from the two query results.  */ 
   union all  
   select
      le_derivatives.product_name length = 40   
         format = $40.,
      le_derivatives.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      le_derivatives.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      . as defaulted length = 8   
         format = 15.2,
      le_derivatives.debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      . as equity_instruments length = 8   
         format = 15.2,
      le_derivatives.derivatives length = 8   
         format = 15.2,
      . as loan_commitments length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      . as financial_guarantees length = 8   
         format = 15.2,
      . as other_commitments length = 8   
         format = 15.2,
      . as _value_adjust_and_provis length = 8   
         format = 15.2,
      . as _financial_guarantees length = 8   
         format = 15.2,
      . as crm__financial_guarantees length = 8   
         format = 15.2,
      le_derivatives._Funded_credit_prot_not_subst length = 8   
         format = 15.2,
      . as _real_estate length = 8   
         format = 15.2,
      0 as _Amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      le_derivatives.individual_name length = 90   
         label = 'counterparty name (key)',
      le_derivatives.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      "" as sector_code length = 6   
         label = 'Sector code',
      le_derivatives.maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      le_derivatives.exposure_at_default_amount as bucket_value_amount length = 8   
         format = 15.2
         label = 'Bucket value amount'
   from
      work.le_derivatives
   /* Returns all unique rows from the two query results.  */ 
   union all  
   select
      le_loan_commitments.product_name length = 40   
         format = $40.,
      le_loan_commitments.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      le_loan_commitments.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      . as defaulted length = 8   
         format = 15.2,
      . as debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      . as equity_instruments length = 8   
         format = 15.2,
      . as derivatives length = 8   
         format = 15.2,
      le_loan_commitments.loan_commitments length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      . as financial_guarantees length = 8   
         format = 15.2,
      . as other_commitments length = 8   
         format = 15.2,
      . as _value_adjust_and_provis length = 8   
         format = 15.2,
      . as _financial_guarantees length = 8   
         format = 15.2,
      . as crm__financial_guarantees length = 8   
         format = 15.2,
      . as _Funded_credit_prot_not_subst length = 8   
         format = 15.2,
      . as _real_estate length = 8   
         format = 15.2,
      0 as _Amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      "" as individual_name length = 90   
         label = 'counterparty name (key)',
      le_loan_commitments.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      "" as sector_code length = 6   
         label = 'Sector code',
      . as maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      0 as bucket_value_amount length = 8   
         format = 15.2
         label = 'Bucket value amount'
   from
      work.le_loan_commitments
   /* Returns all unique rows from the two query results.  */ 
   union all  
   select
      LE_manual_entries.product_name length = 40   
         format = $40.,
      LE_manual_entries.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      LE_manual_entries.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      LE_manual_entries.defaulted length = 8   
         format = 15.2,
      LE_manual_entries.debt_instruments length = 8   
         format = 15.2
         label = 'Book value EUR: (Book_Value*Spot_Factor)',
      LE_manual_entries.equity_instruments length = 8   
         format = 15.2,
      LE_manual_entries.derivatives length = 8   
         format = 15.2,
      LE_manual_entries.loan_commitments length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      LE_manual_entries.financial_guarantees length = 8   
         format = 15.2,
      LE_manual_entries.other_commitments length = 8   
         format = 15.2,
      LE_manual_entries._value_adjust_and_provis length = 8   
         format = 15.2,
      LE_manual_entries._financial_guarantees length = 8   
         format = 15.2,
      LE_manual_entries.crm__financial_guarantees length = 8   
         format = 15.2,
      LE_manual_entries._funded_credit_prot_not_subst length = 8   
         format = 15.2,
      LE_manual_entries._real_estate length = 8   
         format = 15.2,
      LE_manual_entries._amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      "" as individual_name length = 90   
         label = 'counterparty name (key)',
      LE_manual_entries.information_date length = 4   
         format = findfdd10.
         label = 'Query position date',
      "" as sector_code length = 6   
         label = 'Sector code',
      . as maturity_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Maturity date',
      LE_manual_entries.bucket_value_amount length = 8   
         format = 15.2
         label = 'Bucket value amount'
   from
      work.LE_manual_entries
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Union **/

/*==========================================================================* 
 * Step:            summary columns                       A5M8HTKH.BU0001AS * 
 * Transform:       Extract                                                 * 
 * Description:     Calculate Exposure_value, Exposure_after_exempt_n_crm.  * 
 *                   Drop zero exposures                                    * 
 *                                                                          * 
 * Source Table:    Set Operators - work.W4VXZXZF         A5M8HTKH.BR0000TW * 
 * Target Table:    Extract - work.active_date_detail     A5M8HTKH.BR0000TX * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AS);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W4VXZXZF); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete active_date_detail;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.active_date_detail as
      select
         product_name,
         code,
         code_client,
         defaulted,
         debt_instruments,
         equity_instruments,
         derivatives,
         loan_commitments,
         financial_guarantees,
         other_commitments,
         _value_adjust_and_provis,
         _financial_guarantees,
         crm__financial_guarantees,
         _Funded_credit_prot_not_subst,
         _real_estate,
         _Amounts_exempted,
         (sum(debt_instruments, equity_instruments, derivatives, loan_commitments, 
              financial_guarantees, other_commitments)) as original_exposure_amount length = 8
            format = 15.2
            label = 'Original exposure value',
         (sum(debt_instruments, equity_instruments, derivatives, loan_commitments, 
              financial_guarantees, other_commitments, _value_adjust_and_provis)) as Exposure_value length = 8
            format = 15.2
            label = 'Book value EUR: (Book_Value*Spot_Factor)',
         (sum(debt_instruments, equity_instruments, derivatives, loan_commitments, 
              financial_guarantees, other_commitments, _value_adjust_and_provis, 
              _financial_guarantees, crm__financial_guarantees, _Funded_credit_prot_not_subst, 
              _real_estate, _Amounts_exempted)) as Exposure_after_exempt_n_crm length = 8
            format = 15.2
            label = 'Book value EUR: (Book_Value*Spot_Factor)',
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)',
         individual_name   
            label = 'counterparty/issuer name (key in some products)',
         information_date,
         sector_code,
         maturity_date,
         bucket_value_amount
   from &SYSLAST
      where code_client ne ' ' and not (calculated original_exposure_amount=0 and calculated Exposure_value=0 and calculated Exposure_after_exempt_n_crm=0)
   ;
quit;

%let SYSLAST = work.active_date_detail;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end summary columns **/

/*==========================================================================* 
 * Step:            Create le_detail_id                   A5M8HTKH.BU0001AT * 
 * Transform:       Extract                                                 * 
 * Description:     Also add maturity_in_days                               * 
 *                                                                          * 
 * Source Table:    Extract - work.active_date_detail     A5M8HTKH.BR0000TX * 
 * Target Table:    Extract - work.W8S23BF                A5M8HTKH.BR0000TY * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AT);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.active_date_detail); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W8S23BF;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W8S23BF as
      select
         information_date,
         (monotonic()) as le_detail_id length = 8,
         product_name,
         code,
         code_client,
         defaulted,
         (case  
               when code  ='7437006WYM821IJ3MN73' then 0 
              else debt_instruments  
            end) as debt_instruments length = 8
            format = 15.2
            label = 'Book value EUR: (Book_Value*Spot_Factor)',
         equity_instruments,
         derivatives,
         loan_commitments,
         financial_guarantees,
         other_commitments,
         _value_adjust_and_provis,
         _financial_guarantees,
         crm__financial_guarantees,
         _Funded_credit_prot_not_subst,
         _real_estate,
         _Amounts_exempted,
         (case  
               when code ='7437006WYM821IJ3MN73' then 0  
            else original_exposure_amount  
            end) as original_exposure_amount length = 8
            format = 15.2
            label = 'Original exposure value',
         (case  
               when code ='7437006WYM821IJ3MN73' then 0  
            else Exposure_value   
            end) as Exposure_value length = 8
            format = 15.2
            label = 'Book value EUR: (Book_Value*Spot_Factor)',
         (case  
               when code ='7437006WYM821IJ3MN73' then 0  
            else Exposure_after_exempt_n_crm  
            end) as Exposure_after_exempt_n_crm length = 8
            format = 15.2
            label = 'Book value EUR: (Book_Value*Spot_Factor)',
         loaded_dt,
         individual_name,
         sector_code,
         maturity_date,
         bucket_value_amount,
         (maturity_date - &active_date) as maturity_in_days length = 8
            label = 'Difference between maturity date and active date'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W8S23BF;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Create le_detail_id **/

/*==========================================================================* 
 * Step:            Maturity buckets calculation          A5M8HTKH.BU0001AU * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W8S23BF                A5M8HTKH.BR0000TY * 
 * Target Table:    Extract - work.W8JMGIU                A5M8HTKH.BR0000TZ * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AU);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W8S23BF); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W8JMGIU;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W8JMGIU as
      select
         information_date,
         le_detail_id,
         product_name,
         code,
         code_client,
         defaulted,
         debt_instruments,
         equity_instruments,
         derivatives,
         loan_commitments,
         financial_guarantees,
         other_commitments,
         _value_adjust_and_provis,
         _financial_guarantees,
         crm__financial_guarantees,
         _Funded_credit_prot_not_subst,
         _real_estate,
         _Amounts_exempted,
         original_exposure_amount,
         Exposure_value,
         Exposure_after_exempt_n_crm,
         loaded_dt,
         individual_name,
         sector_code,
         maturity_date,
         bucket_value_amount,
         maturity_in_days   
            label = 'Number of days between maturity date and active date',
         (case when  maturity_in_days <= 30 or  maturity_in_days =.
            then  bucket_value_amount
            else 0
            end) as _1_m length = 8
            format = 15.2
            label = 'Bucket value amount for 0-30 days to maturity',
         (case when maturity_in_days> 30 and maturity_in_days <= (30*2) 
            then  bucket_value_amount
            else 0
            end) as _1_2_m length = 8
            format = 15.2
            label = 'Bucket value amount for 1 to 2 months(31-60 d) to maturity',
         (case when maturity_in_days> (30*2) and maturity_in_days <= (30*3)
            then  bucket_value_amount
            else 0
            end) as _2_3_m length = 8
            format = 15.2
            label = 'Bucket value amount for 2 to 3 months(61-90 d) to maturity',
         (case when maturity_in_days> (30*3) and maturity_in_days <= (30*4) 
            then  bucket_value_amount
            else 0
            end) as _3_4_m length = 8
            format = 15.2
            label = 'Bucket value amount for 3 to 4 months(91-120 d) to maturity',
         (case when maturity_in_days> (30*4) and maturity_in_days <= (30*5) 
            then  bucket_value_amount
            else 0
            end) as _4_5_m length = 8
            format = 15.2
            label = 'Bucket value amount for 4 to 5 months(121-150 d) to maturity',
         (case when maturity_in_days> (30*5) and maturity_in_days <= (30*6) 
            then  bucket_value_amount
            else 0
            end) as _5_6_m length = 8
            format = 15.2
            label = 'Bucket value amount for 5 to 6 months(151-180 d) to maturity',
         (case when maturity_in_days> (30*6) and maturity_in_days <= (30*7) 
            then  bucket_value_amount
            else 0
            end) as _6_7_m length = 8
            format = 15.2
            label = 'Bucket value amount for 6 to 7 months(181-210 d) to maturity',
         (case when maturity_in_days> (30*7) and maturity_in_days <= (30*8) 
            then  bucket_value_amount
            else 0
            end) as _7_8_m length = 8
            format = 15.2
            label = 'Bucket value amount for 7 to 8 months(211-240 d) to maturity',
         (case when maturity_in_days> (30*8) and maturity_in_days <= (30*9) 
            then  bucket_value_amount
            else 0
            end) as _8_9_m length = 8
            format = 15.2
            label = 'Bucket value amount for 8 to 9 months(241-270 d) to maturity',
         (case when maturity_in_days> (30*9) and maturity_in_days <= (30*10) 
            then  bucket_value_amount
            else 0
            end) as _9_10_m length = 8
            format = 15.2
            label = 'Bucket value amount for 9 to 10 months(271-300 d) to maturity',
         (case when maturity_in_days> (30*10) and maturity_in_days <= (30*11) 
            then  bucket_value_amount
            else 0
            end) as _10_11_m length = 8
            format = 15.2
            label = 'Bucket value amount for 10 to 11 months(301-330 d) to maturity',
         (case when maturity_in_days> (30*11) and maturity_in_days <= (30*12) 
            then  bucket_value_amount
            else 0
            end) as _11_12_m length = 8
            format = 15.2
            label = 'Bucket value amount for 11 to 12 months(331-360 d) to maturity',
         (case when maturity_in_days> (30*12) and maturity_in_days <= (30*15) 
            then  bucket_value_amount
            else 0
            end) as _12_15_m length = 8
            format = 15.2
            label = 'Bucket value amount for 12 to 15 months to maturity',
         (case when maturity_in_days> (30*15) and maturity_in_days <= (30*18) 
            then  bucket_value_amount
            else 0
            end) as _15_18_m length = 8
            format = 15.2
            label = 'Bucket value amount for 15 to 18 months to maturity',
         (case when maturity_in_days> (30*18) and maturity_in_days <= (30*21) 
            then  bucket_value_amount
            else 0
            end) as _18_21_m length = 8
            format = 15.2
            label = 'Bucket value amount for 18 to 21 months to maturity',
         (case when maturity_in_days> (30*21) and maturity_in_days <= (30*24) 
            then  bucket_value_amount
            else 0
            end) as _21_24_m length = 8
            format = 15.2
            label = 'Bucket value amount for 21 to 24 months to maturity',
         (case when maturity_in_days> (30*24) and maturity_in_days <= (30*27) 
            then  bucket_value_amount
            else 0
            end) as _24_27_m length = 8
            format = 15.2
            label = 'Bucket value amount for 24 to 27 months to maturity',
         (case when maturity_in_days> (30*27) and maturity_in_days <= (30*30) 
            then  bucket_value_amount
            else 0
            end) as _27_30_m length = 8
            format = 15.2
            label = 'Bucket value amount for 27 to 30 months to maturity',
         (case when maturity_in_days> (30*30) and maturity_in_days <= (30*33) 
            then  bucket_value_amount
            else 0
            end) as _30_33_m length = 8
            format = 15.2
            label = 'Bucket value amount for 30 to 33 months to maturity',
         (case when maturity_in_days> (30*33) and maturity_in_days <= (30*36) 
            then  bucket_value_amount
            else 0
            end) as _33_36_m length = 8
            format = 15.2
            label = 'Bucket value amount for 33 to 36 months to maturity',
         (case when maturity_in_days> (3*360) and maturity_in_days <= (5*360) 
            then  bucket_value_amount
            else 0
            end) as _3_5_y length = 8
            format = 15.2
            label = 'Bucket value amount for 3 to 5 years to maturity',
         (case when maturity_in_days> (5*360) and maturity_in_days <= (10*360) 
            then  bucket_value_amount
            else 0
            end) as _5_10_y length = 8
            format = 15.2
            label = 'Bucket value amount for 5 to 10 years to maturity',
         (case when maturity_in_days> (10*360) 
            then  bucket_value_amount
            else 0
            end) as _10_y length = 8
            format = 15.2
            label = 'Bucket value amount for over 10 years to maturity'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W8JMGIU;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Maturity buckets calculation **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU0001AV * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W8JMGIU                A5M8HTKH.BR0000TZ * 
 * Target Table:    mco_dm.LE_DETAIL                      A5M8HTKH.BB0000XL * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU0001AV);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W8JMGIU); 

%let _INPUT_count = 1; 
%let _INPUT = work.W8JMGIU;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR0000TZ%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W8JMGIU;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR0000TZ%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mco_dm.LE_DETAIL;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_DETAIL%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Individual exposures before aggregation.);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name sector_code maturity_date bucket_value_amount 
        maturity_in_days _1_m _1_2_m _2_3_m _3_4_m _4_5_m _5_6_m _6_7_m _7_8_m 
        _8_9_m _9_10_m _10_11_m _11_12_m _12_15_m _15_18_m _18_21_m _21_24_m 
        _24_27_m _27_30_m _30_33_m _33_36_m _3_5_y _5_10_y _10_y loaded_dt;

%let _OUTPUT0 = mco_dm.LE_DETAIL;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_DETAIL%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Individual exposures before aggregation.);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name sector_code maturity_date bucket_value_amount 
        maturity_in_days _1_m _1_2_m _2_3_m _3_4_m _4_5_m _5_6_m _6_7_m _7_8_m 
        _8_9_m _9_10_m _10_11_m _11_12_m _12_15_m _15_18_m _18_21_m _21_24_m 
        _24_27_m _27_30_m _30_33_m _33_36_m _3_5_y _5_10_y _10_y loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name sector_code maturity_date bucket_value_amount 
        maturity_in_days _1_m _1_2_m _2_3_m _3_4_m _4_5_m _5_6_m _6_7_m _7_8_m 
        _8_9_m _9_10_m _10_11_m _11_12_m _12_15_m _15_18_m _18_21_m _21_24_m 
        _24_27_m _27_30_m _30_33_m _33_36_m _3_5_y _5_10_y _10_y loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name sector_code maturity_date bucket_value_amount 
        maturity_in_days _1_m _1_2_m _2_3_m _3_4_m _4_5_m _5_6_m _6_7_m _7_8_m 
        _8_9_m _9_10_m _10_11_m _11_12_m _12_15_m _15_18_m _18_21_m _21_24_m 
        _24_27_m _27_30_m _30_33_m _33_36_m _3_5_y _5_10_y _10_y loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mco_dm nolist; 
   modify LE_DETAIL(&altercommand. ); 
      index create primary_index = (information_date le_detail_id)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

