/**************************************************************************** 
 * Job:             mco_dm.le_code_client_sum             A5ZNM6KG.BO0003D6 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mco/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Tables:   mco_dm.DET_LE_GENERAL_INFO            A5ZNM6KG.BG0002JE * 
 *                  mco_dm.DET_LE_CUSTOMER                A5ZNM6KG.BG0002JD * 
 *                  mco_dm.LE_CODE_SUM                    A5ZNM6KG.BG0003CB * 
 *                  mco_dm.LE_DETAIL                      A5ZNM6KG.BG0003CC * 
 *                  mco_dm.DET_LE_GENERAL_INFO            A5ZNM6KG.BG0002JE * 
 * Target Table:    mco_dm.LE_CODE_CLIENT_SUM             A5ZNM6KG.BG0003CA * 
 *                                                                          * 
 * Generated on:    Wednesday, November 23, 2016 3:40:16 PM EET             * 
 * Generated by:    ppr                                                     * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003D6);
%let etls_jobName = %nrquote(mco_dm.le_code_client_sum);
%let etls_userID = %nrquote(ppr);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0002PN * 
 * Transform:       shadow                                                  * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.LE_DETAIL                      A5ZNM6KG.BG0003CC * 
 * Target Table:    shadow_OUTPUT0 - work.W63UGSBS        A5ZNM6KG.BV0002D9 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.LE_DETAIL); 

%let _INPUT_count = 1; 
%let _INPUT = mco_dm.LE_DETAIL;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_DETAIL%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Individual exposures before aggregation.);

%let _INPUT0 = mco_dm.LE_DETAIL;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_DETAIL%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Individual exposures before aggregation.);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W63UGSBS;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002D9%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name loaded_dt;

%let _OUTPUT0 = work.W63UGSBS;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002D9%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W63UGSBS;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date le_detail_id product_name code code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        individual_name loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0002PU * 
 * Transform:       shadow                                                  * 
 * Description:     get group_or_individual                                 * 
 *                                                                          * 
 * Source Table:    mco_dm.DET_LE_CUSTOMER                A5ZNM6KG.BG0002JD * 
 * Target Table:    shadow_det_le_customer -              A5ZNM6KG.BV0002DG * 
 *                   work.shadow_det_le_customer                            * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PU);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.DET_LE_CUSTOMER); 

%let _INPUT_count = 1; 
%let _INPUT = mco_dm.DET_LE_CUSTOMER;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_LE_CUSTOMER%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = mco_dm.DET_LE_CUSTOMER;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_LE_CUSTOMER%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.shadow_det_le_customer;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_det_le_customer_A5ZNM6KG.BV0002DG%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = row_id type code name lei_code country sector nace_code 
        type_of_counterparty group_individual information_date;

%let _OUTPUT0 = work.shadow_det_le_customer;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_det_le_customer_A5ZNM6KG.BV0002DG%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = row_id type code name lei_code country sector nace_code 
        type_of_counterparty group_individual information_date;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete shadow_det_le_customer;
quit;


/* List of target columns to keep  */ 
%let _keep = row_id type code name lei_code country sector nace_code 
        type_of_counterparty group_individual information_date;
/* List of target columns to keep  */ 
%let keep = row_id type code name lei_code country sector nace_code 
        type_of_counterparty group_individual information_date;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0002Q0 * 
 * Transform:       Join                                                    * 
 * Description:     Get Lei code for clients                                * 
 *                                                                          * 
 * Source Tables:   shadow_OUTPUT0 - work.W63UGSBS        A5ZNM6KG.BV0002D9 * 
 *                  shadow_det_le_customer -              A5ZNM6KG.BV0002DG * 
 *                   work.shadow_det_le_customer                            * 
 * Target Table:    Join - work.W5CSMR2G                  A5ZNM6KG.BV0002DL * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002Q0);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W5CSMR2G;
quit;

proc sql;
   create view work.W5CSMR2G as
   select
      W63UGSBS.information_date length = 4   
         format = findfdd10.
         label = 'Information date',
      W63UGSBS.le_detail_id length = 8,
      W63UGSBS.product_name length = 40   
         format = $40.
         label = 'Product name',
      coalesce(shadow_det_le_customer.lei_code ,W63UGSBS.code  ) as code length = 50   
         format = $50.
         label = 'LEI-code or other ID of the Entity/Group',
      W63UGSBS.code_client length = 50   
         format = $50.
         label = 'LEI-code or other ID of the individual counterparty',
      W63UGSBS.defaulted length = 8   
         format = 15.2
         label = 'Defaulted',
      W63UGSBS.debt_instruments length = 8   
         format = 15.2
         label = 'Debt instruments',
      W63UGSBS.equity_instruments length = 8   
         format = 15.2
         label = 'Equity instruments',
      W63UGSBS.derivatives length = 8   
         format = 15.2
         label = 'Derivatives',
      W63UGSBS.loan_commitments length = 8   
         format = 15.2
         label = 'Loan commitments',
      W63UGSBS.financial_guarantees length = 8   
         format = 15.2
         label = 'Financial guarantees',
      W63UGSBS.other_commitments length = 8   
         format = 15.2
         label = 'Other commitments',
      W63UGSBS._value_adjust_and_provis length = 8   
         format = 15.2
         label = '(-) Value adjustments and provisions',
      W63UGSBS._financial_guarantees length = 8   
         format = 15.2
         label = '(-) Financial Guarantees',
      W63UGSBS.crm__financial_guarantees length = 8   
         format = 15.2
         label = 'CRM (-) Financial Guarantees',
      W63UGSBS._funded_credit_prot_not_subst length = 8   
         format = 15.2
         label = '(-) Funded credit protection other than substitution effect',
      W63UGSBS._real_estate length = 8   
         format = 15.2
         label = '(-) Real estate',
      W63UGSBS._amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      W63UGSBS.original_exposure_amount length = 8   
         format = 15.2
         label = 'Original exposure value',
      W63UGSBS.exposure_value length = 8   
         format = 15.2
         label = 'Exposure value',
      W63UGSBS.exposure_after_exempt_n_crm length = 8   
         format = 15.2
         label = 'Exposure value after exemptions and crm',
      W63UGSBS.individual_name length = 90   
         label = 'counterparty/issuer name (key in some products)',
      W63UGSBS.loaded_dt length = 8   
         format = DATETIME20.
         label = 'Load timestamp (date & time)'
   from
      work.W63UGSBS as W63UGSBS left join 
      work.shadow_det_le_customer as shadow_det_le_customer
         on
         (
            W63UGSBS.code_client = shadow_det_le_customer.code
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            sum by code_client                    A5ZNM6KG.BS0002PO * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W5CSMR2G                  A5ZNM6KG.BV0002DL * 
 * Target Table:    sum_by_code_client_1 -                A5ZNM6KG.BV0002DA * 
 *                   work.sum_by_code_client_1                              * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W5CSMR2G); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete sum_by_code_client_1;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.sum_by_code_client_1 as
      select distinct
         code,
         code_client,
         (sum(defaulted)) as defaulted length = 8
            format = 15.2
            label = 'Defaulted',
         (sum(debt_instruments)) as debt_instruments length = 8
            format = 15.2
            label = 'Debt instruments',
         (sum(equity_instruments)) as equity_instruments length = 8
            format = 15.2
            label = 'Equity instruments',
         (sum(derivatives)) as derivatives length = 8
            format = 15.2
            label = 'Derivatives',
         (sum(loan_commitments)) as loan_commitments length = 8
            format = 15.2
            label = 'Loan commitments',
         (sum(financial_guarantees)) as financial_guarantees length = 8
            format = 15.2
            label = 'Financial guarantees',
         (sum(other_commitments)) as other_commitments length = 8
            format = 15.2
            label = 'Other commitments',
         (sum(_value_adjust_and_provis)) as _value_adjust_and_provis length = 8
            format = 15.2
            label = '(-) Value adjustments and provisions',
         (sum(_financial_guarantees)) as _financial_guarantees length = 8
            format = 15.2
            label = '(-) Financial Guarantees',
         (sum(crm__financial_guarantees)) as crm__financial_guarantees length = 8
            format = 15.2
            label = 'CRM (-) Financial Guarantees',
         (sum(_funded_credit_prot_not_subst)) as _Funded_credit_prot_not_subst length = 8
            format = 15.2
            label = '(-) Funded credit protection other than substitution effect',
         (sum(_real_estate)) as _real_estate length = 8
            format = 15.2
            label = '(-) Real estate',
         (sum(_amounts_exempted)) as _amounts_exempted length = 8
            format = 15.2
            label = '(-) Amounts exempted',
         (sum(original_exposure_amount)) as original_exposure_amount length = 8
            format = 15.2
            label = 'Original exposure value',
         (sum(exposure_value)) as exposure_value length = 8
            format = 15.2
            label = 'Exposure value',
         (sum(exposure_after_exempt_n_crm)) as Exposure_after_exempt_n_crm length = 8
            format = 15.2
            label = 'Exposure value after exemptions and crm',
         information_date
   from &SYSLAST
      where information_date=&active_date
   group by
      code,
      code_client
   order by
      code,
      code_client
   ;
quit;

%let SYSLAST = work.sum_by_code_client_1;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end sum by code_client **/

/*==========================================================================* 
 * Step:            adjust excemptions                    A5ZNM6KG.BS0002PP * 
 * Transform:       User Written                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    sum_by_code_client_1 -                A5ZNM6KG.BV0002DA * 
 *                   work.sum_by_code_client_1                              * 
 * Target Table:    sum_by_product_code_client -          A5ZNM6KG.BV0002DB * 
 *                   work.sum_by_code_client                                * 
 *                                                                          * 
 * User Written:    SourceCode                                              * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.sum_by_code_client_1); 

%let _INPUT_count = 1;
%let _INPUT = work.sum_by_code_client_1;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/sum_by_code_client_1_A5ZNM6KG.BV0002DA%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();
%let _INPUT_filetype = WorkTable;

%let _INPUT1 = work.sum_by_code_client_1;
%let _INPUT1_connect = ;
%let _INPUT1_engine = ;
%let _INPUT1_memtype = VIEW;
%let _INPUT1_options = %nrquote();
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/sum_by_code_client_1_A5ZNM6KG.BV0002DA%(WorkTable%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote();
%let _INPUT1_filetype = WorkTable;

%let _OUTPUT_count = 1;
%let _OUTPUT = work.sum_by_code_client;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/sum_by_product_code_client_A5ZNM6KG.BV0002DB%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = code code_client defaulted debt_instruments equity_instruments 
        derivatives loan_commitments financial_guarantees other_commitments 
        _value_adjust_and_provis _financial_guarantees 
        crm__financial_guarantees _Funded_credit_prot_not_subst _real_estate 
        _amounts_exempted original_exposure_amount exposure_value 
        Exposure_after_exempt_n_crm information_date note_txt;
%let _OUTPUT_col_count = 20;
%let _OUTPUT_col0_name = code;
%let _OUTPUT_col0_table = work.sum_by_code_client;
%let _OUTPUT_col0_length = 50;
%let _OUTPUT_col0_type = $;
%let _OUTPUT_col0_format = $50.;
%let _OUTPUT_col0_informat = ;
%let _OUTPUT_col0_label = %nrquote(LEI-code or other ID of the Entity/Group);
%let _OUTPUT_col0_input0 = code;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = code;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = code_client;
%let _OUTPUT_col1_table = work.sum_by_code_client;
%let _OUTPUT_col1_length = 50;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = $50.;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(LEI-code or other ID of the individual counterparty);
%let _OUTPUT_col1_input0 = code_client;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = code_client;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = defaulted;
%let _OUTPUT_col2_table = work.sum_by_code_client;
%let _OUTPUT_col2_length = 8;
%let _OUTPUT_col2_type = ;
%let _OUTPUT_col2_format = 15.2;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Defaulted);
%let _OUTPUT_col2_input0 = defaulted;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = defaulted;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = debt_instruments;
%let _OUTPUT_col3_table = work.sum_by_code_client;
%let _OUTPUT_col3_length = 8;
%let _OUTPUT_col3_type = ;
%let _OUTPUT_col3_format = 15.2;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(Debt instruments);
%let _OUTPUT_col3_input0 = debt_instruments;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = debt_instruments;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = equity_instruments;
%let _OUTPUT_col4_table = work.sum_by_code_client;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 15.2;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(Equity instruments);
%let _OUTPUT_col4_input0 = equity_instruments;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = equity_instruments;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = derivatives;
%let _OUTPUT_col5_table = work.sum_by_code_client;
%let _OUTPUT_col5_length = 8;
%let _OUTPUT_col5_type = ;
%let _OUTPUT_col5_format = 15.2;
%let _OUTPUT_col5_informat = ;
%let _OUTPUT_col5_label = %nrquote(Derivatives);
%let _OUTPUT_col5_input0 = derivatives;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = derivatives;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = loan_commitments;
%let _OUTPUT_col6_table = work.sum_by_code_client;
%let _OUTPUT_col6_length = 8;
%let _OUTPUT_col6_type = ;
%let _OUTPUT_col6_format = 15.2;
%let _OUTPUT_col6_informat = ;
%let _OUTPUT_col6_label = %nrquote(Loan commitments);
%let _OUTPUT_col6_input0 = loan_commitments;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = loan_commitments;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = financial_guarantees;
%let _OUTPUT_col7_table = work.sum_by_code_client;
%let _OUTPUT_col7_length = 8;
%let _OUTPUT_col7_type = ;
%let _OUTPUT_col7_format = 15.2;
%let _OUTPUT_col7_informat = ;
%let _OUTPUT_col7_label = %nrquote(Financial guarantees);
%let _OUTPUT_col7_input0 = financial_guarantees;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = financial_guarantees;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = other_commitments;
%let _OUTPUT_col8_table = work.sum_by_code_client;
%let _OUTPUT_col8_length = 8;
%let _OUTPUT_col8_type = ;
%let _OUTPUT_col8_format = 15.2;
%let _OUTPUT_col8_informat = ;
%let _OUTPUT_col8_label = %nrquote(Other commitments);
%let _OUTPUT_col8_input0 = other_commitments;
%let _OUTPUT_col8_exp = ;
%let _OUTPUT_col8_input = other_commitments;
%let _OUTPUT_col8_input_count = 1;
%let _OUTPUT_col9_name = _value_adjust_and_provis;
%let _OUTPUT_col9_table = work.sum_by_code_client;
%let _OUTPUT_col9_length = 8;
%let _OUTPUT_col9_type = ;
%let _OUTPUT_col9_format = 15.2;
%let _OUTPUT_col9_informat = ;
%let _OUTPUT_col9_label = %nrquote(%(-%) Value adjustments and provisions);
%let _OUTPUT_col9_input0 = _value_adjust_and_provis;
%let _OUTPUT_col9_exp = ;
%let _OUTPUT_col9_input = _value_adjust_and_provis;
%let _OUTPUT_col9_input_count = 1;
%let _OUTPUT_col10_name = _financial_guarantees;
%let _OUTPUT_col10_table = work.sum_by_code_client;
%let _OUTPUT_col10_length = 8;
%let _OUTPUT_col10_type = ;
%let _OUTPUT_col10_format = 15.2;
%let _OUTPUT_col10_informat = ;
%let _OUTPUT_col10_label = %nrquote(%(-%) Financial Guarantees);
%let _OUTPUT_col10_input0 = _financial_guarantees;
%let _OUTPUT_col10_exp = ;
%let _OUTPUT_col10_input = _financial_guarantees;
%let _OUTPUT_col10_input_count = 1;
%let _OUTPUT_col11_name = crm__financial_guarantees;
%let _OUTPUT_col11_table = work.sum_by_code_client;
%let _OUTPUT_col11_length = 8;
%let _OUTPUT_col11_type = ;
%let _OUTPUT_col11_format = 15.2;
%let _OUTPUT_col11_informat = ;
%let _OUTPUT_col11_label = %nrquote(CRM %(-%) Financial Guarantees);
%let _OUTPUT_col11_input0 = crm__financial_guarantees;
%let _OUTPUT_col11_exp = ;
%let _OUTPUT_col11_input = crm__financial_guarantees;
%let _OUTPUT_col11_input_count = 1;
%let _OUTPUT_col12_name = _Funded_credit_prot_not_subst;
%let _OUTPUT_col12_table = work.sum_by_code_client;
%let _OUTPUT_col12_length = 8;
%let _OUTPUT_col12_type = ;
%let _OUTPUT_col12_format = 15.2;
%let _OUTPUT_col12_informat = ;
%let _OUTPUT_col12_label = %nrquote(%(-%) Funded credit protection other than substitution effect);
%let _OUTPUT_col12_input0 = _Funded_credit_prot_not_subst;
%let _OUTPUT_col12_exp = ;
%let _OUTPUT_col12_input = _Funded_credit_prot_not_subst;
%let _OUTPUT_col12_input_count = 1;
%let _OUTPUT_col13_name = _real_estate;
%let _OUTPUT_col13_table = work.sum_by_code_client;
%let _OUTPUT_col13_length = 8;
%let _OUTPUT_col13_type = ;
%let _OUTPUT_col13_format = 15.2;
%let _OUTPUT_col13_informat = ;
%let _OUTPUT_col13_label = %nrquote(%(-%) Real estate);
%let _OUTPUT_col13_input0 = _real_estate;
%let _OUTPUT_col13_exp = ;
%let _OUTPUT_col13_input = _real_estate;
%let _OUTPUT_col13_input_count = 1;
%let _OUTPUT_col14_name = _amounts_exempted;
%let _OUTPUT_col14_table = work.sum_by_code_client;
%let _OUTPUT_col14_length = 8;
%let _OUTPUT_col14_type = ;
%let _OUTPUT_col14_format = 15.2;
%let _OUTPUT_col14_informat = ;
%let _OUTPUT_col14_label = %nrquote(%(-%) Amounts exempted);
%let _OUTPUT_col14_input0 = _amounts_exempted;
%let _OUTPUT_col14_exp = ;
%let _OUTPUT_col14_input = _amounts_exempted;
%let _OUTPUT_col14_input_count = 1;
%let _OUTPUT_col15_name = original_exposure_amount;
%let _OUTPUT_col15_table = work.sum_by_code_client;
%let _OUTPUT_col15_length = 8;
%let _OUTPUT_col15_type = ;
%let _OUTPUT_col15_format = 15.2;
%let _OUTPUT_col15_informat = ;
%let _OUTPUT_col15_label = %nrquote(Original exposure value);
%let _OUTPUT_col15_input0 = original_exposure_amount;
%let _OUTPUT_col15_exp = ;
%let _OUTPUT_col15_input = original_exposure_amount;
%let _OUTPUT_col15_input_count = 1;
%let _OUTPUT_col16_name = exposure_value;
%let _OUTPUT_col16_table = work.sum_by_code_client;
%let _OUTPUT_col16_length = 8;
%let _OUTPUT_col16_type = ;
%let _OUTPUT_col16_format = 15.2;
%let _OUTPUT_col16_informat = ;
%let _OUTPUT_col16_label = %nrquote(Exposure value);
%let _OUTPUT_col16_input0 = exposure_value;
%let _OUTPUT_col16_exp = ;
%let _OUTPUT_col16_input = exposure_value;
%let _OUTPUT_col16_input_count = 1;
%let _OUTPUT_col17_name = Exposure_after_exempt_n_crm;
%let _OUTPUT_col17_table = work.sum_by_code_client;
%let _OUTPUT_col17_length = 8;
%let _OUTPUT_col17_type = ;
%let _OUTPUT_col17_format = 15.2;
%let _OUTPUT_col17_informat = ;
%let _OUTPUT_col17_label = %nrquote(Exposure value after exemptions and crm);
%let _OUTPUT_col17_input0 = Exposure_after_exempt_n_crm;
%let _OUTPUT_col17_exp = ;
%let _OUTPUT_col17_input = Exposure_after_exempt_n_crm;
%let _OUTPUT_col17_input_count = 1;
%let _OUTPUT_col18_name = information_date;
%let _OUTPUT_col18_table = work.sum_by_code_client;
%let _OUTPUT_col18_length = 4;
%let _OUTPUT_col18_type = ;
%let _OUTPUT_col18_format = findfdd10.;
%let _OUTPUT_col18_informat = ;
%let _OUTPUT_col18_label = %nrquote(Information date);
%let _OUTPUT_col18_input0 = information_date;
%let _OUTPUT_col18_exp = ;
%let _OUTPUT_col18_input = information_date;
%let _OUTPUT_col18_input_count = 1;
%let _OUTPUT_col19_name = note_txt;
%let _OUTPUT_col19_table = work.sum_by_code_client;
%let _OUTPUT_col19_length = 40;
%let _OUTPUT_col19_type = $;
%let _OUTPUT_col19_format = ;
%let _OUTPUT_col19_informat = ;
%let _OUTPUT_col19_label = %nrquote(Adjustment made);
%let _OUTPUT_col19_exp = ;
%let _OUTPUT_col19_input_count = 0;
%let _OUTPUT_filetype = WorkTable;

%let _OUTPUT1 = work.sum_by_code_client;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/sum_by_product_code_client_A5ZNM6KG.BV0002DB%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = code code_client defaulted debt_instruments equity_instruments 
        derivatives loan_commitments financial_guarantees other_commitments 
        _value_adjust_and_provis _financial_guarantees 
        crm__financial_guarantees _Funded_credit_prot_not_subst _real_estate 
        _amounts_exempted original_exposure_amount exposure_value 
        Exposure_after_exempt_n_crm information_date note_txt;
%let _OUTPUT1_col_count = 20;
%let _OUTPUT1_col0_name = code;
%let _OUTPUT1_col0_table = work.sum_by_code_client;
%let _OUTPUT1_col0_length = 50;
%let _OUTPUT1_col0_type = $;
%let _OUTPUT1_col0_format = $50.;
%let _OUTPUT1_col0_informat = ;
%let _OUTPUT1_col0_label = %nrquote(LEI-code or other ID of the Entity/Group);
%let _OUTPUT1_col0_input0 = code;
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input = code;
%let _OUTPUT1_col0_input_count = 1;
%let _OUTPUT1_col1_name = code_client;
%let _OUTPUT1_col1_table = work.sum_by_code_client;
%let _OUTPUT1_col1_length = 50;
%let _OUTPUT1_col1_type = $;
%let _OUTPUT1_col1_format = $50.;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote(LEI-code or other ID of the individual counterparty);
%let _OUTPUT1_col1_input0 = code_client;
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input = code_client;
%let _OUTPUT1_col1_input_count = 1;
%let _OUTPUT1_col2_name = defaulted;
%let _OUTPUT1_col2_table = work.sum_by_code_client;
%let _OUTPUT1_col2_length = 8;
%let _OUTPUT1_col2_type = ;
%let _OUTPUT1_col2_format = 15.2;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote(Defaulted);
%let _OUTPUT1_col2_input0 = defaulted;
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input = defaulted;
%let _OUTPUT1_col2_input_count = 1;
%let _OUTPUT1_col3_name = debt_instruments;
%let _OUTPUT1_col3_table = work.sum_by_code_client;
%let _OUTPUT1_col3_length = 8;
%let _OUTPUT1_col3_type = ;
%let _OUTPUT1_col3_format = 15.2;
%let _OUTPUT1_col3_informat = ;
%let _OUTPUT1_col3_label = %nrquote(Debt instruments);
%let _OUTPUT1_col3_input0 = debt_instruments;
%let _OUTPUT1_col3_exp = ;
%let _OUTPUT1_col3_input = debt_instruments;
%let _OUTPUT1_col3_input_count = 1;
%let _OUTPUT1_col4_name = equity_instruments;
%let _OUTPUT1_col4_table = work.sum_by_code_client;
%let _OUTPUT1_col4_length = 8;
%let _OUTPUT1_col4_type = ;
%let _OUTPUT1_col4_format = 15.2;
%let _OUTPUT1_col4_informat = ;
%let _OUTPUT1_col4_label = %nrquote(Equity instruments);
%let _OUTPUT1_col4_input0 = equity_instruments;
%let _OUTPUT1_col4_exp = ;
%let _OUTPUT1_col4_input = equity_instruments;
%let _OUTPUT1_col4_input_count = 1;
%let _OUTPUT1_col5_name = derivatives;
%let _OUTPUT1_col5_table = work.sum_by_code_client;
%let _OUTPUT1_col5_length = 8;
%let _OUTPUT1_col5_type = ;
%let _OUTPUT1_col5_format = 15.2;
%let _OUTPUT1_col5_informat = ;
%let _OUTPUT1_col5_label = %nrquote(Derivatives);
%let _OUTPUT1_col5_input0 = derivatives;
%let _OUTPUT1_col5_exp = ;
%let _OUTPUT1_col5_input = derivatives;
%let _OUTPUT1_col5_input_count = 1;
%let _OUTPUT1_col6_name = loan_commitments;
%let _OUTPUT1_col6_table = work.sum_by_code_client;
%let _OUTPUT1_col6_length = 8;
%let _OUTPUT1_col6_type = ;
%let _OUTPUT1_col6_format = 15.2;
%let _OUTPUT1_col6_informat = ;
%let _OUTPUT1_col6_label = %nrquote(Loan commitments);
%let _OUTPUT1_col6_input0 = loan_commitments;
%let _OUTPUT1_col6_exp = ;
%let _OUTPUT1_col6_input = loan_commitments;
%let _OUTPUT1_col6_input_count = 1;
%let _OUTPUT1_col7_name = financial_guarantees;
%let _OUTPUT1_col7_table = work.sum_by_code_client;
%let _OUTPUT1_col7_length = 8;
%let _OUTPUT1_col7_type = ;
%let _OUTPUT1_col7_format = 15.2;
%let _OUTPUT1_col7_informat = ;
%let _OUTPUT1_col7_label = %nrquote(Financial guarantees);
%let _OUTPUT1_col7_input0 = financial_guarantees;
%let _OUTPUT1_col7_exp = ;
%let _OUTPUT1_col7_input = financial_guarantees;
%let _OUTPUT1_col7_input_count = 1;
%let _OUTPUT1_col8_name = other_commitments;
%let _OUTPUT1_col8_table = work.sum_by_code_client;
%let _OUTPUT1_col8_length = 8;
%let _OUTPUT1_col8_type = ;
%let _OUTPUT1_col8_format = 15.2;
%let _OUTPUT1_col8_informat = ;
%let _OUTPUT1_col8_label = %nrquote(Other commitments);
%let _OUTPUT1_col8_input0 = other_commitments;
%let _OUTPUT1_col8_exp = ;
%let _OUTPUT1_col8_input = other_commitments;
%let _OUTPUT1_col8_input_count = 1;
%let _OUTPUT1_col9_name = _value_adjust_and_provis;
%let _OUTPUT1_col9_table = work.sum_by_code_client;
%let _OUTPUT1_col9_length = 8;
%let _OUTPUT1_col9_type = ;
%let _OUTPUT1_col9_format = 15.2;
%let _OUTPUT1_col9_informat = ;
%let _OUTPUT1_col9_label = %nrquote(%(-%) Value adjustments and provisions);
%let _OUTPUT1_col9_input0 = _value_adjust_and_provis;
%let _OUTPUT1_col9_exp = ;
%let _OUTPUT1_col9_input = _value_adjust_and_provis;
%let _OUTPUT1_col9_input_count = 1;
%let _OUTPUT1_col10_name = _financial_guarantees;
%let _OUTPUT1_col10_table = work.sum_by_code_client;
%let _OUTPUT1_col10_length = 8;
%let _OUTPUT1_col10_type = ;
%let _OUTPUT1_col10_format = 15.2;
%let _OUTPUT1_col10_informat = ;
%let _OUTPUT1_col10_label = %nrquote(%(-%) Financial Guarantees);
%let _OUTPUT1_col10_input0 = _financial_guarantees;
%let _OUTPUT1_col10_exp = ;
%let _OUTPUT1_col10_input = _financial_guarantees;
%let _OUTPUT1_col10_input_count = 1;
%let _OUTPUT1_col11_name = crm__financial_guarantees;
%let _OUTPUT1_col11_table = work.sum_by_code_client;
%let _OUTPUT1_col11_length = 8;
%let _OUTPUT1_col11_type = ;
%let _OUTPUT1_col11_format = 15.2;
%let _OUTPUT1_col11_informat = ;
%let _OUTPUT1_col11_label = %nrquote(CRM %(-%) Financial Guarantees);
%let _OUTPUT1_col11_input0 = crm__financial_guarantees;
%let _OUTPUT1_col11_exp = ;
%let _OUTPUT1_col11_input = crm__financial_guarantees;
%let _OUTPUT1_col11_input_count = 1;
%let _OUTPUT1_col12_name = _Funded_credit_prot_not_subst;
%let _OUTPUT1_col12_table = work.sum_by_code_client;
%let _OUTPUT1_col12_length = 8;
%let _OUTPUT1_col12_type = ;
%let _OUTPUT1_col12_format = 15.2;
%let _OUTPUT1_col12_informat = ;
%let _OUTPUT1_col12_label = %nrquote(%(-%) Funded credit protection other than substitution effect);
%let _OUTPUT1_col12_input0 = _Funded_credit_prot_not_subst;
%let _OUTPUT1_col12_exp = ;
%let _OUTPUT1_col12_input = _Funded_credit_prot_not_subst;
%let _OUTPUT1_col12_input_count = 1;
%let _OUTPUT1_col13_name = _real_estate;
%let _OUTPUT1_col13_table = work.sum_by_code_client;
%let _OUTPUT1_col13_length = 8;
%let _OUTPUT1_col13_type = ;
%let _OUTPUT1_col13_format = 15.2;
%let _OUTPUT1_col13_informat = ;
%let _OUTPUT1_col13_label = %nrquote(%(-%) Real estate);
%let _OUTPUT1_col13_input0 = _real_estate;
%let _OUTPUT1_col13_exp = ;
%let _OUTPUT1_col13_input = _real_estate;
%let _OUTPUT1_col13_input_count = 1;
%let _OUTPUT1_col14_name = _amounts_exempted;
%let _OUTPUT1_col14_table = work.sum_by_code_client;
%let _OUTPUT1_col14_length = 8;
%let _OUTPUT1_col14_type = ;
%let _OUTPUT1_col14_format = 15.2;
%let _OUTPUT1_col14_informat = ;
%let _OUTPUT1_col14_label = %nrquote(%(-%) Amounts exempted);
%let _OUTPUT1_col14_input0 = _amounts_exempted;
%let _OUTPUT1_col14_exp = ;
%let _OUTPUT1_col14_input = _amounts_exempted;
%let _OUTPUT1_col14_input_count = 1;
%let _OUTPUT1_col15_name = original_exposure_amount;
%let _OUTPUT1_col15_table = work.sum_by_code_client;
%let _OUTPUT1_col15_length = 8;
%let _OUTPUT1_col15_type = ;
%let _OUTPUT1_col15_format = 15.2;
%let _OUTPUT1_col15_informat = ;
%let _OUTPUT1_col15_label = %nrquote(Original exposure value);
%let _OUTPUT1_col15_input0 = original_exposure_amount;
%let _OUTPUT1_col15_exp = ;
%let _OUTPUT1_col15_input = original_exposure_amount;
%let _OUTPUT1_col15_input_count = 1;
%let _OUTPUT1_col16_name = exposure_value;
%let _OUTPUT1_col16_table = work.sum_by_code_client;
%let _OUTPUT1_col16_length = 8;
%let _OUTPUT1_col16_type = ;
%let _OUTPUT1_col16_format = 15.2;
%let _OUTPUT1_col16_informat = ;
%let _OUTPUT1_col16_label = %nrquote(Exposure value);
%let _OUTPUT1_col16_input0 = exposure_value;
%let _OUTPUT1_col16_exp = ;
%let _OUTPUT1_col16_input = exposure_value;
%let _OUTPUT1_col16_input_count = 1;
%let _OUTPUT1_col17_name = Exposure_after_exempt_n_crm;
%let _OUTPUT1_col17_table = work.sum_by_code_client;
%let _OUTPUT1_col17_length = 8;
%let _OUTPUT1_col17_type = ;
%let _OUTPUT1_col17_format = 15.2;
%let _OUTPUT1_col17_informat = ;
%let _OUTPUT1_col17_label = %nrquote(Exposure value after exemptions and crm);
%let _OUTPUT1_col17_input0 = Exposure_after_exempt_n_crm;
%let _OUTPUT1_col17_exp = ;
%let _OUTPUT1_col17_input = Exposure_after_exempt_n_crm;
%let _OUTPUT1_col17_input_count = 1;
%let _OUTPUT1_col18_name = information_date;
%let _OUTPUT1_col18_table = work.sum_by_code_client;
%let _OUTPUT1_col18_length = 4;
%let _OUTPUT1_col18_type = ;
%let _OUTPUT1_col18_format = findfdd10.;
%let _OUTPUT1_col18_informat = ;
%let _OUTPUT1_col18_label = %nrquote(Information date);
%let _OUTPUT1_col18_input0 = information_date;
%let _OUTPUT1_col18_exp = ;
%let _OUTPUT1_col18_input = information_date;
%let _OUTPUT1_col18_input_count = 1;
%let _OUTPUT1_col19_name = note_txt;
%let _OUTPUT1_col19_table = work.sum_by_code_client;
%let _OUTPUT1_col19_length = 40;
%let _OUTPUT1_col19_type = $;
%let _OUTPUT1_col19_format = ;
%let _OUTPUT1_col19_informat = ;
%let _OUTPUT1_col19_label = %nrquote(Adjustment made);
%let _OUTPUT1_col19_exp = ;
%let _OUTPUT1_col19_input_count = 0;
%let _OUTPUT1_filetype = WorkTable;

/*---- Start of User Written Code  ----*/ 

data &_OUTPUT1 ;
  set &_INPUT1 ;
  length note_txt $40 ;
  if Exposure_after_exempt_n_crm < 0 then do;
    xmpts=sum(crm__financial_guarantees, _real_estate,_Funded_credit_prot_not_subst,_value_adjust_and_provis,0) ;
    if abs(crm__financial_guarantees) > 0 then do ;
      crm__financial_guarantees=round(crm__financial_guarantees-Exposure_after_exempt_n_crm*(crm__financial_guarantees/xmpts),0.01);
      note_txt='crm__financial_guarantees adjusted (maybe others)' ;
    end ;
    if abs(_real_estate) > 0 then do ;
      _real_estate=round(_real_estate-Exposure_after_exempt_n_crm*(_real_estate/xmpts),0.01);
      note_txt='_real_estate adjusted (maybe others)' ;
    end ;
    if abs(_funded_credit_prot_not_subst) > 0 then do ;
      _Funded_credit_prot_not_subst=round(_Funded_credit_prot_not_subst-Exposure_after_exempt_n_crm*(_Funded_credit_prot_not_subst/xmpts),0.01);
      note_txt='_funded_credit_prot_not_subst adjusted (maybe others)' ;
    end ;
    if abs(_value_adjust_and_provis) > 0 then do ;
      _value_adjust_and_provis=round(_value_adjust_and_provis-Exposure_after_exempt_n_crm*(_value_adjust_and_provis/xmpts),0.01);
      note_txt='_value_adjust_and_provis adjusted (maybe others)' ;
    end ;
    Exposure_after_exempt_n_crm=round(sum(debt_instruments, loan_commitments, financial_guarantees, other_commitments, _value_adjust_and_provis, 
      crm__financial_guarantees, _funded_credit_prot_not_subst, _real_estate, _amounts_exempted),0.01) ;
  end ;
  drop xmpts ;
run ;

/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 


/**  Step end adjust excemptions **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0002PQ * 
 * Transform:       shadow                                                  * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.DET_LE_GENERAL_INFO            A5ZNM6KG.BG0002JE * 
 * Target Table:    shadow_OUTPUT0 - work.W5S0LZHP        A5ZNM6KG.BV0002DC * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.DET_LE_GENERAL_INFO); 

%let _INPUT_count = 1; 
%let _INPUT = mco_dm.DET_LE_GENERAL_INFO;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_LE_GENERAL_INFO%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = mco_dm.DET_LE_GENERAL_INFO;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_LE_GENERAL_INFO%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W5S0LZHP;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002DC%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;

%let _OUTPUT0 = work.W5S0LZHP;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002DC%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W5S0LZHP;
quit;


/* List of target columns to keep  */ 
%let _keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;
/* List of target columns to keep  */ 
%let keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            eligible_capital for 205              A5ZNM6KG.BS0002PR * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 - work.W5S0LZHP        A5ZNM6KG.BV0002DC * 
 * Target Table:    eligible_capital -                    A5ZNM6KG.BV0002DD * 
 *                   work.extract_eligible_capital                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PR);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W5S0LZHP); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete extract_eligible_capital;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.extract_eligible_capital as
      select distinct
         (round(input(input_data,best20.)/0.25,0.01)) as eligible_capital_205 length = 8
            format = 15.2,
         (round(information_date,1)) as information_date length = 4
            format = FINDFDD10.
   from &SYSLAST
      (OBS=1)
      where row_id='3' and input_data ne ''
         and information_date=&active_date
   ;
quit;

%let SYSLAST = work.extract_eligible_capital;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end eligible_capital for 205 **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0002PS * 
 * Transform:       shadow                                                  * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mco_dm.DET_LE_GENERAL_INFO            A5ZNM6KG.BG0002JE * 
 * Target Table:    shadow_OUTPUT0 - work.W2XXD6RY        A5ZNM6KG.BV0002DE * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PS);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.DET_LE_GENERAL_INFO); 

%let _INPUT_count = 1; 
%let _INPUT = mco_dm.DET_LE_GENERAL_INFO;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_LE_GENERAL_INFO%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = mco_dm.DET_LE_GENERAL_INFO;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_LE_GENERAL_INFO%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W2XXD6RY;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002DE%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;

%let _OUTPUT0 = work.W2XXD6RY;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002DE%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W2XXD6RY;
quit;


/* List of target columns to keep  */ 
%let _keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;
/* List of target columns to keep  */ 
%let keep = row_id applicable sheet_row title input_data template_id entity 
        id_type id information_date corep_type address;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            eligible capital for 201              A5ZNM6KG.BS0002PT * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 - work.W2XXD6RY        A5ZNM6KG.BV0002DE * 
 * Target Table:    Extract -                             A5ZNM6KG.BV0002DF * 
 *                   work.ext_eligible_capital_201                          * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PT);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W2XXD6RY); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete ext_eligible_capital_201;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.ext_eligible_capital_201 as
      select
         row_id,
         (round(input(input_data,best20.)/0.25,0.01)) as eligible_capital_201 length = 8
            format = 15.2,
         (round(information_date,1)) as information_date length = 8
            format = FINDFDD10.
   from &SYSLAST
      where row_id='8' and input_data ne '' 
         and information_date=&active_date
   ;
quit;

%let SYSLAST = work.ext_eligible_capital_201;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end eligible capital for 201 **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0002PV * 
 * Transform:       Join                                                    * 
 * Description:     Eligible capital pct fields defined                     * 
 *                                                                          * 
 * Source Tables:   eligible_capital -                    A5ZNM6KG.BV0002DD * 
 *                   work.extract_eligible_capital                          * 
 *                  shadow_det_le_customer -              A5ZNM6KG.BV0002DG * 
 *                   work.shadow_det_le_customer                            * 
 *                  sum_by_product_code_client -          A5ZNM6KG.BV0002DB * 
 *                   work.sum_by_code_client                                * 
 *                  Extract -                             A5ZNM6KG.BV0002DF * 
 *                   work.ext_eligible_capital_201                          * 
 * Target Table:    Join - work.W621AL3P                  A5ZNM6KG.BV0002DH * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PV);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W621AL3P;
quit;

proc sql;
   create view work.W621AL3P as
   select distinct
      sum_by_code_client.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      case shadow_det_le_customer.group_individual 
        when 'eba_ZZ:x2' then 'eba_ZZ:x2' 
        when ' ' then 'eba_ZZ:x1' 
        else ' ' 
      end as group_individual length = 16,
      sum_by_code_client.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      sum_by_code_client.defaulted length = 8   
         format = 15.2
         label = 'Defaulted',
      sum_by_code_client.debt_instruments length = 8   
         format = 15.2
         label = 'Debt instruments',
      sum_by_code_client.equity_instruments length = 8   
         format = 15.2
         label = 'Equity instruments',
      sum_by_code_client.derivatives length = 8   
         format = 15.2
         label = 'Derivatives',
      sum_by_code_client.loan_commitments length = 8   
         format = 15.2
         label = 'Loan commitments',
      sum_by_code_client.financial_guarantees length = 8   
         format = 15.2
         label = 'Financial guarantees',
      sum_by_code_client.other_commitments length = 8   
         format = 15.2
         label = 'Other commitments',
      sum_by_code_client._value_adjust_and_provis length = 8   
         format = 15.2
         label = '(-) Value adjustments and provisions',
      sum_by_code_client._financial_guarantees length = 8   
         format = 15.2
         label = '(-) Financial Guarantees',
      sum_by_code_client.crm__financial_guarantees length = 8   
         format = 15.2
         label = 'CRM (-) Financial Guarantees',
      sum_by_code_client._Funded_credit_prot_not_subst length = 8   
         format = 15.2
         label = '(-) Funded credit protection other than substitution effect',
      sum_by_code_client._real_estate length = 8   
         format = 15.2
         label = '(-) Real estate',
      sum_by_code_client._amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      sum_by_code_client.original_exposure_amount length = 8   
         format = 15.2
         label = 'Original exposure value',
      sum_by_code_client.exposure_value length = 8   
         format = 15.2
         label = 'Exposure value',
      sum_by_code_client.Exposure_after_exempt_n_crm length = 8   
         format = 15.2
         label = 'Exposure value after exemptions and crm',
      case 
      when extract_eligible_capital.eligible_capital_205 ne . 
      then sum_by_code_client.exposure_value /extract_eligible_capital.eligible_capital_205
      else .
      end as eligible_capital_1_pct length = 8   
         format = 10.7,
      case 
      when extract_eligible_capital.eligible_capital_205 ne . then
      sum_by_code_client.Exposure_after_exempt_n_crm  /extract_eligible_capital.eligible_capital_205
      else .
      end as eligible_capital_2_pct length = 8   
         format = 10.7,
      %sysfunc(round(%sysfunc(datetime()),1)) as loaded_dt length = 8   
         format = DATETIME20.
         label = 'Load timestamp (date & time)',
      sum_by_code_client.information_date length = 4   
         format = findfdd10.
         label = 'Information date',
      sum_by_code_client.note_txt length = 40   
         label = 'Adjustment made',
      case 
      when ext_eligible_capital_201.eligible_capital_201 ne . 
      then sum_by_code_client.exposure_value /ext_eligible_capital_201.eligible_capital_201 
      else .
      end as eligible_capital_1_pct_201 length = 8   
         format = 10.7,
      case 
      when ext_eligible_capital_201.eligible_capital_201  ne . then
      sum_by_code_client.Exposure_after_exempt_n_crm/ext_eligible_capital_201.eligible_capital_201 
      else .
      end as eligible_capital_2_pct_201 length = 8   
         format = 10.7
   from
      work.sum_by_code_client as sum_by_code_client left join 
      work.extract_eligible_capital as extract_eligible_capital
         on
         (
            extract_eligible_capital.information_date = sum_by_code_client.information_date
         ) left join 
      work.shadow_det_le_customer as shadow_det_le_customer
         on
         (
            sum_by_code_client.code_client = shadow_det_le_customer.code
         ) left join 
      work.ext_eligible_capital_201 as ext_eligible_capital_201
         on
         (
            sum_by_code_client.information_date = ext_eligible_capital_201.information_date
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0002PW * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mco_dm.LE_CODE_SUM                    A5ZNM6KG.BG0003CB * 
 * Target Table:    shadow_OUTPUT0 - work.W9DTCLSF        A5ZNM6KG.BV0002DI * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PW);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.LE_CODE_SUM); 

%let _INPUT_count = 1; 
%let _INPUT = mco_dm.LE_CODE_SUM;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_CODE_SUM%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = mco_dm.LE_CODE_SUM;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_CODE_SUM%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W9DTCLSF;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002DI%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date code flag_a flag_b;

%let _OUTPUT0 = work.W9DTCLSF;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0002DI%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date code flag_a flag_b;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W9DTCLSF;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date code flag_a flag_b;
/* List of target columns to keep  */ 
%let keep = information_date code flag_a flag_b;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0002PX * 
 * Transform:       Extract                                                 * 
 * Description:     Flag_a ne null or Flag_b ne null                        * 
 *                                                                          * 
 * Source Table:    shadow_OUTPUT0 - work.W9DTCLSF        A5ZNM6KG.BV0002DI * 
 * Target Table:    Extract - work.W2YZN0T8               A5ZNM6KG.BV0002DJ * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PX);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W9DTCLSF); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W2YZN0T8;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W2YZN0T8 as
      select
         information_date,
         code,
         flag_a,
         flag_b
   from &SYSLAST
      where flag_a ne '' or flag_b ne ''
   ;
quit;

%let SYSLAST = work.W2YZN0T8;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0002PY * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Join - work.W621AL3P                  A5ZNM6KG.BV0002DH * 
 *                  Extract - work.W2YZN0T8               A5ZNM6KG.BV0002DJ * 
 * Target Table:    Join - work.W9DT9PEU                  A5ZNM6KG.BV0002DK * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PY);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W9DT9PEU;
quit;

proc sql;
   create table work.W9DT9PEU as
   select
      W2YZN0T8.information_date length = 4   
         format = findfdd10.
         label = 'Information date',
      W2YZN0T8.code length = 50   
         format = $50.
         label = 'SSN of the Entity/Group/Mother: e.g. 0144123-4 or 230264-1234',
      W621AL3P.group_individual length = 16,
      W621AL3P.code_client length = 50   
         format = $50.
         label = 'Social security / organisation number',
      W621AL3P.defaulted length = 8   
         format = 15.2
         label = 'Defaulted',
      W621AL3P.debt_instruments length = 8   
         format = 15.2
         label = 'Debt instruments',
      W621AL3P.equity_instruments length = 8   
         format = 15.2
         label = 'Equity instruments',
      W621AL3P.derivatives length = 8   
         format = 15.2
         label = 'Derivatives',
      W621AL3P.loan_commitments length = 8   
         format = 15.2
         label = 'Loan commitments',
      W621AL3P.financial_guarantees length = 8   
         format = 15.2
         label = 'Financial guarantees',
      W621AL3P.other_commitments length = 8   
         format = 15.2
         label = 'Other commitments',
      W621AL3P._value_adjust_and_provis length = 8   
         format = 15.2
         label = '(-) Value adjustments and provisions',
      W621AL3P._financial_guarantees length = 8   
         format = 15.2
         label = '(-) Financial Guarantees',
      W621AL3P.crm__financial_guarantees length = 8   
         format = 15.2
         label = 'CRM (-) Financial Guarantees',
      W621AL3P._funded_credit_prot_not_subst length = 8   
         format = 15.2
         label = '(-) Funded credit protection other than substitution effect',
      W621AL3P._real_estate length = 8   
         format = 15.2
         label = '(-) Real estate',
      W621AL3P._amounts_exempted length = 8   
         format = 15.2
         label = '(-) Amounts exempted',
      W621AL3P.original_exposure_amount length = 8   
         format = 15.2
         label = 'Original exposure value',
      W621AL3P.exposure_value length = 8   
         format = 15.2
         label = 'Exposure value',
      W621AL3P.exposure_after_exempt_n_crm length = 8   
         format = 15.2
         label = 'Exposure value after exemptions and crm',
      W621AL3P.eligible_capital_1_pct length = 8   
         format = 10.7,
      W621AL3P.eligible_capital_2_pct length = 8   
         format = 10.7,
      W621AL3P.eligible_capital_1_pct_201 length = 8   
         format = 10.7,
      W621AL3P.eligible_capital_2_pct_201 length = 8   
         format = 10.7,
      trim(W621AL3P.code_client)!!'|'!!trim(W2YZN0T8.code) as client_group_key length = 100,
      substr(W2YZN0T8.flag_a,1,1)!!substr(W2YZN0T8.flag_b,1,1) as flags length = 8,
      W621AL3P.note_txt length = 40   
         label = 'Adjustment made',
      %sysfunc(round(%sysfunc(datetime()),1)) as loaded_dt length = 8   
         format = DATETIME20.
         label = 'Load timestamp (date & time)'
   from
      work.W2YZN0T8 as W2YZN0T8 left join 
      work.W621AL3P as W621AL3P
         on
         (
            W2YZN0T8.information_date = W621AL3P.information_date
            and W2YZN0T8.code = W621AL3P.code
            and W621AL3P.group_individual = "eba_ZZ:x2"
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0002PZ * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Join - work.W9DT9PEU                  A5ZNM6KG.BV0002DK * 
 * Target Table:    mco_dm.LE_CODE_CLIENT_SUM             A5ZNM6KG.BG0003CA * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0002PZ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W9DT9PEU); 

%let _INPUT_count = 1; 
%let _INPUT = work.W9DT9PEU;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Join_A5ZNM6KG.BV0002DK%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W9DT9PEU;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Join_A5ZNM6KG.BV0002DK%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mco_dm.LE_CODE_CLIENT_SUM;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_CODE_CLIENT_SUM%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date code group_individual code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        eligible_capital_1_pct eligible_capital_2_pct 
        eligible_capital_1_pct_201 eligible_capital_2_pct_201 client_group_key 
        flags note_txt loaded_dt;

%let _OUTPUT0 = mco_dm.LE_CODE_CLIENT_SUM;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.LE_CODE_CLIENT_SUM%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date code group_individual code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        eligible_capital_1_pct eligible_capital_2_pct 
        eligible_capital_1_pct_201 eligible_capital_2_pct_201 client_group_key 
        flags note_txt loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date code group_individual code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        eligible_capital_1_pct eligible_capital_2_pct 
        eligible_capital_1_pct_201 eligible_capital_2_pct_201 client_group_key 
        flags note_txt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date code group_individual code_client defaulted 
        debt_instruments equity_instruments derivatives loan_commitments 
        financial_guarantees other_commitments _value_adjust_and_provis 
        _financial_guarantees crm__financial_guarantees 
        _funded_credit_prot_not_subst _real_estate _amounts_exempted 
        original_exposure_amount exposure_value exposure_after_exempt_n_crm 
        eligible_capital_1_pct eligible_capital_2_pct 
        eligible_capital_1_pct_201 eligible_capital_2_pct_201 client_group_key 
        flags note_txt loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mco_dm nolist; 
   modify LE_CODE_CLIENT_SUM(ALTER=&alterpass ); 
      index create primary_index = (information_date code code_client)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

