/**************************************************************************** 
 * Job:             mco_dm.basel_irb                      A5M8HTKH.BO0000F0 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: 217.29.235.142                                          * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mco/programs/jobs                          * 
 *                                                                          * 
 * Server:          SASApp                                A5M8HTKH.AS000002 * 
 *                                                                          * 
 * Source Tables:   dw_dw.BASEL_IRB                       A5M8HTKH.BB00003N * 
 *                  dw_dw.ACCOUNT                         A5M8HTKH.BB000026 * 
 *                  mco_dm.BASEL_IRB_H                    A5M8HTKH.BB0000UU * 
 *                  mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 *                  mco_dm.DET_COREP_ECL                  A5M8HTKH.BB0000VP * 
 * Target Tables:   mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 *                  mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 *                  mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 *                                                                          * 
 * Generated on:    Tuesday, November 24, 2020 1:29:53 PM EET               * 
 * Generated by:    pwagh                                                   * 
 * Version:         SAS Data Integration Studio 4.904                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5M8HTKH.BO0000F0);
%let etls_jobName = %nrquote(mco_dm.basel_irb);
%let etls_userID = %nrquote(pwagh);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */ 
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU00014P * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.BASEL_IRB                       A5M8HTKH.BB00003N * 
 * Target Table:    shadow_OUTPUT0 - work.WIM23GQ         A5M8HTKH.BR0000PE * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014P);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.BASEL_IRB); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.BASEL_IRB;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.BASEL_IRB%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Monthly IRB data, approved);

%let _INPUT0 = dw_dw.BASEL_IRB;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.BASEL_IRB%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Monthly IRB data, approved);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.WIM23GQ;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0000PE%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type source_system_cd 
        extracted_dt loaded_dt supporting_factor_pct;

%let _OUTPUT0 = work.WIM23GQ;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0000PE%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type source_system_cd 
        extracted_dt loaded_dt supporting_factor_pct;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete WIM23GQ;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type source_system_cd 
        extracted_dt loaded_dt supporting_factor_pct;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type source_system_cd 
        extracted_dt loaded_dt supporting_factor_pct;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU00014Q * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT                         A5M8HTKH.BB000026 * 
 * Target Table:    shadow_OUTPUT0 - work.W70XYLMX        A5M8HTKH.BR0000PF * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014Q);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.ACCOUNT;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.ACCOUNT;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.W70XYLMX;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0000PF%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id owner_ssn_id;

%let _OUTPUT0 = work.W70XYLMX;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5M8HTKH.BR0000PF%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id owner_ssn_id;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete W70XYLMX;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id owner_ssn_id;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id owner_ssn_id;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5M8HTKH.BU00014R * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   dw_dw.BASEL_IRB						  A5M8HTKH.BR0000PE * 
 *                  dw_dw.ACCOUNT       				  A5M8HTKH.BR0000PF * 
 * Target Table:    Join - work.W70Y6A6C                  A5M8HTKH.BR0000PG * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014R);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W70Y6A6C;
quit;

proc sql;
   create view work.W70Y6A6C as
   select
      WIM23GQ.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      WIM23GQ.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      WIM23GQ.account_id length = 20   
         label = 'Account number / Credit number / Loan number',
      WIM23GQ.ead_amount length = 8   
         format = 15.2
         label = 'Exposure at default amount on balance sheet',
      WIM23GQ.ead_amount_obs length = 8   
         format = 15.2
         label = 'Exposure at default amount off balance sheet',
      WIM23GQ.credit_amount length = 8   
         format = 15.2
         label = 'credit balance',
      WIM23GQ.conversion_factor_type length = 1   
         label = 'On balance exposure type (conversion_factor...)',
      WIM23GQ.conversion_factor_pct length = 8   
         format = 10.7
         label = 'Exposure percentage on balance sheet (conversion_factor...)',
      WIM23GQ.credit_amount_obs length = 8   
         format = 15.2
         label = 'Available credit amount. The amount that has not been withdrawn of total credit amount.',
      WIM23GQ.conversion_factor_type_obs length = 1   
         label = 'Off balance exposure type (conversion_factor...)',
      WIM23GQ.conversion_factor_pct_obs length = 8   
         format = 10.7
         label = 'Off balance exposure percentage (conversion_factor...)',
      WIM23GQ.sm_amount length = 8   
         format = 15.2
         label = 'On balance sheet S-method exposure amount',
      WIM23GQ.sm_amount_obs length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      WIM23GQ.irb_amount length = 8   
         format = 15.2
         label = 'On balance sheet IRB exposure amount',
      WIM23GQ.irb_amount_obs length = 8   
         format = 15.2
         label = 'Off balance sheet IRB exposure amount.',
      WIM23GQ.credit_risk_type length = 1   
         label = 'Credit risk type',
      WIM23GQ.risk_weighted_asset_amount length = 8   
         format = 15.2
         label = '(IRB) risk weighted asset amount.',
      WIM23GQ.risk_weight_pct length = 8   
         format = 10.7
         label = '(IRB) risk weight percentage',
      WIM23GQ.expected_loss_amount length = 8   
         format = 15.2
         label = '(IRB) Expected loss amount',
      WIM23GQ.sm_exposure_class length = 3   
         label = 'S-method exposure class',
      WIM23GQ.irb_customer_group length = 1   
         label = 'IRB customer group: R=retail, C=corporate',
      WIM23GQ.sm_originating_exposure_class length = 3   
         label = 'Originating exposure class for S-method exposure class 10',
      WIM23GQ.irb_exposure_class length = 3   
         format = 2.
         label = 'IRB exposure class',
      WIM23GQ.pd_class_pct length = 8   
         format = 10.7
         label = 'Probability default class percentage',
      WIM23GQ.pd_class_number length = 3   
         format = 2.
         label = 'Probability default class number',
      WIM23GQ.lgd_class_pct length = 8   
         format = 10.7
         label = 'Loss given default class percentage',
      WIM23GQ.lgd_class_number length = 3   
         format = 2.
         label = 'Loss given default class number',
      WIM23GQ.nbr_of_counterparties length = 3   
         format = 3.
         label = 'Number of counterparties',
      WIM23GQ.company_housing_30_amount length = 8   
         format = 15.2
         label = 'Company secured by real estate (LGD 30% rule)',
      WIM23GQ.crm_amount length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      WIM23GQ.housing_collateral_amount length = 8   
         format = 15.2
         label = 'Secured by real estate amount',
      WIM23GQ.other_collateral_amount length = 8   
         format = 15.2
         label = 'None secured by real estate amount',
      WIM23GQ.maturity length = 4   
         format = 5.
         label = 'Maturity - Remaining credit repayment time in days.',
      WIM23GQ.calculated_ead length = 8   
         format = 15.2
         label = 'Exposure at default amount where interest is included.',
      WIM23GQ.supporting_factor_class_number length = 3   
         format = 1.
         label = 'Supporting factor class number',
      WIM23GQ.currency length = 3   
         label = 'Currency',
      WIM23GQ.bank_group_currency length = 3   
         label = 'Bank group currency',
      WIM23GQ.exchange_rate length = 8   
         format = 10.6
         label = 'Exchange rate used for converting amount columns',
      WIM23GQ.country_code length = 2   
         label = 'Country code. FI = ÅAB Finland, SE = ÅAB Sweden',
      WIM23GQ.impairment_losses_amount length = 8   
         format = 15.2
         label = 'Impairment (write-down) amount',
      WIM23GQ.counterparty_risk_type length = 1   
         label = 'Counterparty risk type',
      WIM23GQ.source_system_cd length = 3   
         label = 'Data source system',
      WIM23GQ.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      WIM23GQ.loaded_dt length = 8   
         format = DATETIME20.
         label = 'Load timestamp (date & time)',
      W70XYLMX.owner_ssn_id as customer_ssn_id length = 20   
         label = 'Social Sec.number / Org.number. Account owner',
      WIM23GQ.supporting_factor_pct length = 8   
         format = 10.7
         label = 'supporting factor',
      W70XYLMX.owner_ssn_id length = 20   
         label = 'Social Sec.number / Org.number. Account owner'
   from
      work.dw_dw.BASEL_IRB as BASEL_IRB left join 
      work.dw_dw.ACCOUNT as ACCOUNT
         on
         (
            BASEL_IRB.information_date = ACCOUNT.information_date
            and BASEL_IRB.bank_id = ACCOUNT.bank_id
            and BASEL_IRB.account_id = ACCOUNT.account_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU00014S * 
 * Transform:       Extract                                                 * 
 * Description:     New calculated column added, rest 1:1                   * 
 *                                                                          * 
 * Source Table:    Join - work.W70Y6A6C                  A5M8HTKH.BR0000PG * 
 * Target Table:    Extract - work.W25FCJ64               A5M8HTKH.BR0000PH * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014S);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W70Y6A6C); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W25FCJ64;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W25FCJ64 as
      select
         information_date,
         bank_id,
         account_id,
         ead_amount,
         ead_amount_obs,
         credit_amount,
         conversion_factor_type,
         conversion_factor_pct,
         credit_amount_obs,
         conversion_factor_type_obs,
         conversion_factor_pct_obs,
         sm_amount,
         sm_amount_obs,
         irb_amount,
         irb_amount_obs,
         credit_risk_type,
         risk_weighted_asset_amount,
         risk_weight_pct,
         expected_loss_amount,
         sm_exposure_class,
         irb_customer_group,
         sm_originating_exposure_class,
         irb_exposure_class,
         pd_class_pct,
         pd_class_number,
         lgd_class_pct,
         lgd_class_number,
         nbr_of_counterparties,
         company_housing_30_amount,
         crm_amount,
         housing_collateral_amount,
         other_collateral_amount,
         maturity,
         calculated_ead,
         supporting_factor_class_number,
         currency,
         bank_group_currency,
         exchange_rate,
         country_code,
         impairment_losses_amount,
         (case when supporting_factor_class_number=1 
            then (risk_weighted_asset_amount * supporting_factor_pct) else 
            (risk_weighted_asset_amount) end) as irb_risk_exposure_amount_sf length = 8
            format = 15.2,
         counterparty_risk_type,
         source_system_cd,
         extracted_dt,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)',
         customer_ssn_id,
         supporting_factor_pct
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W25FCJ64;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            Conditional Start                     A5M8HTKH.BU00014T * 
 * Transform:       Conditional Start                                       * 
 * Description:                                                             * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014T);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%macro etls_conditionW8LAHBUL;
   %local etls_conditionTrue;
   %let etls_conditionTrue = %eval( %sysfunc(EXIST(mco_dm.BASEL_IRB))  ^= 1);
   %if (&etls_conditionTrue=0) %then
   %do;
      %put ETLS_DIAG: Condition flow did NOT execute, condition was  %sysfunc(EXIST(mco_dm.BASEL_IRB))  ^= 1;
      %goto exitetls_conditionW8LAHBUL;
   %end;
   %else
   %do;
      %put ETLS_DIAG: Condition flow did execute, condition was  %sysfunc(EXIST(mco_dm.BASEL_IRB))  ^= 1;
   %end;
/*==========================================================================* 
 * Step:            Table Loader                          A5M8HTKH.BU00014U * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W25FCJ64               A5M8HTKH.BR0000PH * 
 * Target Table:    mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014U);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W25FCJ64); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: AppendToExisting - InsertSQL
   Constraint and index action selections: 'ASIS','ASIS','INIT','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = %nrquote(where=(1=0));
   
   /*---- Map the columns  ----*/ 
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete W2Z4SQL;
   quit;
   
   data _null_;
      put "NOTE: The following column(s) do not have a column mapping, so the"
           " value(s) will be set to missing: bank_id, account_id, ead_amount,"
           " ead_amount_obs, credit_amount,    conversion_factor_type,"
           " conversion_factor_pct, credit_amount_obs,   "
           " conversion_factor_type_obs, conversion_factor_pct_obs, sm_amount,  "
           "  sm_amount_obs, irb_amount, irb_amount_obs, credit_risk_type,   "
           " risk_weighted_asset_amount, risk_weight_pct, expected_loss_amount, "
           "   sm_exposure_class, irb_customer_group,"
           " sm_originating_exposure_class,    irb_exposure_class, pd_class_pct,"
           " pd_class_number, lgd_class_pct,    lgd_class_number,"
           " nbr_of_counterparties, company_housing_30_amount,    crm_amount,"
           " housing_collateral_amount, other_collateral_amount, maturity,   "
           " calculated_ead, supporting_factor_class_number, currency,   "
           " bank_group_currency, exchange_rate, country_code,"
           " impairment_losses_amount,    irb_risk_exposure_amount_sf,"
           " counterparty_risk_type, source_system_cd,    extracted_dt,"
           " loaded_dt, customer_ssn_id, new_default_flg,   "
           " account_number_official, ecl_amount, stage_cd";
   run;
   
   %put %str(NOTE: Mapping columns ...);
   proc sql;
      create view work.W2Z4SQL as
         select
            information_date,
            "" as bank_id length = 1,
            "" as account_id length = 20,
            . as ead_amount length = 8
               format = 15.2,
            . as ead_amount_obs length = 8
               format = 15.2,
            . as credit_amount length = 8
               format = 15.2,
            "" as conversion_factor_type length = 1,
            . as conversion_factor_pct length = 8
               format = 10.7,
            . as credit_amount_obs length = 8
               format = 15.2,
            "" as conversion_factor_type_obs length = 1,
            . as conversion_factor_pct_obs length = 8
               format = 10.7,
            . as sm_amount length = 8
               format = 15.2,
            . as sm_amount_obs length = 8
               format = 15.2,
            . as irb_amount length = 8
               format = 15.2,
            . as irb_amount_obs length = 8
               format = 15.2,
            "" as credit_risk_type length = 1,
            . as risk_weighted_asset_amount length = 8
               format = 15.2,
            . as risk_weight_pct length = 8
               format = 10.7,
            . as expected_loss_amount length = 8
               format = 15.2,
            "" as sm_exposure_class length = 3,
            "" as irb_customer_group length = 1,
            "" as sm_originating_exposure_class length = 3,
            . as irb_exposure_class length = 3
               format = 2.,
            . as pd_class_pct length = 8
               format = 10.7,
            . as pd_class_number length = 3
               format = 2.,
            . as lgd_class_pct length = 8
               format = 10.7,
            . as lgd_class_number length = 3
               format = 2.,
            . as nbr_of_counterparties length = 3
               format = 3.,
            . as company_housing_30_amount length = 8
               format = 15.2,
            . as crm_amount length = 8
               format = 15.2,
            . as housing_collateral_amount length = 8
               format = 15.2,
            . as other_collateral_amount length = 8
               format = 15.2,
            . as maturity length = 4
               format = 5.,
            . as calculated_ead length = 8
               format = 15.2,
            . as supporting_factor_class_number length = 3
               format = 1.,
            "" as currency length = 3,
            "" as bank_group_currency length = 3,
            . as exchange_rate length = 8
               format = 10.6,
            "" as country_code length = 2,
            . as impairment_losses_amount length = 8
               format = 15.2,
            . as irb_risk_exposure_amount_sf length = 8
               format = 15.2,
            "" as counterparty_risk_type length = 1,
            "" as source_system_cd length = 3,
            . as extracted_dt length = 8
               format = DATETIME20.,
            . as loaded_dt length = 8
               format = DATETIME20.,
            "" as customer_ssn_id length = 20,
            . as new_default_flg length = 3
               format = 1.,
            "" as account_number_official length = 20,
            . as ecl_amount length = 8
               format = 15.2,
            . as stage_cd length = 3
               format = 6.,
            supporting_factor_pct
      from &etls_lastTable
         (&etls_tableOptions)
      ;
   quit;
   
   %let SYSLAST = work.W2Z4SQL;
   
   %let etls_lastTable = &SYSLAST; 
   %let etls_tableOptions = ; 
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(mco_dm.BASEL_IRB, DATA)) or 
         %sysfunc(exist(mco_dm.BASEL_IRB, VIEW))); 
   
   /*---- Create a new table  ----*/ 
   %if (&etls_tableExist eq 0) %then 
   %do;  /* if table does not exist  */ 
   
      %put %str(NOTE: Creating table ...);
      
      data mco_dm.BASEL_IRB
              (&altercommand.);
         attrib information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date of the record'; 
         attrib bank_id length = $1
            label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden'; 
         attrib account_id length = $20
            label = 'Account number / Credit number / Loan number'; 
         attrib ead_amount length = 8
            format = 15.2
            label = 'Exposure at default amount on balance sheet'; 
         attrib ead_amount_obs length = 8
            format = 15.2
            label = 'Exposure at default amount off balance sheet'; 
         attrib credit_amount length = 8
            format = 15.2
            label = 'credit balance'; 
         attrib conversion_factor_type length = $1
            label = 'On balance exposure type (conversion_factor...)'; 
         attrib conversion_factor_pct length = 8
            format = 10.7
            label = 'Exposure percentage on balance sheet (conversion_factor...)'; 
         attrib credit_amount_obs length = 8
            format = 15.2
            label = 'Available credit amount. The amount that has not been withdrawn of total credit amount.'; 
         attrib conversion_factor_type_obs length = $1
            label = 'Off balance exposure type (conversion_factor...)'; 
         attrib conversion_factor_pct_obs length = 8
            format = 10.7
            label = 'Off balance exposure percentage (conversion_factor...)'; 
         attrib sm_amount length = 8
            format = 15.2
            label = 'On balance sheet S-method exposure amount'; 
         attrib sm_amount_obs length = 8
            format = 15.2
            label = 'Off balance sheet S-method exposure amount'; 
         attrib irb_amount length = 8
            format = 15.2
            label = 'On balance sheet IRB exposure amount'; 
         attrib irb_amount_obs length = 8
            format = 15.2
            label = 'Off balance sheet IRB exposure amount.'; 
         attrib credit_risk_type length = $1
            label = 'Credit risk type'; 
         attrib risk_weighted_asset_amount length = 8
            format = 15.2
            label = '(IRB) risk weighted asset amount.'; 
         attrib risk_weight_pct length = 8
            format = 10.7
            label = '(IRB) risk weight percentage'; 
         attrib expected_loss_amount length = 8
            format = 15.2
            label = '(IRB) Expected loss amount'; 
         attrib sm_exposure_class length = $3
            label = 'S-method exposure class'; 
         attrib irb_customer_group length = $1
            label = 'IRB customer group: R=retail, C=corporate'; 
         attrib sm_originating_exposure_class length = $3
            label = 'Originating exposure class for S-method exposure class 10'; 
         attrib irb_exposure_class length = 3
            format = 2.
            label = 'IRB exposure class'; 
         attrib pd_class_pct length = 8
            format = 10.7
            label = 'Probability default class percentage'; 
         attrib pd_class_number length = 3
            format = 2.
            label = 'Probability default class number'; 
         attrib lgd_class_pct length = 8
            format = 10.7
            label = 'Loss given default class percentage'; 
         attrib lgd_class_number length = 3
            format = 2.
            label = 'Loss given default class number'; 
         attrib nbr_of_counterparties length = 3
            format = 3.
            label = 'Number of counterparties'; 
         attrib company_housing_30_amount length = 8
            format = 15.2
            label = 'Company secured by real estate (LGD 30% rule)'; 
         attrib crm_amount length = 8
            format = 15.2
            label = 'Credit risk mitigation amount'; 
         attrib housing_collateral_amount length = 8
            format = 15.2
            label = 'Secured by real estate amount'; 
         attrib other_collateral_amount length = 8
            format = 15.2
            label = 'None secured by real estate amount'; 
         attrib maturity length = 4
            format = 5.
            label = 'Maturity - Remaining credit repayment time in days.'; 
         attrib calculated_ead length = 8
            format = 15.2
            label = 'Exposure at default amount where interest is included.'; 
         attrib supporting_factor_class_number length = 3
            format = 1.
            label = 'Supporting factor class number'; 
         attrib currency length = $3
            label = 'Currency'; 
         attrib bank_group_currency length = $3
            label = 'Bank group currency'; 
         attrib exchange_rate length = 8
            format = 10.6
            label = 'Exchange rate used for converting amount columns'; 
         attrib country_code length = $2
            label = 'Country code. FI = ÅAB Finland, SE = ÅAB Sweden'; 
         attrib impairment_losses_amount length = 8
            format = 15.2
            label = 'Impairment (write-down) amount'; 
         attrib irb_risk_exposure_amount_sf length = 8
            format = 15.2
            label = 'IRB risk exposure amt_sf'; 
         attrib counterparty_risk_type length = $1
            label = 'Counterparty risk type'; 
         attrib source_system_cd length = $3
            label = 'Data source system'; 
         attrib extracted_dt length = 8
            format = DATETIME20.
            label = 'Extract timestamp (date & time)'; 
         attrib loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'; 
         attrib customer_ssn_id length = $20
            label = 'Social security / organisation number'; 
         attrib new_default_flg length = 3
            format = 1.; 
         attrib account_number_official length = $20
            label = 'Account Number, official (In Finland same as account_id, in Sweden the official Swedish account number)'; 
         attrib ecl_amount length = 8
            format = 15.2
            label = 'ECL amount'; 
         attrib stage_cd length = 3
            format = 6.
            label = 'Stage, eg. 1, 2, 3'; 
         attrib supporting_factor_pct length = 8
            format = 10.7
            label = 'supporting factor'; 
         call missing(of _all_);
         stop;
      run;
      
      %rcSet(&syserr); 
      
      /*---- Create the indexes for a table  ----*/ 
      %put %str(NOTE: Creating indexes ...);
      proc datasets lib = mco_dm nolist; 
         modify BASEL_IRB(&altercommand. ); 
            index create primary_index = (information_date bank_id account_id)
               / unique;
      quit; 
      
      %rcSet(&syserr); 
      
   %end;  /* if table does not exist  */ 
   
   proc sql ; 
   
      /* insert new records into the master table  */ 
      insert into mco_dm.BASEL_IRB 
         (ALTER=&alterpass, 
           information_date, bank_id, account_id, ead_amount, ead_amount_obs, 
             credit_amount, conversion_factor_type, conversion_factor_pct, 
             credit_amount_obs, conversion_factor_type_obs, conversion_factor_pct_obs, 
             sm_amount, sm_amount_obs, irb_amount, irb_amount_obs, credit_risk_type, 
             risk_weighted_asset_amount, risk_weight_pct, expected_loss_amount, 
             sm_exposure_class, irb_customer_group, sm_originating_exposure_class, 
             irb_exposure_class, pd_class_pct, pd_class_number, lgd_class_pct, 
             lgd_class_number, nbr_of_counterparties, company_housing_30_amount, 
             crm_amount, housing_collateral_amount, other_collateral_amount, maturity, 
             calculated_ead, supporting_factor_class_number, currency, 
             bank_group_currency, exchange_rate, country_code, impairment_losses_amount, 
             irb_risk_exposure_amount_sf, counterparty_risk_type, source_system_cd, 
             extracted_dt, loaded_dt, customer_ssn_id, new_default_flg, 
             account_number_official, ecl_amount, stage_cd, supporting_factor_pct)
         select 
                   information_date, bank_id, account_id, ead_amount, ead_amount_obs, 
             credit_amount, conversion_factor_type, conversion_factor_pct, 
             credit_amount_obs, conversion_factor_type_obs, conversion_factor_pct_obs, 
             sm_amount, sm_amount_obs, irb_amount, irb_amount_obs, credit_risk_type, 
             risk_weighted_asset_amount, risk_weight_pct, expected_loss_amount, 
             sm_exposure_class, irb_customer_group, sm_originating_exposure_class, 
             irb_exposure_class, pd_class_pct, pd_class_number, lgd_class_pct, 
             lgd_class_number, nbr_of_counterparties, company_housing_30_amount, 
             crm_amount, housing_collateral_amount, other_collateral_amount, maturity, 
             calculated_ead, supporting_factor_class_number, currency, 
             bank_group_currency, exchange_rate, country_code, impairment_losses_amount, 
             irb_risk_exposure_amount_sf, counterparty_risk_type, source_system_cd, 
             extracted_dt, loaded_dt, customer_ssn_id, new_default_flg, 
             account_number_official, ecl_amount, stage_cd, supporting_factor_pct
            from &etls_lastTable 
      ; 
      
   quit;
   
   %global etls_sql_pushDown;
   %let etls_sql_pushDown = &sys_sql_ip_all;
   
   %rcSet(&sqlrc); 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete W2Z4SQL;
   quit;
   
%mend etls_loader;
%etls_loader;



/** Step end Table Loader **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU00014V * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 * Target Table:    mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014V);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.BASEL_IRB); 

%let _INPUT_count = 1; 
%let _INPUT = mco_dm.BASEL_IRB;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.BASEL_IRB%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = mco_dm.BASEL_IRB;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.BASEL_IRB%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mco_dm.BASEL_IRB;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.BASEL_IRB%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;

%let _OUTPUT0 = mco_dm.BASEL_IRB;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.BASEL_IRB%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mco_dm nolist; 
   modify BASEL_IRB(&altercommand. ); 
      index create primary_index = (information_date bank_id account_id)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%exitetls_conditionW8LAHBUL:
%mend etls_conditionW8LAHBUL;

%etls_conditionW8LAHBUL;


/** Step end Conditional Start **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU00014X * 
 * Transform:       Extract                                                 * 
 * Description:     Information date = Last 3rd month                       * 
 *                                                                          * 
 * Source Table:    mco_dm.BASEL_IRB_H                    A5M8HTKH.BB0000UU * 
 * Target Table:    Extract - work.W8AJ2XUM               A5M8HTKH.BR0000PI * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014X);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.BASEL_IRB_H); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W8AJ2XUM;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W8AJ2XUM as
      select
         information_date,
         bank_id,
         account_id,
         pd_class_number,
         (0) as new_default_flg length = 3
            format = 1.
   from &SYSLAST
      where information_date=intnx("month",&active_date.,-3,"E")
   ;
quit;

%let SYSLAST = work.W8AJ2XUM;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU00014Y * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W8AJ2XUM               A5M8HTKH.BR0000PI * 
 * Target Table:    Extract - work.W8AJ3W5R               A5M8HTKH.BR0000PJ * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014Y);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W8AJ2XUM); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W8AJ3W5R;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W8AJ3W5R as
      select
         information_date,
         bank_id,
         account_id,
         pd_class_number,
         new_default_flg
   from &SYSLAST
      where pd_class_number=11
   ;
quit;

%let SYSLAST = work.W8AJ3W5R;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            Sort                                  A5M8HTKH.BU00014Z * 
 * Transform:       Sort                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W8AJ3W5R               A5M8HTKH.BR0000PJ * 
 * Target Table:    Sort - work.W8AJ6598                  A5M8HTKH.BR0000PK * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU00014Z);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W8AJ3W5R); 

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W8AJ6598;
quit;

proc sort data = &SYSLAST 
   out = work.W8AJ6598
      NODUPKEY ; 
   by
      account_id
   ;
run; 

%rcSet(&syserr); 



/** Step end Sort **/

/*==========================================================================* 
 * Step:            Join                                  A5M8HTKH.BU000150 * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Extract - work.W25FCJ64               A5M8HTKH.BR0000PH * 
 *                  Sort - work.W8AJ6598                  A5M8HTKH.BR0000PK * 
 * Target Table:    Join - work.W8AILI9S                  A5M8HTKH.BR0000PL * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000150);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W8AILI9S;
quit;

proc sql;
   create view work.W8AILI9S as
   select
      W25FCJ64.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      W25FCJ64.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      W25FCJ64.account_id length = 20   
         label = 'Account number / Credit number / Loan number',
      W25FCJ64.ead_amount length = 8   
         format = 15.2
         label = 'Exposure at default amount on balance sheet',
      W25FCJ64.ead_amount_obs length = 8   
         format = 15.2
         label = 'Exposure at default amount off balance sheet',
      W25FCJ64.credit_amount length = 8   
         format = 15.2
         label = 'credit balance',
      W25FCJ64.conversion_factor_type length = 1   
         label = 'On balance exposure type (conversion_factor...)',
      W25FCJ64.conversion_factor_pct length = 8   
         format = 10.7
         label = 'Exposure percentage on balance sheet (conversion_factor...)',
      W25FCJ64.credit_amount_obs length = 8   
         format = 15.2
         label = 'Available credit amount. The amount that has not been withdrawn of total credit amount.',
      W25FCJ64.conversion_factor_type_obs length = 1   
         label = 'Off balance exposure type (conversion_factor...)',
      W25FCJ64.conversion_factor_pct_obs length = 8   
         format = 10.7
         label = 'Off balance exposure percentage (conversion_factor...)',
      W25FCJ64.sm_amount length = 8   
         format = 15.2
         label = 'On balance sheet S-method exposure amount',
      W25FCJ64.sm_amount_obs length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      W25FCJ64.irb_amount length = 8   
         format = 15.2
         label = 'On balance sheet IRB exposure amount',
      W25FCJ64.irb_amount_obs length = 8   
         format = 15.2
         label = 'Off balance sheet IRB exposure amount.',
      W25FCJ64.credit_risk_type length = 1   
         label = 'Credit risk type',
      W25FCJ64.risk_weighted_asset_amount length = 8   
         format = 15.2
         label = '(IRB) risk weighted asset amount.',
      W25FCJ64.risk_weight_pct length = 8   
         format = 10.7
         label = '(IRB) risk weight percentage',
      W25FCJ64.expected_loss_amount length = 8   
         format = 15.2
         label = '(IRB) Expected loss amount',
      W25FCJ64.sm_exposure_class length = 3   
         label = 'S-method exposure class',
      W25FCJ64.irb_customer_group length = 1   
         label = 'IRB customer group: R=retail, C=corporate',
      W25FCJ64.sm_originating_exposure_class length = 3   
         label = 'Originating exposure class for S-method exposure class 10',
      W25FCJ64.irb_exposure_class length = 3   
         format = 2.
         label = 'IRB exposure class',
      W25FCJ64.pd_class_pct length = 8   
         format = 10.7
         label = 'Probability default class percentage',
      W25FCJ64.pd_class_number length = 3   
         format = 2.
         label = 'Probability default class number',
      W25FCJ64.lgd_class_pct length = 8   
         format = 10.7
         label = 'Loss given default class percentage',
      W25FCJ64.lgd_class_number length = 3   
         format = 2.
         label = 'Loss given default class number',
      W25FCJ64.nbr_of_counterparties length = 3   
         format = 3.
         label = 'Number of counterparties',
      W25FCJ64.company_housing_30_amount length = 8   
         format = 15.2
         label = 'Company secured by real estate (LGD 30% rule)',
      W25FCJ64.crm_amount length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      W25FCJ64.housing_collateral_amount length = 8   
         format = 15.2
         label = 'Secured by real estate amount',
      W25FCJ64.other_collateral_amount length = 8   
         format = 15.2
         label = 'None secured by real estate amount',
      W25FCJ64.maturity length = 4   
         format = 5.
         label = 'Maturity - Remaining credit repayment time in days.',
      W25FCJ64.calculated_ead length = 8   
         format = 15.2
         label = 'Exposure at default amount where interest is included.',
      W25FCJ64.supporting_factor_class_number length = 3   
         format = 1.
         label = 'Supporting factor class number',
      W25FCJ64.currency length = 3   
         label = 'Currency',
      W25FCJ64.bank_group_currency length = 3   
         label = 'Bank group currency',
      W25FCJ64.exchange_rate length = 8   
         format = 10.6
         label = 'Exchange rate used for converting amount columns',
      W25FCJ64.country_code length = 2   
         label = 'Country code. FI = ÅAB Finland, SE = ÅAB Sweden',
      W25FCJ64.impairment_losses_amount length = 8   
         format = 15.2
         label = 'Impairment (write-down) amount',
      W25FCJ64.irb_risk_exposure_amount_sf length = 8   
         format = 15.2,
      W25FCJ64.counterparty_risk_type length = 1   
         label = 'Counterparty risk type',
      W25FCJ64.source_system_cd length = 3   
         label = 'Data source system',
      W25FCJ64.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      W25FCJ64.loaded_dt length = 8   
         format = DATETIME20.
         label = 'Load timestamp (date & time)',
      W25FCJ64.customer_ssn_id length = 20   
         label = 'Social Sec.number / Org.number. Account owner',
      W8AJ6598.new_default_flg length = 3   
         format = 1.,
      W25FCJ64.supporting_factor_pct length = 8   
         format = 10.7
         label = 'supporting factor'
   from
      work.W25FCJ64 as W25FCJ64 left join 
      work.W8AJ6598 as W8AJ6598
         on
         (
            W25FCJ64.account_id = W8AJ6598.account_id
            and W25FCJ64.bank_id = W8AJ6598.bank_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU000151 * 
 * Transform:       Extract                                                 * 
 * Description:     New default flag expression added                       * 
 *                                                                          * 
 * Source Table:    Join - work.W8AILI9S                  A5M8HTKH.BR0000PL * 
 * Target Table:    Extract - work.W8AINLDC               A5M8HTKH.BR0000PM * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000151);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W8AILI9S); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W8AINLDC;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W8AINLDC as
      select
         information_date,
         bank_id,
         account_id,
         ead_amount,
         ead_amount_obs,
         credit_amount,
         conversion_factor_type,
         conversion_factor_pct,
         credit_amount_obs,
         conversion_factor_type_obs,
         conversion_factor_pct_obs,
         sm_amount,
         sm_amount_obs,
         irb_amount,
         irb_amount_obs,
         credit_risk_type,
         risk_weighted_asset_amount,
         risk_weight_pct,
         expected_loss_amount,
         sm_exposure_class,
         irb_customer_group,
         sm_originating_exposure_class,
         irb_exposure_class,
         pd_class_pct,
         pd_class_number,
         lgd_class_pct,
         lgd_class_number,
         nbr_of_counterparties,
         company_housing_30_amount,
         crm_amount,
         housing_collateral_amount,
         other_collateral_amount,
         maturity,
         calculated_ead,
         supporting_factor_class_number,
         currency,
         bank_group_currency,
         exchange_rate,
         country_code,
         impairment_losses_amount,
         irb_risk_exposure_amount_sf,
         counterparty_risk_type,
         source_system_cd,
         extracted_dt,
         loaded_dt,
         customer_ssn_id,
         (case when new_default_flg = . and pd_class_number=11  then 1 else 0 end) as new_default_flg length = 3
            format = 1.,
         supporting_factor_pct
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W8AINLDC;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            shadow                                A5M8HTKH.BU000152 * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    mco_dm.DET_COREP_ECL                  A5M8HTKH.BB0000VP * 
 * Target Table:    shadow_DET_COREP_ECL -                A5M8HTKH.BR0000PN * 
 *                   work.DET_COREP_ECL                                     * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000152);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mco_dm.DET_COREP_ECL); 

%let _INPUT_count = 1; 
%let _INPUT = mco_dm.DET_COREP_ECL;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(&altercommand.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_COREP_ECL%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = mco_dm.DET_COREP_ECL;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(&altercommand.);
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.DET_COREP_ECL%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.DET_COREP_ECL;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_DET_COREP_ECL_A5M8HTKH.BR0000PN%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date counterparty_name customer_id deal_id account_id 
        account_number_official ecl_amount stage_cd type loaded_dt;

%let _OUTPUT0 = work.DET_COREP_ECL;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_DET_COREP_ECL_A5M8HTKH.BR0000PN%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date counterparty_name customer_id deal_id account_id 
        account_number_official ecl_amount stage_cd type loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete DET_COREP_ECL;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date counterparty_name customer_id deal_id account_id 
        account_number_official ecl_amount stage_cd type loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date counterparty_name customer_id deal_id account_id 
        account_number_official ecl_amount stage_cd type loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/** Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5M8HTKH.BU000153 * 
 * Transform:       Join                                                    * 
 * Description:     Left join 3 columns from mco_dm.DET_COREP_ECL           * 
 *                                                                          * 
 * Source Tables:   Extract - work.W8AINLDC               A5M8HTKH.BR0000PM * 
 *                  shadow_DET_COREP_ECL -                A5M8HTKH.BR0000PN * 
 *                   work.DET_COREP_ECL                                     * 
 * Target Table:    Join - work.W9MDQRX2                  A5M8HTKH.BR0000PO * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000153);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W9MDQRX2;
quit;

proc sql;
   create view work.W9MDQRX2 as
   select
      W8AINLDC.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      W8AINLDC.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      W8AINLDC.account_id length = 20   
         label = 'Account number / Credit number / Loan number',
      W8AINLDC.ead_amount length = 8   
         format = 15.2
         label = 'Exposure at default amount on balance sheet',
      W8AINLDC.ead_amount_obs length = 8   
         format = 15.2
         label = 'Exposure at default amount off balance sheet',
      W8AINLDC.credit_amount length = 8   
         format = 15.2
         label = 'credit balance',
      W8AINLDC.conversion_factor_type length = 1   
         label = 'On balance exposure type (conversion_factor...)',
      W8AINLDC.conversion_factor_pct length = 8   
         format = 10.7
         label = 'Exposure percentage on balance sheet (conversion_factor...)',
      W8AINLDC.credit_amount_obs length = 8   
         format = 15.2
         label = 'Available credit amount. The amount that has not been withdrawn of total credit amount.',
      W8AINLDC.conversion_factor_type_obs length = 1   
         label = 'Off balance exposure type (conversion_factor...)',
      W8AINLDC.conversion_factor_pct_obs length = 8   
         format = 10.7
         label = 'Off balance exposure percentage (conversion_factor...)',
      W8AINLDC.sm_amount length = 8   
         format = 15.2
         label = 'On balance sheet S-method exposure amount',
      W8AINLDC.sm_amount_obs length = 8   
         format = 15.2
         label = 'Off balance sheet S-method exposure amount',
      W8AINLDC.irb_amount length = 8   
         format = 15.2
         label = 'On balance sheet IRB exposure amount',
      W8AINLDC.irb_amount_obs length = 8   
         format = 15.2
         label = 'Off balance sheet IRB exposure amount.',
      W8AINLDC.credit_risk_type length = 1   
         label = 'Credit risk type',
      W8AINLDC.risk_weighted_asset_amount length = 8   
         format = 15.2
         label = '(IRB) risk weighted asset amount.',
      W8AINLDC.risk_weight_pct length = 8   
         format = 10.7
         label = '(IRB) risk weight percentage',
      W8AINLDC.expected_loss_amount length = 8   
         format = 15.2
         label = '(IRB) Expected loss amount',
      W8AINLDC.sm_exposure_class length = 3   
         label = 'S-method exposure class',
      W8AINLDC.irb_customer_group length = 1   
         label = 'IRB customer group: R=retail, C=corporate',
      W8AINLDC.sm_originating_exposure_class length = 3   
         label = 'Originating exposure class for S-method exposure class 10',
      W8AINLDC.irb_exposure_class length = 3   
         format = 2.
         label = 'IRB exposure class',
      W8AINLDC.pd_class_pct length = 8   
         format = 10.7
         label = 'Probability default class percentage',
      W8AINLDC.pd_class_number length = 3   
         format = 2.
         label = 'Probability default class number',
      W8AINLDC.lgd_class_pct length = 8   
         format = 10.7
         label = 'Loss given default class percentage',
      W8AINLDC.lgd_class_number length = 3   
         format = 2.
         label = 'Loss given default class number',
      W8AINLDC.nbr_of_counterparties length = 3   
         format = 3.
         label = 'Number of counterparties',
      W8AINLDC.company_housing_30_amount length = 8   
         format = 15.2
         label = 'Company secured by real estate (LGD 30% rule)',
      W8AINLDC.crm_amount length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      W8AINLDC.housing_collateral_amount length = 8   
         format = 15.2
         label = 'Secured by real estate amount',
      W8AINLDC.other_collateral_amount length = 8   
         format = 15.2
         label = 'None secured by real estate amount',
      W8AINLDC.maturity length = 4   
         format = 5.
         label = 'Maturity - Remaining credit repayment time in days.',
      W8AINLDC.calculated_ead length = 8   
         format = 15.2
         label = 'Exposure at default amount where interest is included.',
      W8AINLDC.supporting_factor_class_number length = 3   
         format = 1.
         label = 'Supporting factor class number',
      W8AINLDC.currency length = 3   
         label = 'Currency',
      W8AINLDC.bank_group_currency length = 3   
         label = 'Bank group currency',
      W8AINLDC.exchange_rate length = 8   
         format = 10.6
         label = 'Exchange rate used for converting amount columns',
      W8AINLDC.country_code length = 2   
         label = 'Country code. FI = ÅAB Finland, SE = ÅAB Sweden',
      W8AINLDC.impairment_losses_amount length = 8   
         format = 15.2
         label = 'Impairment (write-down) amount',
      W8AINLDC.irb_risk_exposure_amount_sf length = 8   
         format = 15.2,
      W8AINLDC.counterparty_risk_type length = 1   
         label = 'Counterparty risk type',
      W8AINLDC.source_system_cd length = 3   
         label = 'Data source system',
      W8AINLDC.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      W8AINLDC.loaded_dt length = 8   
         format = DATETIME20.
         label = 'Load timestamp (date & time)',
      W8AINLDC.customer_ssn_id length = 20   
         label = 'Social Sec.number / Org.number. Account owner',
      W8AINLDC.new_default_flg length = 3   
         format = 1.,
      DET_COREP_ECL.account_number_official length = 20   
         label = 'Account Number, official (In Finland same as account_id, in Sweden the official Swedish account number)',
      DET_COREP_ECL.ecl_amount length = 8   
         format = 15.2
         label = 'ECL amount',
      DET_COREP_ECL.stage_cd length = 3   
         format = 6.
         label = 'Stage, eg. 1, 2, 3',
      W8AINLDC.supporting_factor_pct length = 8   
         format = 10.7
         label = 'supporting factor'
   from
      work.W8AINLDC as W8AINLDC left join 
      work.DET_COREP_ECL as DET_COREP_ECL
         on
         (
            W8AINLDC.information_date = DET_COREP_ECL.information_date
            and W8AINLDC.account_id = DET_COREP_ECL.account_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5M8HTKH.BU000154 * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W9MDQRX2                  A5M8HTKH.BR0000PO * 
 * Target Table:    Extract - work.W9MDUHDP               A5M8HTKH.BR0000PP * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000154);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W9MDQRX2); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W9MDUHDP;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W9MDUHDP as
      select
         information_date,
         bank_id,
         account_id,
         ead_amount,
         ead_amount_obs,
         credit_amount,
         conversion_factor_type,
         conversion_factor_pct,
         credit_amount_obs,
         conversion_factor_type_obs,
         conversion_factor_pct_obs,
         sm_amount,
         sm_amount_obs,
         irb_amount,
         irb_amount_obs,
         credit_risk_type,
         risk_weighted_asset_amount,
         risk_weight_pct,
         expected_loss_amount,
         sm_exposure_class,
         irb_customer_group,
         sm_originating_exposure_class,
         irb_exposure_class,
         pd_class_pct,
         pd_class_number,
         lgd_class_pct,
         lgd_class_number,
         nbr_of_counterparties,
         company_housing_30_amount,
         crm_amount,
         housing_collateral_amount,
         other_collateral_amount,
         maturity,
         calculated_ead,
         supporting_factor_class_number,
         currency,
         bank_group_currency,
         exchange_rate,
         country_code,
         impairment_losses_amount,
         irb_risk_exposure_amount_sf   
            label = 'IRB risk exposure amt_sf',
         counterparty_risk_type,
         source_system_cd,
         extracted_dt,
         loaded_dt,
         customer_ssn_id   
            label = 'Social security / organisation number',
         new_default_flg,
         account_number_official,
         ecl_amount,
         stage_cd,
         supporting_factor_pct
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W9MDUHDP;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/** Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5M8HTKH.BU000155 * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W9MDUHDP               A5M8HTKH.BR0000PP * 
 * Target Table:    mco_dm.BASEL_IRB                      A5M8HTKH.BB0000UO * 
 *==========================================================================*/ 

%let transformID = %quote(A5M8HTKH.BU000155);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W9MDUHDP); 

%let _INPUT_count = 1; 
%let _INPUT = work.W9MDUHDP;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5M8HTKH.BR0000PP%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W9MDUHDP;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5M8HTKH.BR0000PP%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mco_dm.BASEL_IRB;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.BASEL_IRB%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;

%let _OUTPUT0 = mco_dm.BASEL_IRB;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mco/data/dm/mco_dm.BASEL_IRB%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount irb_risk_exposure_amount_sf 
        counterparty_risk_type source_system_cd extracted_dt loaded_dt 
        customer_ssn_id new_default_flg account_number_official ecl_amount 
        stage_cd supporting_factor_pct;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mco_dm nolist; 
   modify BASEL_IRB(&altercommand. ); 
      index create primary_index = (information_date bank_id account_id)
         / unique;
quit; 

%rcSet(&syserr); 



/** Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

