/**************************************************************************** 
 * Job:             mel_dm.object                         A5ZNM6KG.BO0003O0 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Tables:   dw_dw.COLLATERAL_OBJECT               A5ZNM6KG.BG0003SG * 
 *                  dw_dw.CUSTODY_OBJECT                  A5ZNM6KG.BG0003SZ * 
 *                  dw_dw.DEPOSIT_OBJECT                  A5ZNM6KG.BG0003SH * 
 *                  dw_dw.GUARANTEE_OBJECT                A5ZNM6KG.BG0003TY * 
 *                  dw_dw.REAL_PROPERTY_OBJECT            A5ZNM6KG.BG0003SI * 
 *                  dw_dw.HOUSING_OBJECT                  A5ZNM6KG.BG0003SJ * 
 * Target Table:    mel_dm.OBJECT                         A5ZNM6KG.BG0003XP * 
 *                                                                          * 
 * Generated on:    Friday, January 12, 2018 4:18:16 PM EET                 * 
 * Generated by:    ani                                                     * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003O0);
%let etls_jobName = %nrquote(mel_dm.object);
%let etls_userID = %nrquote(ani);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract_1                             A5ZNM6KG.BS0003RF * 
 * Transform:       Extract                                                 * 
 * Description:     Extract_1                                               * 
 *                                                                          * 
 * Source Table:    dw_dw.COLLATERAL_OBJECT               A5ZNM6KG.BG0003SG * 
 * Target Table:    Extract - work.W_Collateral_object    A5ZNM6KG.BV000317 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RF);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.COLLATERAL_OBJECT); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W_Collateral_object;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W_Collateral_object as
      select
         information_date,
         bank_id,
         internal_object_id,
         object_type_cd,
         currency_cd,
         market_value_amt,
         residence_value_amt,
         collateral_loan_value_amt,
         valuation_date,
         index_market_value_amt,
         index_residence_market_value_amt,
         index_collateral_loan_value_amt,
         index_valuation_date,
         extracted_dt
   from &SYSLAST
      (ALTER=&alterpass)
   ;
quit;

%let SYSLAST = work.W_Collateral_object;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract_1 **/

/*==========================================================================* 
 * Step:            Extract_2                             A5ZNM6KG.BS0003RG * 
 * Transform:       Extract                                                 * 
 * Description:     Extract_2                                               * 
 *                                                                          * 
 * Source Table:    dw_dw.CUSTODY_OBJECT                  A5ZNM6KG.BG0003SZ * 
 * Target Table:    Extract -                             A5ZNM6KG.BV000318 * 
 *                   work.W_Custody_collateral_object                       * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RG);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.CUSTODY_OBJECT); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W_Custody_collateral_object;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W_Custody_collateral_object as
      select
         information_date,
         bank_id,
         internal_object_id,
         crm_value_amt,
         total_deposit_amt
   from &SYSLAST
      (ALTER=&alterpass)
   ;
quit;

%let SYSLAST = work.W_Custody_collateral_object;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract_2 **/

/*==========================================================================* 
 * Step:            Extract_3                             A5ZNM6KG.BS0003RH * 
 * Transform:       Extract                                                 * 
 * Description:     Extract_3                                               * 
 *                                                                          * 
 * Source Table:    dw_dw.DEPOSIT_OBJECT                  A5ZNM6KG.BG0003SH * 
 * Target Table:    Extract - work.W_Deposit_object       A5ZNM6KG.BV000319 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RH);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.DEPOSIT_OBJECT); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W_Deposit_object;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W_Deposit_object as
      select
         information_date,
         bank_id,
         internal_object_id,
         account_balance_amt,
         maximum_pledge_amt
   from &SYSLAST
      (ALTER=&alterpass)
   ;
quit;

%let SYSLAST = work.W_Deposit_object;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract_3 **/

/*==========================================================================* 
 * Step:            Extract_4                             A5ZNM6KG.BS0003RI * 
 * Transform:       Extract                                                 * 
 * Description:     Extract_4                                               * 
 *                                                                          * 
 * Source Table:    dw_dw.GUARANTEE_OBJECT                A5ZNM6KG.BG0003TY * 
 * Target Table:    Extract - work.W_Guarantee_object     A5ZNM6KG.BV00031A * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RI);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.GUARANTEE_OBJECT); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W_Guarantee_object;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W_Guarantee_object as
      select
         information_date,
         bank_id,
         internal_object_id,
         guarantors_cnt
   from &SYSLAST
      (ALTER=&alterpass)
   ;
quit;

%let SYSLAST = work.W_Guarantee_object;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract_4 **/

/*==========================================================================* 
 * Step:            Extract_5                             A5ZNM6KG.BS0003RJ * 
 * Transform:       Extract                                                 * 
 * Description:     Extract_5                                               * 
 *                                                                          * 
 * Source Table:    dw_dw.REAL_PROPERTY_OBJECT            A5ZNM6KG.BG0003SI * 
 * Target Table:    Extract - work.W_Real_property_object A5ZNM6KG.BV00031B * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RJ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.REAL_PROPERTY_OBJECT); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W_Real_property_object;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W_Real_property_object as
      select
         information_date,
         bank_id,
         internal_object_id,
         main_object_type_cd,
         main_property_id
   from &SYSLAST
      (ALTER=&alterpass)
   ;
quit;

%let SYSLAST = work.W_Real_property_object;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract_5 **/

/*==========================================================================* 
 * Step:            Extract_6                             A5ZNM6KG.BS0003RK * 
 * Transform:       Extract                                                 * 
 * Description:     Extract_6                                               * 
 *                                                                          * 
 * Source Table:    dw_dw.HOUSING_OBJECT                  A5ZNM6KG.BG0003SJ * 
 * Target Table:    Extract - work.W_Housing_object       A5ZNM6KG.BV00031C * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RK);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.HOUSING_OBJECT); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W_Housing_object;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W_Housing_object as
      select
         information_date,
         bank_id,
         internal_object_id,
         debt_share_amt
   from &SYSLAST
      (ALTER=&alterpass)
   ;
quit;

%let SYSLAST = work.W_Housing_object;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract_6 **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0003RL * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Extract - work.W_Collateral_object    A5ZNM6KG.BV000317 * 
 *                  Extract -                             A5ZNM6KG.BV000318 * 
 *                   work.W_Custody_collateral_object                       * 
 * Target Table:    Join - work.WLMPSA6X                  A5ZNM6KG.BV00031E * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete WLMPSA6X;
quit;

proc sql;
   create view work.WLMPSA6X as
   select
      W_Collateral_object.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      W_Collateral_object.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      W_Collateral_object.internal_object_id length = 10   
         label = 'Object ID number',
      W_Collateral_object.object_type_cd length = 4   
         label = 'Object type',
      W_Collateral_object.currency_cd length = 3   
         label = 'The currency of the valuation',
      W_Collateral_object.market_value_amt length = 8   
         format = 15.2
         label = 'The estimated market value of the object',
      W_Collateral_object.residence_value_amt length = 8   
         format = 15.2
         label = 'Object value linked with dwelling (in currency)',
      W_Collateral_object.collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'Calculated loan value of collateral (belåningsvärde)',
      W_Collateral_object.valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Valuation date',
      W_Collateral_object.index_market_value_amt length = 8   
         format = 15.2
         label = 'Index adjusted estimated market value',
      W_Collateral_object.index_residence_market_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted value of the residence',
      W_Collateral_object.index_collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted loan value of the collateral',
      W_Collateral_object.index_valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'This field denotes the date when the index adjustment was executed',
      W_Collateral_object.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      W_Custody_collateral_object.crm_value_amt length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      W_Custody_collateral_object.total_deposit_amt length = 8   
         format = 15.2
         label = 'The sum of all trading accounts connected to this collateral. If an account has a negative balance then it is not included.'
   from
      work.W_Collateral_object as W_Collateral_object left join 
      work.W_Custody_collateral_object as W_Custody_collateral_object
         on
         (
            W_Collateral_object.information_date = W_Custody_collateral_object.information_date
            and W_Collateral_object.bank_id = W_Custody_collateral_object.bank_id
            and W_Collateral_object.internal_object_id = W_Custody_collateral_object.internal_object_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0003RM * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Extract - work.W_Deposit_object       A5ZNM6KG.BV000319 * 
 *                  Join - work.WLMPSA6X                  A5ZNM6KG.BV00031E * 
 * Target Table:    Join - work.WLMT2T3I                  A5ZNM6KG.BV00031F * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete WLMT2T3I;
quit;

proc sql;
   create view work.WLMT2T3I as
   select
      WLMPSA6X.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      WLMPSA6X.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      WLMPSA6X.internal_object_id length = 10   
         label = 'Object ID number',
      WLMPSA6X.object_type_cd length = 4   
         label = 'Object type',
      WLMPSA6X.currency_cd length = 3   
         label = 'The currency of the valuation',
      WLMPSA6X.market_value_amt length = 8   
         format = 15.2
         label = 'The estimated market value of the object',
      WLMPSA6X.residence_value_amt length = 8   
         format = 15.2
         label = 'Object value linked with dwelling (in currency)',
      WLMPSA6X.collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'Calculated loan value of collateral (belåningsvärde)',
      WLMPSA6X.valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Valuation date',
      WLMPSA6X.index_market_value_amt length = 8   
         format = 15.2
         label = 'Index adjusted estimated market value',
      WLMPSA6X.index_residence_market_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted value of the residence',
      WLMPSA6X.index_collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted loan value of the collateral',
      WLMPSA6X.index_valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'This field denotes the date when the index adjustment was executed',
      WLMPSA6X.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      WLMPSA6X.crm_value_amt length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      WLMPSA6X.total_deposit_amt length = 8   
         format = 15.2
         label = 'The sum of all trading accounts connected to this collateral. If an account has a negative balance then it is not included.',
      W_Deposit_object.account_balance_amt length = 8   
         format = 15.2
         label = 'The balance of the connected account',
      W_Deposit_object.maximum_pledge_amt length = 8   
         format = 15.2
         label = 'Maximum amount to cover interest and payments of capital. If empty then the entire amount is pledged.'
   from
      work.WLMPSA6X as WLMPSA6X left join 
      work.W_Deposit_object as W_Deposit_object
         on
         (
            WLMPSA6X.information_date = W_Deposit_object.information_date
            and WLMPSA6X.bank_id = W_Deposit_object.bank_id
            and WLMPSA6X.internal_object_id = W_Deposit_object.internal_object_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0003RN * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Join - work.WLMT2T3I                  A5ZNM6KG.BV00031F * 
 *                  Extract - work.W_Guarantee_object     A5ZNM6KG.BV00031A * 
 * Target Table:    Join - work.WLMUG0GI                  A5ZNM6KG.BV00031G * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete WLMUG0GI;
quit;

proc sql;
   create view work.WLMUG0GI as
   select
      WLMT2T3I.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      WLMT2T3I.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      WLMT2T3I.internal_object_id length = 10   
         label = 'Object ID number',
      WLMT2T3I.object_type_cd length = 4   
         label = 'Object type',
      WLMT2T3I.currency_cd length = 3   
         label = 'The currency of the valuation',
      WLMT2T3I.market_value_amt length = 8   
         format = 15.2
         label = 'The estimated market value of the object',
      WLMT2T3I.residence_value_amt length = 8   
         format = 15.2
         label = 'Object value linked with dwelling (in currency)',
      WLMT2T3I.collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'Calculated loan value of collateral (belåningsvärde)',
      WLMT2T3I.valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Valuation date',
      WLMT2T3I.index_market_value_amt length = 8   
         format = 15.2
         label = 'Index adjusted estimated market value',
      WLMT2T3I.index_residence_market_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted value of the residence',
      WLMT2T3I.index_collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted loan value of the collateral',
      WLMT2T3I.index_valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'This field denotes the date when the index adjustment was executed',
      WLMT2T3I.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      WLMT2T3I.crm_value_amt length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      WLMT2T3I.total_deposit_amt length = 8   
         format = 15.2
         label = 'The sum of all trading accounts connected to this collateral. If an account has a negative balance then it is not included.',
      WLMT2T3I.account_balance_amt length = 8   
         format = 15.2
         label = 'The balance of the connected account',
      WLMT2T3I.maximum_pledge_amt length = 8   
         format = 15.2
         label = 'Maximum amount to cover interest and payments of capital. If empty then the entire amount is pledged.',
      W_Guarantee_object.guarantors_cnt length = 4   
         format = 8.
         label = 'Number of guarantors'
   from
      work.WLMT2T3I as WLMT2T3I left join 
      work.W_Guarantee_object as W_Guarantee_object
         on
         (
            WLMT2T3I.information_date = W_Guarantee_object.information_date
            and WLMT2T3I.bank_id = W_Guarantee_object.bank_id
            and WLMT2T3I.internal_object_id = W_Guarantee_object.internal_object_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0003RO * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Join - work.WLMUG0GI                  A5ZNM6KG.BV00031G * 
 *                  Extract - work.W_Real_property_object A5ZNM6KG.BV00031B * 
 * Target Table:    Join - work.WLMUSMIO                  A5ZNM6KG.BV00031H * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete WLMUSMIO;
quit;

proc sql;
   create view work.WLMUSMIO as
   select
      WLMUG0GI.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      WLMUG0GI.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      WLMUG0GI.internal_object_id length = 10   
         label = 'Object ID number',
      WLMUG0GI.object_type_cd length = 4   
         label = 'Object type',
      WLMUG0GI.currency_cd length = 3   
         label = 'The currency of the valuation',
      WLMUG0GI.market_value_amt length = 8   
         format = 15.2
         label = 'The estimated market value of the object',
      WLMUG0GI.residence_value_amt length = 8   
         format = 15.2
         label = 'Object value linked with dwelling (in currency)',
      WLMUG0GI.collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'Calculated loan value of collateral (belåningsvärde)',
      WLMUG0GI.valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Valuation date',
      WLMUG0GI.index_market_value_amt length = 8   
         format = 15.2
         label = 'Index adjusted estimated market value',
      WLMUG0GI.index_residence_market_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted value of the residence',
      WLMUG0GI.index_collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted loan value of the collateral',
      WLMUG0GI.index_valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'This field denotes the date when the index adjustment was executed',
      WLMUG0GI.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      WLMUG0GI.crm_value_amt length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      WLMUG0GI.total_deposit_amt length = 8   
         format = 15.2
         label = 'The sum of all trading accounts connected to this collateral. If an account has a negative balance then it is not included.',
      WLMUG0GI.account_balance_amt length = 8   
         format = 15.2
         label = 'The balance of the connected account',
      WLMUG0GI.maximum_pledge_amt length = 8   
         format = 15.2
         label = 'Maximum amount to cover interest and payments of capital. If empty then the entire amount is pledged.',
      WLMUG0GI.guarantors_cnt length = 4   
         format = 8.
         label = 'Number of guarantors',
      W_Real_property_object.main_object_type_cd length = 4   
         label = 'Main property object type code',
      W_Real_property_object.main_property_id length = 23   
         label = 'Main property unit identification number'
   from
      work.WLMUG0GI as WLMUG0GI left join 
      work.W_Real_property_object as W_Real_property_object
         on
         (
            WLMUG0GI.information_date = W_Real_property_object.information_date
            and WLMUG0GI.bank_id = W_Real_property_object.bank_id
            and WLMUG0GI.internal_object_id = W_Real_property_object.internal_object_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0003RP * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Join - work.WLMUSMIO                  A5ZNM6KG.BV00031H * 
 *                  Extract - work.W_Housing_object       A5ZNM6KG.BV00031C * 
 * Target Table:    Join - work.WLMV3DIN                  A5ZNM6KG.BV00031D * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete WLMV3DIN;
quit;

proc sql;
   create view work.WLMV3DIN as
   select
      WLMUSMIO.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      WLMUSMIO.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      WLMUSMIO.internal_object_id length = 10   
         label = 'Object ID number',
      WLMUSMIO.object_type_cd length = 4   
         label = 'Object type',
      WLMUSMIO.currency_cd length = 3   
         label = 'The currency of the valuation',
      WLMUSMIO.market_value_amt length = 8   
         format = 15.2
         label = 'The estimated market value of the object',
      WLMUSMIO.residence_value_amt length = 8   
         format = 15.2
         label = 'Object value linked with dwelling (in currency)',
      WLMUSMIO.collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'Calculated loan value of collateral (belåningsvärde)',
      WLMUSMIO.valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Valuation date',
      WLMUSMIO.index_market_value_amt length = 8   
         format = 15.2
         label = 'Index adjusted estimated market value',
      WLMUSMIO.index_residence_market_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted value of the residence',
      WLMUSMIO.index_collateral_loan_value_amt length = 8   
         format = 15.2
         label = 'The index adjusted loan value of the collateral',
      WLMUSMIO.index_valuation_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'This field denotes the date when the index adjustment was executed',
      WLMUSMIO.extracted_dt length = 8   
         format = DATETIME20.
         label = 'Extract timestamp (date & time)',
      WLMUSMIO.crm_value_amt length = 8   
         format = 15.2
         label = 'Credit risk mitigation amount',
      WLMUSMIO.total_deposit_amt length = 8   
         format = 15.2
         label = 'The sum of all trading accounts connected to this collateral. If an account has a negative balance then it is not included.',
      WLMUSMIO.account_balance_amt length = 8   
         format = 15.2
         label = 'The balance of the connected account',
      WLMUSMIO.maximum_pledge_amt length = 8   
         format = 15.2
         label = 'Maximum amount to cover interest and payments of capital. If empty then the entire amount is pledged.',
      WLMUSMIO.guarantors_cnt length = 4   
         format = 8.
         label = 'Number of guarantors',
      WLMUSMIO.main_object_type_cd length = 4   
         label = 'Main property object type code',
      WLMUSMIO.main_property_id length = 23   
         label = 'Main property unit identification number',
      W_Housing_object.debt_share_amt length = 8   
         format = 15.2
         label = 'The current apartment´s share of the housing company´s debt (Bostadens andel av bostadsbolagets skuld)'
   from
      work.WLMUSMIO as WLMUSMIO left join 
      work.W_Housing_object as W_Housing_object
         on
         (
            WLMUSMIO.information_date = W_Housing_object.information_date
            and WLMUSMIO.bank_id = W_Housing_object.bank_id
            and WLMUSMIO.internal_object_id = W_Housing_object.internal_object_id
         )
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0003RD * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.WLMV3DIN                  A5ZNM6KG.BV00031D * 
 * Target Table:    Extract - work.W12JGKMY               A5ZNM6KG.BV000316 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RD);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.WLMV3DIN); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W12JGKMY;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W12JGKMY as
      select
         information_date,
         bank_id,
         internal_object_id,
         object_type_cd,
         currency_cd,
         market_value_amt,
         residence_value_amt,
         collateral_loan_value_amt,
         valuation_date,
         index_market_value_amt,
         index_residence_market_value_amt,
         index_collateral_loan_value_amt,
         index_valuation_date,
         crm_value_amt,
         total_deposit_amt,
         account_balance_amt,
         maximum_pledge_amt,
         guarantors_cnt,
         main_object_type_cd,
         main_property_id,
         debt_share_amt,
         extracted_dt,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W12JGKMY;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0003RE * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W12JGKMY               A5ZNM6KG.BV000316 * 
 * Target Table:    mel_dm.OBJECT                         A5ZNM6KG.BG0003XP * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003RE);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W12JGKMY); 

%let _INPUT_count = 1; 
%let _INPUT = work.W12JGKMY;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV000316%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W12JGKMY;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV000316%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mel_dm.OBJECT;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.OBJECT%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Collateral object - 410);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id internal_object_id object_type_cd currency_cd 
        market_value_amt residence_value_amt collateral_loan_value_amt 
        valuation_date index_market_value_amt index_residence_market_value_amt 
        index_collateral_loan_value_amt index_valuation_date crm_value_amt 
        total_deposit_amt account_balance_amt maximum_pledge_amt 
        guarantors_cnt main_object_type_cd main_property_id debt_share_amt 
        extracted_dt loaded_dt;

%let _OUTPUT0 = mel_dm.OBJECT;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.OBJECT%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Collateral object - 410);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id internal_object_id object_type_cd currency_cd 
        market_value_amt residence_value_amt collateral_loan_value_amt 
        valuation_date index_market_value_amt index_residence_market_value_amt 
        index_collateral_loan_value_amt index_valuation_date crm_value_amt 
        total_deposit_amt account_balance_amt maximum_pledge_amt 
        guarantors_cnt main_object_type_cd main_property_id debt_share_amt 
        extracted_dt loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bank_id internal_object_id object_type_cd currency_cd 
        market_value_amt residence_value_amt collateral_loan_value_amt 
        valuation_date index_market_value_amt index_residence_market_value_amt 
        index_collateral_loan_value_amt index_valuation_date crm_value_amt 
        total_deposit_amt account_balance_amt maximum_pledge_amt 
        guarantors_cnt main_object_type_cd main_property_id debt_share_amt 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id internal_object_id object_type_cd currency_cd 
        market_value_amt residence_value_amt collateral_loan_value_amt 
        valuation_date index_market_value_amt index_residence_market_value_amt 
        index_collateral_loan_value_amt index_valuation_date crm_value_amt 
        total_deposit_amt account_balance_amt maximum_pledge_amt 
        guarantors_cnt main_object_type_cd main_property_id debt_share_amt 
        extracted_dt loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mel_dm nolist; 
   modify OBJECT(ALTER=&alterpass ); 
      index create primary_index = (information_date bank_id internal_object_id)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

