/**************************************************************************** 
 * Job:             mel_dm.det_stage_and_ecl_override     A5ZNM6KG.BO0003QL * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Tables:   mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S   A5ZNM6KG.BG0006EY * 
 *                  mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S   A5ZNM6KG.BG0006EY * 
 * Target Tables:   mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S   A5ZNM6KG.BG0006EY * 
 *                  mel_dm.DET_STAGE_AND_ECL_OVERRIDE     A5ZNM6KG.BG0006EV * 
 *                                                                          * 
 * Generated on:    Tuesday, December 18, 2018 3:34:30 PM EET               * 
 * Generated by:    makkojon                                                * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003QL);
%let etls_jobName = %nrquote(mel_dm.det_stage_and_ecl_override);
%let etls_userID = %nrquote(makkojon);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0005EN * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S   A5ZNM6KG.BG0006EY * 
 * Target Table:    Extract - work.W3VT591O               A5ZNM6KG.BV0004J2 * 
 *                                                                          * 
 * User Written:    UserWrittenSourceCode                                   * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005EN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S); 

%let ETLS_SYSLAST = &SYSLAST;
/*---- Start of Pre-Process Code  ----*/ 

* Introduce macro variables ;
%let _main_obs= ;
%let _s_increment=+1;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

%let SYSLAST = &ETLS_SYSLAST;

%let _INPUT_count = 1;
%let _INPUT = mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(OBS = &_main_obs.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();
%let _INPUT_filetype = PhysicalTable;

%let _INPUT1 = mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S;
%let _INPUT1_connect = null;
%let _INPUT1_engine = BASE;
%let _INPUT1_memtype = DATA;
%let _INPUT1_options = %nrquote(OBS = &_main_obs.);
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S%(Table%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote();
%let _INPUT1_filetype = PhysicalTable;

%let _OUTPUT_count = 1;
%let _OUTPUT = work.W3VT591O;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004J2%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;
%let _OUTPUT_col_count = 9;
%let _OUTPUT_col0_name = information_date;
%let _OUTPUT_col0_table = work.W3VT591O;
%let _OUTPUT_col0_length = 4;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = FINDFDD10.;
%let _OUTPUT_col0_informat = DDMMYY10.;
%let _OUTPUT_col0_label = %nrquote(Information date);
%let _OUTPUT_col0_input0 = information_date;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = information_date;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = bank_id;
%let _OUTPUT_col1_table = work.W3VT591O;
%let _OUTPUT_col1_length = 1;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(Bank ID code: A = ÅB Finland, B = ÅB Sweden);
%let _OUTPUT_col1_input0 = bank_id;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = bank_id;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = account_id;
%let _OUTPUT_col2_table = work.W3VT591O;
%let _OUTPUT_col2_length = 20;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Account Number %(=key filed to other Account databases%). Same format in both Finland and Sweden);
%let _OUTPUT_col2_input0 = account_id;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = account_id;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = type_of_run_cd;
%let _OUTPUT_col3_table = work.W3VT591O;
%let _OUTPUT_col3_length = 6;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = ;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(Type of run code);
%let _OUTPUT_col3_input0 = type_of_run_cd;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = type_of_run_cd;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = ecl_override;
%let _OUTPUT_col4_table = work.W3VT591O;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 15.2;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(ECL override);
%let _OUTPUT_col4_input0 = ecl_override;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = ecl_override;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = stage_override;
%let _OUTPUT_col5_table = work.W3VT591O;
%let _OUTPUT_col5_length = 3;
%let _OUTPUT_col5_type = ;
%let _OUTPUT_col5_format = 3.;
%let _OUTPUT_col5_informat = ;
%let _OUTPUT_col5_label = %nrquote(Stage override);
%let _OUTPUT_col5_input0 = stage_override;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = stage_override;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = currency_cd;
%let _OUTPUT_col6_table = work.W3VT591O;
%let _OUTPUT_col6_length = 3;
%let _OUTPUT_col6_type = $;
%let _OUTPUT_col6_format = ;
%let _OUTPUT_col6_informat = ;
%let _OUTPUT_col6_label = %nrquote(Account Currency);
%let _OUTPUT_col6_input0 = currency_cd;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = currency_cd;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = override_reason_txt;
%let _OUTPUT_col7_table = work.W3VT591O;
%let _OUTPUT_col7_length = 200;
%let _OUTPUT_col7_type = $;
%let _OUTPUT_col7_format = ;
%let _OUTPUT_col7_informat = ;
%let _OUTPUT_col7_label = %nrquote(Reason for override);
%let _OUTPUT_col7_input0 = override_reason_txt;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = override_reason_txt;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = loaded_dt;
%let _OUTPUT_col8_table = work.W3VT591O;
%let _OUTPUT_col8_length = 8;
%let _OUTPUT_col8_type = ;
%let _OUTPUT_col8_format = DATETIME20.;
%let _OUTPUT_col8_informat = ;
%let _OUTPUT_col8_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT_col8_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT_col8_input_count = 0;
%let _OUTPUT_filetype = WorkTable;

%let _OUTPUT1 = work.W3VT591O;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/Extract_A5ZNM6KG.BV0004J2%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;
%let _OUTPUT1_col_count = 9;
%let _OUTPUT1_col0_name = information_date;
%let _OUTPUT1_col0_table = work.W3VT591O;
%let _OUTPUT1_col0_length = 4;
%let _OUTPUT1_col0_type = ;
%let _OUTPUT1_col0_format = FINDFDD10.;
%let _OUTPUT1_col0_informat = DDMMYY10.;
%let _OUTPUT1_col0_label = %nrquote(Information date);
%let _OUTPUT1_col0_input0 = information_date;
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input = information_date;
%let _OUTPUT1_col0_input_count = 1;
%let _OUTPUT1_col1_name = bank_id;
%let _OUTPUT1_col1_table = work.W3VT591O;
%let _OUTPUT1_col1_length = 1;
%let _OUTPUT1_col1_type = $;
%let _OUTPUT1_col1_format = ;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote(Bank ID code: A = ÅB Finland, B = ÅB Sweden);
%let _OUTPUT1_col1_input0 = bank_id;
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input = bank_id;
%let _OUTPUT1_col1_input_count = 1;
%let _OUTPUT1_col2_name = account_id;
%let _OUTPUT1_col2_table = work.W3VT591O;
%let _OUTPUT1_col2_length = 20;
%let _OUTPUT1_col2_type = $;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote(Account Number %(=key filed to other Account databases%). Same format in both Finland and Sweden);
%let _OUTPUT1_col2_input0 = account_id;
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input = account_id;
%let _OUTPUT1_col2_input_count = 1;
%let _OUTPUT1_col3_name = type_of_run_cd;
%let _OUTPUT1_col3_table = work.W3VT591O;
%let _OUTPUT1_col3_length = 6;
%let _OUTPUT1_col3_type = $;
%let _OUTPUT1_col3_format = ;
%let _OUTPUT1_col3_informat = ;
%let _OUTPUT1_col3_label = %nrquote(Type of run code);
%let _OUTPUT1_col3_input0 = type_of_run_cd;
%let _OUTPUT1_col3_exp = ;
%let _OUTPUT1_col3_input = type_of_run_cd;
%let _OUTPUT1_col3_input_count = 1;
%let _OUTPUT1_col4_name = ecl_override;
%let _OUTPUT1_col4_table = work.W3VT591O;
%let _OUTPUT1_col4_length = 8;
%let _OUTPUT1_col4_type = ;
%let _OUTPUT1_col4_format = 15.2;
%let _OUTPUT1_col4_informat = ;
%let _OUTPUT1_col4_label = %nrquote(ECL override);
%let _OUTPUT1_col4_input0 = ecl_override;
%let _OUTPUT1_col4_exp = ;
%let _OUTPUT1_col4_input = ecl_override;
%let _OUTPUT1_col4_input_count = 1;
%let _OUTPUT1_col5_name = stage_override;
%let _OUTPUT1_col5_table = work.W3VT591O;
%let _OUTPUT1_col5_length = 3;
%let _OUTPUT1_col5_type = ;
%let _OUTPUT1_col5_format = 3.;
%let _OUTPUT1_col5_informat = ;
%let _OUTPUT1_col5_label = %nrquote(Stage override);
%let _OUTPUT1_col5_input0 = stage_override;
%let _OUTPUT1_col5_exp = ;
%let _OUTPUT1_col5_input = stage_override;
%let _OUTPUT1_col5_input_count = 1;
%let _OUTPUT1_col6_name = currency_cd;
%let _OUTPUT1_col6_table = work.W3VT591O;
%let _OUTPUT1_col6_length = 3;
%let _OUTPUT1_col6_type = $;
%let _OUTPUT1_col6_format = ;
%let _OUTPUT1_col6_informat = ;
%let _OUTPUT1_col6_label = %nrquote(Account Currency);
%let _OUTPUT1_col6_input0 = currency_cd;
%let _OUTPUT1_col6_exp = ;
%let _OUTPUT1_col6_input = currency_cd;
%let _OUTPUT1_col6_input_count = 1;
%let _OUTPUT1_col7_name = override_reason_txt;
%let _OUTPUT1_col7_table = work.W3VT591O;
%let _OUTPUT1_col7_length = 200;
%let _OUTPUT1_col7_type = $;
%let _OUTPUT1_col7_format = ;
%let _OUTPUT1_col7_informat = ;
%let _OUTPUT1_col7_label = %nrquote(Reason for override);
%let _OUTPUT1_col7_input0 = override_reason_txt;
%let _OUTPUT1_col7_exp = ;
%let _OUTPUT1_col7_input = override_reason_txt;
%let _OUTPUT1_col7_input_count = 1;
%let _OUTPUT1_col8_name = loaded_dt;
%let _OUTPUT1_col8_table = work.W3VT591O;
%let _OUTPUT1_col8_length = 8;
%let _OUTPUT1_col8_type = ;
%let _OUTPUT1_col8_format = DATETIME20.;
%let _OUTPUT1_col8_informat = ;
%let _OUTPUT1_col8_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT1_col8_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT1_col8_input_count = 0;
%let _OUTPUT1_filetype = WorkTable;

/*---- Start of User Written Code  ----*/ 

* ********************* BEGIN MODIFIED PART ********************* ;
* In case the (_S) source is missing the first time the job is run, 
  use the corresponding STG sources to create the tables. 
* In case the main table has rows of the current month (2nd or later run), 
  use _H view as the source (where...)

* After changing the Code generation mode into "User written body", 
  this was included in the beginning of the modified part. 
  When need to change the extract
    0) Copy this MODIFIED PART into text editor.
    1) Change Code generation mode into "Automatic"
    3) Make the changes in the other tabs
    4) Change Code generation mode back into "User written body" 
       (Choose "No" when asked "Do you want to reload the saved user written code?".)
    5) Copy this MODIFIED PART from the text editor back here.
;  
%let _libr=%sysfunc(scan(&syslast.,1,'.')) ;
%let _tabl=%sysfunc(scan(&syslast.,2,'.')) ;
%let current_rows_in_target=0;
filename _sqlobs temp;

data _null_ ;
exists=exist("&syslast","DATA");
ext_len_target=2 ; *Snip as many chars as needed to get the target table name. ;
* Check the target libname in the following line., if not the same as source library ;
target_libr="&_libr." ;
target_tabl=substr(target_libr!!".&_tabl",1,length(target_libr!!".&_tabl")-ext_len_target) ; 
call symput('target_tabl',target_tabl) ;
call symput('_s_obs','0') ;
call symput('_main_obs','MAX') ;
file _sqlobs ;
put '* Get number of rows in main table ;';
file log ;
if not exists then do ;
  ext_len_source=2 ; *Snip as many chars as needed to get the new source table name. ;
  tablename=substr("dw_stg.&_tabl",1,length("dw_stg.&_tabl")-ext_len_source) ; 
  exists=exist(tablename,"DATA");
  if exists then do;
    call symput('syslast',tablename) ;
    call symput('_s_obs','MAX') ;
    call symput('_main_obs','0') ;
  end;
  else do ;
    put "ERROR: Table &syslast does not exist and the alternative source " tablename " does not exist either. ";
    abort abend;
  end ;
end ;
else do;
  file _sqlobs ;
  put 'proc sql noprint ; select count(*) from &target_tabl. where information_date=&active_date ; quit ;';
  put '%let current_rows_in_target=&sqlobs;';
  file log ;
end ;
run ;
%include _sqlobs ;

%put NOTE: syslast=&syslast, target_tabl=&target_tabl. current_rows_in_target=&current_rows_in_target. ; 

data _null_ ;
if &current_rows_in_target>0 then do ;
  tablename=substr("&syslast",1,length("&syslast")-2)!!'_H'; 
  exists=exist(tablename,"VIEW");
  if exists then do;
    call symput('syslast',tablename) ;
  end;
  else do ;
    put "ERROR: View &syslast does not exist. ";
    abort abend;
  end ;
end ;
run ;
%put NOTE: syslast=&syslast, target_tabl=&target_tabl., _s_obs=&_s_obs.. ; 

* ********************* END MODIFIED PART ********************* ;


%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W3VT591O;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W3VT591O as
      select
         information_date,
         bank_id,
         account_id,
         type_of_run_cd,
         ecl_override,
         stage_override,
         currency_cd,
         override_reason_txt,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
      (OBS = &_main_obs.)
      where information_date = &active_date.
   ;
quit;

%let SYSLAST = work.W3VT591O;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 


/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 


/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0005EO * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W3VT591O               A5ZNM6KG.BV0004J2 * 
 * Target Table:    mel_dm.DET_STAGE_AND_ECL_OVERRIDE     A5ZNM6KG.BG0006EV * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005EO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W3VT591O); 

%let _INPUT_count = 1; 
%let _INPUT = work.W3VT591O;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004J2%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W3VT591O;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV0004J2%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mel_dm.DET_STAGE_AND_ECL_OVERRIDE;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.DET_STAGE_AND_ECL_OVERRIDE%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Stage and ecl override);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;

%let _OUTPUT0 = mel_dm.DET_STAGE_AND_ECL_OVERRIDE;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.DET_STAGE_AND_ECL_OVERRIDE%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Stage and ecl override);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mel_dm nolist; 
   modify DET_STAGE_AND_ECL_OVERRIDE(ALTER=&alterpass ); 
      index create primary_index = (information_date bank_id account_id type_of_run_cd)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0005EM * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S   A5ZNM6KG.BG0006EY * 
 * Target Table:    Extract - work.W3VT4Q2K               A5ZNM6KG.BV0004J1 * 
 *                                                                          * 
 * User Written:    UserWrittenSourceCode                                   * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005EM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S); 

%let _INPUT_count = 1;
%let _INPUT = mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();
%let _INPUT_filetype = PhysicalTable;

%let _INPUT1 = mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S;
%let _INPUT1_connect = null;
%let _INPUT1_engine = BASE;
%let _INPUT1_memtype = DATA;
%let _INPUT1_options = %nrquote();
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S%(Table%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote();
%let _INPUT1_filetype = PhysicalTable;

%let _OUTPUT_count = 1;
%let _OUTPUT = work.W3VT4Q2K;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004J1%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;
%let _OUTPUT_col_count = 9;
%let _OUTPUT_col0_name = information_date;
%let _OUTPUT_col0_table = work.W3VT4Q2K;
%let _OUTPUT_col0_length = 4;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = FINDFDD10.;
%let _OUTPUT_col0_informat = DDMMYY10.;
%let _OUTPUT_col0_label = %nrquote(Information date);
%let _OUTPUT_col0_exp = intnx('month', &active_date,&_s_increment,'end');
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = bank_id;
%let _OUTPUT_col1_table = work.W3VT4Q2K;
%let _OUTPUT_col1_length = 1;
%let _OUTPUT_col1_type = $;
%let _OUTPUT_col1_format = ;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(Bank ID code: A = ÅB Finland, B = ÅB Sweden);
%let _OUTPUT_col1_input0 = bank_id;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = bank_id;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = account_id;
%let _OUTPUT_col2_table = work.W3VT4Q2K;
%let _OUTPUT_col2_length = 20;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Account Number %(=key filed to other Account databases%). Same format in both Finland and Sweden);
%let _OUTPUT_col2_input0 = account_id;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = account_id;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = type_of_run_cd;
%let _OUTPUT_col3_table = work.W3VT4Q2K;
%let _OUTPUT_col3_length = 6;
%let _OUTPUT_col3_type = $;
%let _OUTPUT_col3_format = ;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(Type of run code);
%let _OUTPUT_col3_input0 = type_of_run_cd;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = type_of_run_cd;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = ecl_override;
%let _OUTPUT_col4_table = work.W3VT4Q2K;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 15.2;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(ECL override);
%let _OUTPUT_col4_input0 = ecl_override;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = ecl_override;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = stage_override;
%let _OUTPUT_col5_table = work.W3VT4Q2K;
%let _OUTPUT_col5_length = 3;
%let _OUTPUT_col5_type = ;
%let _OUTPUT_col5_format = 3.;
%let _OUTPUT_col5_informat = ;
%let _OUTPUT_col5_label = %nrquote(Stage override);
%let _OUTPUT_col5_input0 = stage_override;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = stage_override;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = currency_cd;
%let _OUTPUT_col6_table = work.W3VT4Q2K;
%let _OUTPUT_col6_length = 3;
%let _OUTPUT_col6_type = $;
%let _OUTPUT_col6_format = ;
%let _OUTPUT_col6_informat = ;
%let _OUTPUT_col6_label = %nrquote(Account Currency);
%let _OUTPUT_col6_input0 = currency_cd;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = currency_cd;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = override_reason_txt;
%let _OUTPUT_col7_table = work.W3VT4Q2K;
%let _OUTPUT_col7_length = 200;
%let _OUTPUT_col7_type = $;
%let _OUTPUT_col7_format = ;
%let _OUTPUT_col7_informat = ;
%let _OUTPUT_col7_label = %nrquote(Reason for override);
%let _OUTPUT_col7_input0 = override_reason_txt;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = override_reason_txt;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = loaded_dt;
%let _OUTPUT_col8_table = work.W3VT4Q2K;
%let _OUTPUT_col8_length = 8;
%let _OUTPUT_col8_type = ;
%let _OUTPUT_col8_format = DATETIME20.;
%let _OUTPUT_col8_informat = ;
%let _OUTPUT_col8_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT_col8_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT_col8_input_count = 0;
%let _OUTPUT_filetype = WorkTable;

%let _OUTPUT1 = work.W3VT4Q2K;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/Extract_A5ZNM6KG.BV0004J1%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = information_date bank_id account_id type_of_run_cd ecl_override 
        stage_override currency_cd override_reason_txt loaded_dt;
%let _OUTPUT1_col_count = 9;
%let _OUTPUT1_col0_name = information_date;
%let _OUTPUT1_col0_table = work.W3VT4Q2K;
%let _OUTPUT1_col0_length = 4;
%let _OUTPUT1_col0_type = ;
%let _OUTPUT1_col0_format = FINDFDD10.;
%let _OUTPUT1_col0_informat = DDMMYY10.;
%let _OUTPUT1_col0_label = %nrquote(Information date);
%let _OUTPUT1_col0_exp = intnx('month', &active_date,&_s_increment,'end');
%let _OUTPUT1_col0_input_count = 0;
%let _OUTPUT1_col1_name = bank_id;
%let _OUTPUT1_col1_table = work.W3VT4Q2K;
%let _OUTPUT1_col1_length = 1;
%let _OUTPUT1_col1_type = $;
%let _OUTPUT1_col1_format = ;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote(Bank ID code: A = ÅB Finland, B = ÅB Sweden);
%let _OUTPUT1_col1_input0 = bank_id;
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input = bank_id;
%let _OUTPUT1_col1_input_count = 1;
%let _OUTPUT1_col2_name = account_id;
%let _OUTPUT1_col2_table = work.W3VT4Q2K;
%let _OUTPUT1_col2_length = 20;
%let _OUTPUT1_col2_type = $;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote(Account Number %(=key filed to other Account databases%). Same format in both Finland and Sweden);
%let _OUTPUT1_col2_input0 = account_id;
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input = account_id;
%let _OUTPUT1_col2_input_count = 1;
%let _OUTPUT1_col3_name = type_of_run_cd;
%let _OUTPUT1_col3_table = work.W3VT4Q2K;
%let _OUTPUT1_col3_length = 6;
%let _OUTPUT1_col3_type = $;
%let _OUTPUT1_col3_format = ;
%let _OUTPUT1_col3_informat = ;
%let _OUTPUT1_col3_label = %nrquote(Type of run code);
%let _OUTPUT1_col3_input0 = type_of_run_cd;
%let _OUTPUT1_col3_exp = ;
%let _OUTPUT1_col3_input = type_of_run_cd;
%let _OUTPUT1_col3_input_count = 1;
%let _OUTPUT1_col4_name = ecl_override;
%let _OUTPUT1_col4_table = work.W3VT4Q2K;
%let _OUTPUT1_col4_length = 8;
%let _OUTPUT1_col4_type = ;
%let _OUTPUT1_col4_format = 15.2;
%let _OUTPUT1_col4_informat = ;
%let _OUTPUT1_col4_label = %nrquote(ECL override);
%let _OUTPUT1_col4_input0 = ecl_override;
%let _OUTPUT1_col4_exp = ;
%let _OUTPUT1_col4_input = ecl_override;
%let _OUTPUT1_col4_input_count = 1;
%let _OUTPUT1_col5_name = stage_override;
%let _OUTPUT1_col5_table = work.W3VT4Q2K;
%let _OUTPUT1_col5_length = 3;
%let _OUTPUT1_col5_type = ;
%let _OUTPUT1_col5_format = 3.;
%let _OUTPUT1_col5_informat = ;
%let _OUTPUT1_col5_label = %nrquote(Stage override);
%let _OUTPUT1_col5_input0 = stage_override;
%let _OUTPUT1_col5_exp = ;
%let _OUTPUT1_col5_input = stage_override;
%let _OUTPUT1_col5_input_count = 1;
%let _OUTPUT1_col6_name = currency_cd;
%let _OUTPUT1_col6_table = work.W3VT4Q2K;
%let _OUTPUT1_col6_length = 3;
%let _OUTPUT1_col6_type = $;
%let _OUTPUT1_col6_format = ;
%let _OUTPUT1_col6_informat = ;
%let _OUTPUT1_col6_label = %nrquote(Account Currency);
%let _OUTPUT1_col6_input0 = currency_cd;
%let _OUTPUT1_col6_exp = ;
%let _OUTPUT1_col6_input = currency_cd;
%let _OUTPUT1_col6_input_count = 1;
%let _OUTPUT1_col7_name = override_reason_txt;
%let _OUTPUT1_col7_table = work.W3VT4Q2K;
%let _OUTPUT1_col7_length = 200;
%let _OUTPUT1_col7_type = $;
%let _OUTPUT1_col7_format = ;
%let _OUTPUT1_col7_informat = ;
%let _OUTPUT1_col7_label = %nrquote(Reason for override);
%let _OUTPUT1_col7_input0 = override_reason_txt;
%let _OUTPUT1_col7_exp = ;
%let _OUTPUT1_col7_input = override_reason_txt;
%let _OUTPUT1_col7_input_count = 1;
%let _OUTPUT1_col8_name = loaded_dt;
%let _OUTPUT1_col8_table = work.W3VT4Q2K;
%let _OUTPUT1_col8_length = 8;
%let _OUTPUT1_col8_type = ;
%let _OUTPUT1_col8_format = DATETIME20.;
%let _OUTPUT1_col8_informat = ;
%let _OUTPUT1_col8_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT1_col8_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT1_col8_input_count = 0;
%let _OUTPUT1_filetype = WorkTable;

/*---- Start of User Written Code  ----*/ 

* ********************* BEGIN MODIFIED PART ********************* ;
* In case the (_S) source is missing the first time the job is run, 
  use the corresponding STG sources to create the tables. 

* After changing the Code generation mode into "User written body", 
  this was included in the beginning of the modified part. 
  When need to change the extract
    0) Copy this MODIFIED PART into text editor.
    1) Change Code generation mode into "Automatic"
    3) Make the changes in the other tabs
    4) Change Code generation mode back into "User written body" 
       (Choose "No" when asked "Do you want to reload the saved user written code?".)
    5) Copy this MODIFIED PART from the text editor back here.
;  
%let _libr=%sysfunc(scan(&syslast.,1,'.')) ;
%let _tabl=%sysfunc(scan(&syslast.,2,'.')) ;

data _null_ ;
if symget('_s_obs')='MAX' then do ;
  ext_len_source=2 ; *Snip as many chars as needed to get the new source table name. ;
  tablename=substr("dw_stg.&_tabl",1,length("dw_stg.&_tabl")-ext_len_source) ; 
  exists=exist(tablename,"DATA");
  if exists then do;
    call symput('syslast',tablename) ;
    call symput('_s_increment','0') ;
  end;
  else do ;
    put "ERROR: Table &syslast does not exist and the alternative source " tablename " does not exist either. ";
    abort abend;
  end ;
end ;
run ;
%include _sqlobs ;

* ********************* END MODIFIED PART ********************* ;


%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W3VT4Q2K;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W3VT4Q2K as
      select
         (intnx('month', &active_date,&_s_increment,'end')) as information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date',
         bank_id,
         account_id,
         type_of_run_cd,
         ecl_override,
         stage_override,
         currency_cd,
         override_reason_txt,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
      where information_date = &active_date.
   ;
quit;

%let SYSLAST = work.W3VT4Q2K;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 


/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 


/**  Step end Extract **/

/*==========================================================================* 
 * Step:            Table Loader                          A5ZNM6KG.BS0005EL * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W3VT4Q2K               A5ZNM6KG.BV0004J1 * 
 * Target Table:    mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S   A5ZNM6KG.BG0006EY * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005EL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W3VT4Q2K); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: Update - Matching=ModifyByColumn, New=ModifyByColumn
   Blanks may replace non-blanks: true
   Constraint and index action selections: 'ASIS','ASIS','INIT','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S, DATA)) or 
         %sysfunc(exist(mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S, VIEW))); 
   
   %let etls_hasUpdateIndex=0; 
   
   /*---- Create a new table  ----*/ 
   %if (&etls_tableExist eq 0) %then 
   %do;  /* if table does not exist  */ 
   
      %put %str(NOTE: Creating table ...);
      
      data mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S;
         attrib information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date'; 
         attrib bank_id length = $1
            label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden'; 
         attrib account_id length = $20
            label = 'Account Number (=key filed to other Account databases). Same format in both Finland and Sweden'; 
         attrib type_of_run_cd length = $6
            label = 'Type of run code'; 
         attrib ecl_override length = 8
            format = 15.2
            label = 'ECL override'; 
         attrib stage_override length = 3
            format = 3.
            label = 'Stage override'; 
         attrib currency_cd length = $3
            label = 'Account Currency'; 
         attrib override_reason_txt length = $200
            label = 'Reason for override'; 
         attrib loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'; 
         call missing(of _all_);
         stop;
      run;
      
      %rcSet(&syserr); 
      
      /*---- Create the indexes for a table  ----*/ 
      %put %str(NOTE: Creating indexes ...);
      proc datasets lib = mel_dm nolist; 
         modify DET_STAGE_AND_ECL_OVERRIDE_S; 
            index create primary_index = (information_date bank_id account_id type_of_run_cd)
               / unique nomiss;
      quit; 
      
      %rcSet(&syserr); 
      
   %end;  /* if table does not exist  */ 
   
   /*---- Begin Modify Step  ----*/ 
   /* Allow user to specify IORC values to trigger step to stop. Initialize if  */ 
   /*  not assigned.                                                            */ 
   %if NOT %symexist(etls_StopOnIORC) %then %let etls_StopOnIORC=;
    
   data mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S; 
      length etls_msg $200; 
      drop etls_msg; 
      modify mel_dm.DET_STAGE_AND_ECL_OVERRIDE_S 
             &etls_lastTable
             updatemode = nomissingcheck 
      ; 
      
      by bank_id account_id type_of_run_cd;
      
      /* if the record does not exist in the master, then add it  */ 
      if %sysrc(_DSENMR) eq _iorc_ then 
         output; 
      /* if the record exists in the master, then replace it  */ 
      else if %sysrc(_SOK) eq _iorc_ then 
         replace; 
      %if &etls_StopOnIORC ne %then
      %do;
         if _iorc_ in (&etls_StopOnIORC) then
         do;
            etls_msg = iorcmsg();
            put etls_msg; 
            %rcSetDS(5)
            stop;
         end;
      %end;
      _iorc_ = 0; 
      _error_ = 0; 
      
   run; 
   
   %rcSet(&syserr); 
   
   %let etls_StopOnIORC=; /* reset to blank */ 
   
%mend etls_loader;
%etls_loader;



/**  Step end Table Loader **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

