/**************************************************************************** 
 * Job:             mel_isar.lgd_prob_of_ml_fut_llg       A5ZNM6KG.BO0003PF * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Table:    lgd_prob_of_ml_fut_llg.csv -          A5ZNM6KG.C10002GV * 
 *                  /sasdw/prod/mel/internal_files/outp                     * 
 *                  ut/lgd_prob_of_ml_fut_llg.csv                           * 
 * Target Table:    mel_isar.LGD_PROB_OF_ML_FUT_LLG       A5ZNM6KG.BG0004M0 * 
 *                                                                          * 
 * Generated on:    Wednesday, January 30, 2019 9:19:51 AM EET              * 
 * Generated by:    ier                                                     * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003PF);
%let etls_jobName = %nrquote(mel_isar.lgd_prob_of_ml_fut_llg);
%let etls_userID = %nrquote(ier);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            File Reader                           A5ZNM6KG.BS00044H * 
 * Transform:       File Reader                                             * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    lgd_prob_of_ml_fut_llg.csv -          A5ZNM6KG.C10002GV * 
 *                  /sasdw/prod/mel/internal_files/outp                     * 
 *                  ut/lgd_prob_of_ml_fut_llg.csv                           * 
 * Target Table:    File Reader - work.W861EKE5           A5ZNM6KG.BV0003CR * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS00044H);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W861EKE5;
quit;

data work.W861EKE5 / view = work.W861EKE5 ; 
   infile '/sasdw/prod/mel/internal_files/output/lgd_prob_of_ml_fut_llg.csv'
          lrecl = 10000
          delimiter = '|'
          dsd
          missover
          firstobs = 2; 
   ; 
   attrib information_date length = $10; 
   attrib account_id length = $20; 
   attrib customer_id length = $20; 
   attrib bank_id length = $1; 
   attrib type_of_run_cd length = $6; 
   attrib prob_major_loss_future_1 length = $20; 
   attrib prob_major_loss_future_2 length = $20; 
   attrib prob_major_loss_future_3 length = $20; 
   attrib prob_major_loss_future_4 length = $20; 
   attrib prob_major_loss_future_5 length = $20; 
   attrib prob_major_loss_future_6 length = $20; 
   attrib prob_major_loss_future_7 length = $20; 
   attrib prob_major_loss_future_8 length = $20; 
   attrib prob_major_loss_future_9 length = $20; 
   attrib prob_major_loss_future_10 length = $20; 
   attrib prob_major_loss_future_11 length = $20; 
   attrib prob_major_loss_future_12 length = $20; 
   attrib prob_major_loss_future_13 length = $20; 
   attrib prob_major_loss_future_14 length = $20; 
   attrib prob_major_loss_future_15 length = $20; 
   attrib prob_major_loss_future_16 length = $20; 
   attrib prob_major_loss_future_17 length = $20; 
   attrib prob_major_loss_future_18 length = $20; 
   attrib prob_major_loss_future_19 length = $20; 
   attrib prob_major_loss_future_20 length = $20; 
   attrib prob_major_loss_future_21 length = $20; 
   attrib prob_major_loss_future_22 length = $20; 
   attrib prob_major_loss_future_23 length = $20; 
   attrib prob_major_loss_future_24 length = $20; 
   attrib prob_major_loss_future_25 length = $20; 
   attrib prob_major_loss_future_26 length = $20; 
   attrib prob_major_loss_future_27 length = $20; 
   attrib prob_major_loss_future_28 length = $20; 
   attrib prob_major_loss_future_29 length = $20; 
   attrib prob_major_loss_future_30 length = $20; 
   attrib prob_major_loss_future_31 length = $20; 
   attrib prob_major_loss_future_32 length = $20; 
   attrib prob_major_loss_future_33 length = $20; 
   attrib prob_major_loss_future_34 length = $20; 
   attrib prob_major_loss_future_35 length = $20; 
   attrib prob_major_loss_future_36 length = $20; 
   attrib prob_major_loss_future_37 length = $20; 
   attrib prob_major_loss_future_38 length = $20; 
   attrib prob_major_loss_future_39 length = $20; 
   attrib prob_major_loss_future_40 length = $20; 
   attrib prob_major_loss_future_41 length = $20; 
   attrib prob_major_loss_future_42 length = $20; 
   attrib prob_major_loss_future_43 length = $20; 
   attrib prob_major_loss_future_44 length = $20; 
   attrib prob_major_loss_future_45 length = $20; 
   attrib prob_major_loss_future_46 length = $20; 
   attrib prob_major_loss_future_47 length = $20; 
   attrib prob_major_loss_future_48 length = $20; 
   attrib prob_major_loss_future_49 length = $20; 
   attrib prob_major_loss_future_50 length = $20; 
   
   input information_date account_id customer_id bank_id type_of_run_cd 
         prob_major_loss_future_1 prob_major_loss_future_2 
         prob_major_loss_future_3 prob_major_loss_future_4 
         prob_major_loss_future_5 prob_major_loss_future_6 
         prob_major_loss_future_7 prob_major_loss_future_8 
         prob_major_loss_future_9 prob_major_loss_future_10 
         prob_major_loss_future_11 prob_major_loss_future_12 
         prob_major_loss_future_13 prob_major_loss_future_14 
         prob_major_loss_future_15 prob_major_loss_future_16 
         prob_major_loss_future_17 prob_major_loss_future_18 
         prob_major_loss_future_19 prob_major_loss_future_20 
         prob_major_loss_future_21 prob_major_loss_future_22 
         prob_major_loss_future_23 prob_major_loss_future_24 
         prob_major_loss_future_25 prob_major_loss_future_26 
         prob_major_loss_future_27 prob_major_loss_future_28 
         prob_major_loss_future_29 prob_major_loss_future_30 
         prob_major_loss_future_31 prob_major_loss_future_32 
         prob_major_loss_future_33 prob_major_loss_future_34 
         prob_major_loss_future_35 prob_major_loss_future_36 
         prob_major_loss_future_37 prob_major_loss_future_38 
         prob_major_loss_future_39 prob_major_loss_future_40 
         prob_major_loss_future_41 prob_major_loss_future_42 
         prob_major_loss_future_43 prob_major_loss_future_44 
         prob_major_loss_future_45 prob_major_loss_future_46 
         prob_major_loss_future_47 prob_major_loss_future_48 
         prob_major_loss_future_49 prob_major_loss_future_50; 
   
run; 

%rcSet(&syserr); 



/**  Step end File Reader **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS00044I * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    File Reader - work.W861EKE5           A5ZNM6KG.BV0003CR * 
 * Target Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0003CS * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS00044I);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W861EKE5); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W87VM0VU;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W87VM0VU as
      select
         (INPUT(information_date,yymmdd10.)) as information_date length = 4
            format = findfdd10.
            label = 'Information date of the record',
         account_id,
         customer_id,
         bank_id,
         type_of_run_cd,
         (INPUT(prob_major_loss_future_1,BEST32.)) as prob_major_loss_future_1 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 1',
         (INPUT(prob_major_loss_future_2,BEST32.)) as prob_major_loss_future_2 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 2',
         (INPUT(prob_major_loss_future_3,BEST32.)) as prob_major_loss_future_3 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 3',
         (INPUT(prob_major_loss_future_4,BEST32.)) as prob_major_loss_future_4 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 4',
         (INPUT(prob_major_loss_future_5,BEST32.)) as prob_major_loss_future_5 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 5',
         (INPUT(prob_major_loss_future_6,BEST32.)) as prob_major_loss_future_6 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 6',
         (INPUT(prob_major_loss_future_7,BEST32.)) as prob_major_loss_future_7 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 7',
         (INPUT(prob_major_loss_future_8,BEST32.)) as prob_major_loss_future_8 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 8',
         (INPUT(prob_major_loss_future_9,BEST32.)) as prob_major_loss_future_9 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 9',
         (INPUT(prob_major_loss_future_10,BEST32.)) as prob_major_loss_future_10 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 10',
         (INPUT(prob_major_loss_future_11,BEST32.)) as prob_major_loss_future_11 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 11',
         (INPUT(prob_major_loss_future_12,BEST32.)) as prob_major_loss_future_12 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 12',
         (INPUT(prob_major_loss_future_13,BEST32.)) as prob_major_loss_future_13 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 13',
         (INPUT(prob_major_loss_future_14,BEST32.)) as prob_major_loss_future_14 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 14',
         (INPUT(prob_major_loss_future_15,BEST32.)) as prob_major_loss_future_15 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 15',
         (INPUT(prob_major_loss_future_16,BEST32.)) as prob_major_loss_future_16 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 16',
         (INPUT(prob_major_loss_future_17,BEST32.)) as prob_major_loss_future_17 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 17',
         (INPUT(prob_major_loss_future_18,BEST32.)) as prob_major_loss_future_18 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 18',
         (INPUT(prob_major_loss_future_19,BEST32.)) as prob_major_loss_future_19 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 19',
         (INPUT(prob_major_loss_future_20,BEST32.)) as prob_major_loss_future_20 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 20',
         (INPUT(prob_major_loss_future_21,BEST32.)) as prob_major_loss_future_21 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 21',
         (INPUT(prob_major_loss_future_22,BEST32.)) as prob_major_loss_future_22 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 22',
         (INPUT(prob_major_loss_future_23,BEST32.)) as prob_major_loss_future_23 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 23',
         (INPUT(prob_major_loss_future_24,BEST32.)) as prob_major_loss_future_24 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 24',
         (INPUT(prob_major_loss_future_25,BEST32.)) as prob_major_loss_future_25 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 25',
         (INPUT(prob_major_loss_future_26,BEST32.)) as prob_major_loss_future_26 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 26',
         (INPUT(prob_major_loss_future_27,BEST32.)) as prob_major_loss_future_27 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 27',
         (INPUT(prob_major_loss_future_28,BEST32.)) as prob_major_loss_future_28 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 28',
         (INPUT(prob_major_loss_future_29,BEST32.)) as prob_major_loss_future_29 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 29',
         (INPUT(prob_major_loss_future_30,BEST32.)) as prob_major_loss_future_30 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 30',
         (INPUT(prob_major_loss_future_31,BEST32.)) as prob_major_loss_future_31 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 31',
         (INPUT(prob_major_loss_future_32,BEST32.)) as prob_major_loss_future_32 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 32',
         (INPUT(prob_major_loss_future_33,BEST32.)) as prob_major_loss_future_33 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 33',
         (INPUT(prob_major_loss_future_34,BEST32.)) as prob_major_loss_future_34 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 34',
         (INPUT(prob_major_loss_future_35,BEST32.)) as prob_major_loss_future_35 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 35',
         (INPUT(prob_major_loss_future_36,BEST32.)) as prob_major_loss_future_36 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 36',
         (INPUT(prob_major_loss_future_37,BEST32.)) as prob_major_loss_future_37 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 37',
         (INPUT(prob_major_loss_future_38,BEST32.)) as prob_major_loss_future_38 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 38',
         (INPUT(prob_major_loss_future_39,BEST32.)) as prob_major_loss_future_39 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 39',
         (INPUT(prob_major_loss_future_40,BEST32.)) as prob_major_loss_future_40 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 40',
         (INPUT(prob_major_loss_future_41,BEST32.)) as prob_major_loss_future_41 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 41',
         (INPUT(prob_major_loss_future_42,BEST32.)) as prob_major_loss_future_42 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 42',
         (INPUT(prob_major_loss_future_43,BEST32.)) as prob_major_loss_future_43 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 43',
         (INPUT(prob_major_loss_future_44,BEST32.)) as prob_major_loss_future_44 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 44',
         (INPUT(prob_major_loss_future_45,BEST32.)) as prob_major_loss_future_45 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 45',
         (INPUT(prob_major_loss_future_46,BEST32.)) as prob_major_loss_future_46 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 46',
         (INPUT(prob_major_loss_future_47,BEST32.)) as prob_major_loss_future_47 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 47',
         (INPUT(prob_major_loss_future_48,BEST32.)) as prob_major_loss_future_48 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 48',
         (INPUT(prob_major_loss_future_49,BEST32.)) as prob_major_loss_future_49 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 49',
         (INPUT(prob_major_loss_future_50,BEST32.)) as prob_major_loss_future_50 length = 8
            format = 15.5
            label = 'Estimated probability of major loss for the time period 50',
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = datetime20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W87VM0VU;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            Table Loader                          A5ZNM6KG.BS00047Q * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W87VM0VU               A5ZNM6KG.BV0003CS * 
 * Target Table:    mel_isar.LGD_PROB_OF_ML_FUT_LLG       A5ZNM6KG.BG0004M0 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS00047Q);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W87VM0VU); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: Replace - EntireTable
   Constraint and index action selections: 'ASIS','ASIS','INIT','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(mel_isar.LGD_PROB_OF_ML_FUT_LLG, DATA)) or 
         %sysfunc(exist(mel_isar.LGD_PROB_OF_ML_FUT_LLG, VIEW))); 
   
   %if &etls_tableExist %then 
   %do;/* table exists  */ 
      %let etls_hasPreExistingConstraint=0; 
      
      proc datasets lib = work nolist nowarn memtype = (data view);
         delete etls_commands etls_commands_F;
      quit;
      
      %let etls_otherTablesReferToThisTable=0;
      
      %macro etls_CIContents(table=,workTableOut=,inDSOptions=);
         %put NOTE: Building table listing Constraints and Indexes for: &table;
         proc datasets lib=work nolist; delete &workTableOut; quit;
         proc contents data=&table&inDSOptions out2=&workTableOut noprint; run;
         
         data &workTableOut;
            length name $60 type $20 icown idxUnique idxNoMiss $3 recreate $600;
            name = '';
            type = '';
            icown = '';
            idxUnique = '';
            idxNoMiss = '';
            recreate = '';
            set &workTableOut;
            ref = '';
            type=upcase(type);
            if type eq 'REFERENTIAL' then
            do;
               put "WARNING%QUOTE(:) Target table is referenced by constraints in"
                    " another table: " ref;
               call symput('etls_otherTablesReferToThisTable','1');
               delete;
            end;
            if type='INDEX' and ICOwn eq 'YES' then delete;
         run;
         %rcSet(&syserr); 
         
      %mend etls_CIContents;
      
      %etls_CIContents(table=mel_isar.LGD_PROB_OF_ML_FUT_LLG, workTableOut=etls_commands, inDSOptions=);
      
      %if &etls_otherTablesReferToThisTable %then 
         %put WARNING%QUOTE(:) Replacing entire table will fail. Consider an alternate load technique or revising constraints.; 
      %else 
      %do; /* okay - remove foreign keys  */ 
      
         data etls_commands_F; 
            set etls_commands; 
            if upcase(type)="FOREIGN KEY" then 
            do; 
               command='ic delete '||trim(name)||';';
               output etls_commands_F; 
            end; 
         run; 
         
         %put %str(NOTE: Removing foreign keys before dropping table...);
         data _null_;
            set etls_commands_F end=eof;
            if _n_=1 then 
               call execute('proc datasets nolist lib=mel_isar;modify LGD_PROB_OF_ML_FUT_LLG;');
            call execute(command);
            if eof then call execute('; quit;');
         run;
         %rcSet(&syserr); 
         
   %end; /* okay - remove foreign keys  */ 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete etls_commands etls_commands_F;
   quit;
   
   /*---- Drop a table  ----*/ 
   %put %str(NOTE: Dropping table ...);
   proc datasets lib = mel_isar nolist nowarn memtype = (data view);
      delete LGD_PROB_OF_ML_FUT_LLG;
   quit;
   
   %rcSet(&syserr); 
   
   %let etls_tableExist = 0;
   
%end; /* table exists  */ 

/*---- Create a new table  ----*/ 
%if (&etls_tableExist eq 0) %then 
%do;  /* if table does not exist  */ 

   %put %str(NOTE: Creating table ...);
   
   data mel_isar.LGD_PROB_OF_ML_FUT_LLG;
      attrib information_date length = 4
         format = FINDFDD10.
         label = 'Information date of the record'; 
      attrib account_id length = $20
         label = 'Account Number'; 
      attrib customer_id length = $20
         label = 'CBS Customer ID'; 
      attrib bank_id length = $1
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden'; 
      attrib type_of_run_cd length = $6
         label = 'Type of run code'; 
      attrib prob_major_loss_future_1 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 1'; 
      attrib prob_major_loss_future_2 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 2'; 
      attrib prob_major_loss_future_3 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 3'; 
      attrib prob_major_loss_future_4 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 4'; 
      attrib prob_major_loss_future_5 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 5'; 
      attrib prob_major_loss_future_6 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 6'; 
      attrib prob_major_loss_future_7 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 7'; 
      attrib prob_major_loss_future_8 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 8'; 
      attrib prob_major_loss_future_9 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 9'; 
      attrib prob_major_loss_future_10 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 10'; 
      attrib prob_major_loss_future_11 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 11'; 
      attrib prob_major_loss_future_12 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 12'; 
      attrib prob_major_loss_future_13 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 13'; 
      attrib prob_major_loss_future_14 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 14'; 
      attrib prob_major_loss_future_15 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 15'; 
      attrib prob_major_loss_future_16 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 16'; 
      attrib prob_major_loss_future_17 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 17'; 
      attrib prob_major_loss_future_18 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 18'; 
      attrib prob_major_loss_future_19 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 19'; 
      attrib prob_major_loss_future_20 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 20'; 
      attrib prob_major_loss_future_21 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 21'; 
      attrib prob_major_loss_future_22 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 22'; 
      attrib prob_major_loss_future_23 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 23'; 
      attrib prob_major_loss_future_24 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 24'; 
      attrib prob_major_loss_future_25 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 25'; 
      attrib prob_major_loss_future_26 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 26'; 
      attrib prob_major_loss_future_27 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 27'; 
      attrib prob_major_loss_future_28 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 28'; 
      attrib prob_major_loss_future_29 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 29'; 
      attrib prob_major_loss_future_30 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 30'; 
      attrib prob_major_loss_future_31 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 31'; 
      attrib prob_major_loss_future_32 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 32'; 
      attrib prob_major_loss_future_33 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 33'; 
      attrib prob_major_loss_future_34 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 34'; 
      attrib prob_major_loss_future_35 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 35'; 
      attrib prob_major_loss_future_36 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 36'; 
      attrib prob_major_loss_future_37 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 37'; 
      attrib prob_major_loss_future_38 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 38'; 
      attrib prob_major_loss_future_39 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 39'; 
      attrib prob_major_loss_future_40 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 40'; 
      attrib prob_major_loss_future_41 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 41'; 
      attrib prob_major_loss_future_42 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 42'; 
      attrib prob_major_loss_future_43 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 43'; 
      attrib prob_major_loss_future_44 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 44'; 
      attrib prob_major_loss_future_45 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 45'; 
      attrib prob_major_loss_future_46 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 46'; 
      attrib prob_major_loss_future_47 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 47'; 
      attrib prob_major_loss_future_48 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 48'; 
      attrib prob_major_loss_future_49 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 49'; 
      attrib prob_major_loss_future_50 length = 8
         format = 15.5
         label = 'Estimated probability of major loss for the time period 50'; 
      attrib loaded_dt length = 8
         format = DATETIME20.
         label = 'Load timestamp (date & time)'; 
      call missing(of _all_);
      stop;
   run;
   
   %rcSet(&syserr); 
   
   /*---- Create the indexes for a table  ----*/ 
   %put %str(NOTE: Creating indexes ...);
   proc datasets lib = mel_isar nolist; 
      modify LGD_PROB_OF_ML_FUT_LLG; 
         index create primary_index = (information_date account_id customer_id bank_id type_of_run_cd)
            / unique;
   quit; 
   
   %rcSet(&syserr); 
   
%end;  /* if table does not exist  */ 

/*---- Append  ----*/ 
%put %str(NOTE: Appending data ...);

proc append base = mel_isar.LGD_PROB_OF_ML_FUT_LLG 
   data = &etls_lastTable (&etls_tableOptions)  force ; 
 run; 

%rcSet(&syserr); 

%mend etls_loader;
%etls_loader;



/**  Step end Table Loader **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

