/**************************************************************************** 
 * Job:             mel_dm.account_exp_ovd                A5ZNM6KG.BO0004KE * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Tables:   dw_dw.BASEL_IRB                       A5ZNM6KG.BG0002DI * 
 *                  dw_dw.EXCHANGE_RATES                  A5ZNM6KG.BG0003EB * 
 *                  dw_dw.ACCOUNT                         A5ZNM6KG.BG0002DO * 
 *                  dw_dw.ACCOUNT_DAILY                   A5ZNM6KG.BG0002DQ * 
 *                  dw_dw.BASEL_SA                        A5ZNM6KG.BG0002DH * 
 * Target Table:    mel_dm.ACCOUNT_EXP_OVD                A5ZNM6KG.BG0006LG * 
 *                                                                          * 
 * Generated on:    Tuesday, March 12, 2019 10:46:31 AM EET                 * 
 * Generated by:    makkojon                                                * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0004KE);
%let etls_jobName = %nrquote(mel_dm.account_exp_ovd);
%let etls_userID = %nrquote(makkojon);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005NP * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT_DAILY                   A5ZNM6KG.BG0002DQ * 
 * Target Table:    shadow_OUTPUT0 - work.account_daily   A5ZNM6KG.BV0004QB * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT_DAILY); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.ACCOUNT_DAILY;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_DAILY%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Account Daily - all accounts);

%let _INPUT0 = dw_dw.ACCOUNT_DAILY;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT_DAILY%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Account Daily - all accounts);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.account_daily;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004QB%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.account_daily;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004QB%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete account_daily;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id booked_balance_amt 
        valuedate_balance_amt debit_ref_interest_cd debit_interest_rate_pct 
        debit_margin_rate_pct credit_ref_interest_cd credit_interest_rate_pct 
        credit_margin_rate_pct interest_start_date interest_end_date 
        debit_interest_estimate_amt credit_interest_estimate_amt 
        debit_interest_accrued_amt credit_interest_accrued_amt overdraft_date 
        debit_interest_calc_cd credit_interest_calc_cd source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005NO * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.ACCOUNT                         A5ZNM6KG.BG0002DO * 
 * Target Table:    shadow_OUTPUT0 - work.account         A5ZNM6KG.BV0004QA * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.ACCOUNT); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.ACCOUNT;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.ACCOUNT;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.ACCOUNT%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.account;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004QA%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;

%let _OUTPUT0 = work.account;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004QA%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete account;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id account_number_official 
        iban_number_id account_type_cd currency_cd owner_id owner_ssn_id 
        shared result_office_id opened_date changed_date end_date close_date 
        statement_period_cd group_account_id reference_date source_system_cd 
        extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005NN * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.EXCHANGE_RATES                  A5ZNM6KG.BG0003EB * 
 * Target Table:    shadow_OUTPUT0 - work.exchange_rates  A5ZNM6KG.BV0004Q9 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NN);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.EXCHANGE_RATES); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.EXCHANGE_RATES;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass.);
%let _INPUT_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.EXCHANGE_RATES%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = dw_dw.EXCHANGE_RATES;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass.);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass.);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.EXCHANGE_RATES%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.exchange_rates;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004Q9%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.exchange_rates;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004Q9%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete exchange_rates;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id currency_cd base_currency_cd 
        registration_date cbs_currency_date mid_rate inverse_mid_rate 
        sale_rate buy_rate source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005NM * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.BASEL_IRB                       A5ZNM6KG.BG0002DI * 
 * Target Table:    shadow_OUTPUT0 - work.basel_irb       A5ZNM6KG.BV0004Q8 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.BASEL_IRB); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.BASEL_IRB;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.BASEL_IRB%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Monthly IRB data, approved);

%let _INPUT0 = dw_dw.BASEL_IRB;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.BASEL_IRB%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Monthly IRB data, approved);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.basel_irb;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004Q8%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type portfolio_cd 
        s_group_cd pd_under_model_number source_system_cd extracted_dt 
        loaded_dt;

%let _OUTPUT0 = work.basel_irb;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004Q8%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type portfolio_cd 
        s_group_cd pd_under_model_number source_system_cd extracted_dt 
        loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete basel_irb;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type portfolio_cd 
        s_group_cd pd_under_model_number source_system_cd extracted_dt 
        loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id ead_amount ead_amount_obs 
        credit_amount conversion_factor_type conversion_factor_pct 
        credit_amount_obs conversion_factor_type_obs conversion_factor_pct_obs 
        sm_amount sm_amount_obs irb_amount irb_amount_obs credit_risk_type 
        risk_weighted_asset_amount risk_weight_pct expected_loss_amount 
        sm_exposure_class irb_customer_group sm_originating_exposure_class 
        irb_exposure_class pd_class_pct pd_class_number lgd_class_pct 
        lgd_class_number nbr_of_counterparties company_housing_30_amount 
        crm_amount housing_collateral_amount other_collateral_amount maturity 
        calculated_ead supporting_factor_class_number currency 
        bank_group_currency exchange_rate country_code 
        impairment_losses_amount counterparty_risk_type portfolio_cd 
        s_group_cd pd_under_model_number source_system_cd extracted_dt 
        loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            shadow                                A5ZNM6KG.BS0005NQ * 
 * Transform:       shadow                                                  * 
 * Description:     Makes audited manual corrections possible in a          * 
 *                   standard way.                                          * 
 *                                                                          * 
 * Source Table:    dw_dw.BASEL_SA                        A5ZNM6KG.BG0002DH * 
 * Target Table:    shadow_OUTPUT0 - work.basel_sa        A5ZNM6KG.BV0004QC * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NQ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(dw_dw.BASEL_SA); 

%let _INPUT_count = 1; 
%let _INPUT = dw_dw.BASEL_SA;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(ALTER=&alterpass);
%let _INPUT_alter = %nrquote(ALTER=&alterpass);
%let _INPUT_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.BASEL_SA%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote(Monthly IRB data, additional S-method, approved);

%let _INPUT0 = dw_dw.BASEL_SA;
%let _INPUT0_connect = null;
%let _INPUT0_engine = BASE;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote(ALTER=&alterpass);
%let _INPUT0_alter = %nrquote(ALTER=&alterpass);
%let _INPUT0_path = %nrquote(/dw_solution/dw/data/dw/dw_dw.BASEL_SA%(Table%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote(Monthly IRB data, additional S-method, approved);

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.basel_sa;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004QC%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id row_number exposure_class 
        irb_customer_group sm_originating_exposure_class exposure_amount 
        sm_risk_weight_pct conversion_factor_pct conversion_factor_type 
        balance_sheet exchange_rate source_system_cd extracted_dt loaded_dt;

%let _OUTPUT0 = work.basel_sa;
%let _OUTPUT0_connect = ;
%let _OUTPUT0_engine = ;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote();
%let _OUTPUT0_alter = %nrquote();
%let _OUTPUT0_path = %nrquote(/shadow_OUTPUT0_A5ZNM6KG.BV0004QC%(WorkTable%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id row_number exposure_class 
        irb_customer_group sm_originating_exposure_class exposure_amount 
        sm_risk_weight_pct conversion_factor_pct conversion_factor_type 
        balance_sheet exchange_rate source_system_cd extracted_dt loaded_dt;


proc datasets lib=work nolist nowarn memtype = (data view);
   delete basel_sa;
quit;


/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id row_number exposure_class 
        irb_customer_group sm_originating_exposure_class exposure_amount 
        sm_risk_weight_pct conversion_factor_pct conversion_factor_type 
        balance_sheet exchange_rate source_system_cd extracted_dt loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id row_number exposure_class 
        irb_customer_group sm_originating_exposure_class exposure_amount 
        sm_risk_weight_pct conversion_factor_pct conversion_factor_type 
        balance_sheet exchange_rate source_system_cd extracted_dt loaded_dt;
%shadow(source=&_INPUT0., target=&_OUTPUT0., metapath=&_INPUT0_path.);;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end shadow **/

/*==========================================================================* 
 * Step:            Join                                  A5ZNM6KG.BS0005NS * 
 * Transform:       Join                                                    * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   shadow_OUTPUT0 - work.account_daily   A5ZNM6KG.BV0004QB * 
 *                  shadow_OUTPUT0 - work.account         A5ZNM6KG.BV0004QA * 
 *                  shadow_OUTPUT0 - work.basel_irb       A5ZNM6KG.BV0004Q8 * 
 *                  shadow_OUTPUT0 - work.basel_sa        A5ZNM6KG.BV0004QC * 
 *                  shadow_OUTPUT0 - work.exchange_rates  A5ZNM6KG.BV0004Q9 * 
 * Target Table:    Join - work.W5HWXB02                  A5ZNM6KG.BV0004QE * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NS);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete W5HWXB02;
quit;

proc sql;
   create view work.W5HWXB02 as
   select
      account_daily.information_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Information date of the record',
      account_daily.bank_id length = 1   
         label = 'Bank ID code: A = ÅB Finland, B = ÅB Sweden',
      account_daily.account_id length = 20   
         label = 'Account Number',
      account.account_number_official length = 20   
         label = 'Account Number, official, In Finland this field is same as ACCNBR, in Sweden it contains the official Swedish account number.',
      account.account_type_cd length = 3   
         label = 'CBS Account Type',
      account_daily.booked_balance_amt length = 8   
         format = 15.2
         label = 'Booked Balance,Amount 15,2 (2 decimals)',
      account.currency_cd length = 3   
         label = 'Account Currency',
      exchange_rates_a.mid_rate as exchange_rate_eur length = 8   
         format = 10.6
         label = 'Mid rate against EUR',
      exchange_rates_b.mid_rate as exchange_rate_sek length = 8   
         format = 10.6
         label = 'Mid rate against SEK',
      account_daily.overdraft_date length = 4   
         format = FINDFDD10.
         informat = DDMMYY10.
         label = 'Overdraft day 1.',
      sum(account_daily.information_date, -account_daily.overdraft_date) as overdraft_days_cnt length = 4   
         format = 8.
         label = 'Overdraft days count',
      case when basel_irb.account_id = ' ' then 0 else 1 end as account_in_basel_irb length = 3   
         format = 3.
         label = 'Account in Basel IRB: 0 = no, 1 = yes',
      case when basel_sa.account_id = ' ' then 0 else 1 end as account_in_basel_sa length = 3   
         format = 3.
         label = 'Account in Basel SA: 0 = no, 1 = yes'
   from
      work.account_daily as account_daily left join 
      work.account as account
         on
         (
            account_daily.information_date = account.information_date
            and account_daily.bank_id = account.bank_id
            and account_daily.account_id = account.account_id
         ) left join 
      work.basel_irb as basel_irb
         on
         (
            account_daily.information_date = basel_irb.information_date
            and account_daily.bank_id = basel_irb.bank_id
            and account_daily.account_id = basel_irb.account_id
         ) left join 
      work.basel_sa as basel_sa
         on
         (
            account_daily.information_date = basel_sa.information_date
            and account_daily.bank_id = basel_sa.bank_id
            and account_daily.account_id = basel_sa.account_id
         ) left join 
      work.exchange_rates as exchange_rates_a
         on
         (
            account.information_date = exchange_rates_a.information_date
            and account.currency_cd = exchange_rates_a.currency_cd
         ) left join 
      work.exchange_rates as exchange_rates_b
         on
         (
            account.information_date = exchange_rates_b.information_date
            and account.currency_cd = exchange_rates_b.currency_cd
         )
   where
      account_daily.booked_balance_amt < 0
      and account_daily.overdraft_date NOT IS MISSING 
      and account.account_type_cd NOT LIKE '2%'
      and calculated account_in_basel_irb = 0
      and exchange_rates_a.bank_id = 'A'
      and exchange_rates_b.bank_id = 'B'
   ;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Join **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0005NU * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Join - work.W5HWXB02                  A5ZNM6KG.BV0004QE * 
 * Target Table:    Extract - work.W5IDJJGK               A5ZNM6KG.BV0004QF * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NU);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W5HWXB02); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W5IDJJGK;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create view work.W5IDJJGK as
      select
         information_date,
         bank_id,
         account_id,
         account_number_official,
         account_type_cd,
         booked_balance_amt,
         currency_cd,
         exchange_rate_eur,
         exchange_rate_sek,
         overdraft_date,
         overdraft_days_cnt,
         account_in_basel_irb,
         account_in_basel_sa,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = datetime20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
   ;
quit;

%let SYSLAST = work.W5IDJJGK;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0005NT * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W5IDJJGK               A5ZNM6KG.BV0004QF * 
 * Target Table:    mel_dm.ACCOUNT_EXP_OVD                A5ZNM6KG.BG0006LG * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005NT);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W5IDJJGK); 

%let _INPUT_count = 1; 
%let _INPUT = work.W5IDJJGK;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = VIEW;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004QF%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W5IDJJGK;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = VIEW;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV0004QF%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mel_dm.ACCOUNT_EXP_OVD;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.ACCOUNT_EXP_OVD%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(Account information expanded for ECL class OVD);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date bank_id account_id account_number_official 
        account_type_cd booked_balance_amt currency_cd exchange_rate_eur 
        exchange_rate_sek overdraft_date overdraft_days_cnt 
        account_in_basel_irb account_in_basel_sa loaded_dt;

%let _OUTPUT0 = mel_dm.ACCOUNT_EXP_OVD;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mel/data/dm/mel_dm.ACCOUNT_EXP_OVD%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(Account information expanded for ECL class OVD);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date bank_id account_id account_number_official 
        account_type_cd booked_balance_amt currency_cd exchange_rate_eur 
        exchange_rate_sek overdraft_date overdraft_days_cnt 
        account_in_basel_irb account_in_basel_sa loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date bank_id account_id account_number_official 
        account_type_cd booked_balance_amt currency_cd exchange_rate_eur 
        exchange_rate_sek overdraft_date overdraft_days_cnt 
        account_in_basel_irb account_in_basel_sa loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date bank_id account_id account_number_official 
        account_type_cd booked_balance_amt currency_cd exchange_rate_eur 
        exchange_rate_sek overdraft_date overdraft_days_cnt 
        account_in_basel_irb account_in_basel_sa loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mel_dm nolist; 
   modify ACCOUNT_EXP_OVD(ALTER=&alterpass ); 
      index create primary_index = (information_date bank_id account_id)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

