/**************************************************************************** 
 * Job:             mel_ctrl.par_lgd_general_llg          A5ZNM6KG.BO0003JP * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: olandsbanken-metadata                                   * 
 * Port:            8563                                                    * 
 * Location:        /dw_solution/mel/programs/jobs                          * 
 *                                                                          * 
 * Server:          DEV_App                               A5ZNM6KG.AS000005 * 
 *                                                                          * 
 * Source Tables:   mel_ctrl.PAR_LGD_GENERAL_LLG_S        A5ZNM6KG.BG0006DZ * 
 *                  mel_ctrl.PAR_LGD_GENERAL_LLG_S        A5ZNM6KG.BG0006DZ * 
 * Target Tables:   mel_ctrl.PAR_LGD_GENERAL_LLG          A5ZNM6KG.BG0006DR * 
 *                  mel_ctrl.PAR_LGD_GENERAL_LLG_S        A5ZNM6KG.BG0006DZ * 
 *                                                                          * 
 * Generated on:    Tuesday, December 18, 2018 3:25:25 PM EET               * 
 * Generated by:    makkojon                                                * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5ZNM6KG.BO0003JP);
%let etls_jobName = %nrquote(mel_ctrl.par_lgd_general_llg);
%let etls_userID = %nrquote(makkojon);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

%preprocess_std;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0005DY * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mel_ctrl.PAR_LGD_GENERAL_LLG_S        A5ZNM6KG.BG0006DZ * 
 * Target Table:    Extract - work.W1IQIUL2               A5ZNM6KG.BV0004IN * 
 *                                                                          * 
 * User Written:    Extract                                                 * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005DY);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mel_ctrl.PAR_LGD_GENERAL_LLG_S); 

%let ETLS_SYSLAST = &SYSLAST;
/*---- Start of Pre-Process Code  ----*/ 

* Introduce macro variables ;
%let _main_obs= ;
%let _s_increment=+1;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

%let SYSLAST = &ETLS_SYSLAST;

%let _INPUT_count = 1;
%let _INPUT = mel_ctrl.PAR_LGD_GENERAL_LLG_S;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote(OBS = &_main_obs.);
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/mel/data/ctrl/mel_ctrl.PAR_LGD_GENERAL_LLG_S%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();
%let _INPUT_filetype = PhysicalTable;

%let _INPUT1 = mel_ctrl.PAR_LGD_GENERAL_LLG_S;
%let _INPUT1_connect = null;
%let _INPUT1_engine = BASE;
%let _INPUT1_memtype = DATA;
%let _INPUT1_options = %nrquote(OBS = &_main_obs.);
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/dw_solution/mel/data/ctrl/mel_ctrl.PAR_LGD_GENERAL_LLG_S%(Table%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote();
%let _INPUT1_filetype = PhysicalTable;

%let _OUTPUT_count = 1;
%let _OUTPUT = work.W1IQIUL2;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004IN%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;
%let _OUTPUT_col_count = 10;
%let _OUTPUT_col0_name = information_date;
%let _OUTPUT_col0_table = work.W1IQIUL2;
%let _OUTPUT_col0_length = 4;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = FINDFDD10.;
%let _OUTPUT_col0_informat = DDMMYY10.;
%let _OUTPUT_col0_label = %nrquote(Information date);
%let _OUTPUT_col0_input0 = information_date;
%let _OUTPUT_col0_exp = ;
%let _OUTPUT_col0_input = information_date;
%let _OUTPUT_col0_input_count = 1;
%let _OUTPUT_col1_name = par_unique_id;
%let _OUTPUT_col1_table = work.W1IQIUL2;
%let _OUTPUT_col1_length = 4;
%let _OUTPUT_col1_type = ;
%let _OUTPUT_col1_format = 5.;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(Unique id %(running number%));
%let _OUTPUT_col1_input0 = par_unique_id;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = par_unique_id;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = type_of_run_cd;
%let _OUTPUT_col2_table = work.W1IQIUL2;
%let _OUTPUT_col2_length = 6;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Type of run code);
%let _OUTPUT_col2_input0 = type_of_run_cd;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = type_of_run_cd;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = discount_interest_rate;
%let _OUTPUT_col3_table = work.W1IQIUL2;
%let _OUTPUT_col3_length = 8;
%let _OUTPUT_col3_type = ;
%let _OUTPUT_col3_format = 15.6;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(The discount rate used in the model);
%let _OUTPUT_col3_input0 = discount_interest_rate;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = discount_interest_rate;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = other_recovery_guarantor_prop;
%let _OUTPUT_col4_table = work.W1IQIUL2;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 15.6;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(The proportion of other recovery cash flows estimated recieved from guarantors);
%let _OUTPUT_col4_input0 = other_recovery_guarantor_prop;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = other_recovery_guarantor_prop;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = reduction_other_recovery;
%let _OUTPUT_col5_table = work.W1IQIUL2;
%let _OUTPUT_col5_length = 8;
%let _OUTPUT_col5_type = ;
%let _OUTPUT_col5_format = 15.6;
%let _OUTPUT_col5_informat = ;
%let _OUTPUT_col5_label = %nrquote(General reduction on estimated other recoveries);
%let _OUTPUT_col5_input0 = reduction_other_recovery;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = reduction_other_recovery;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = reduction_collateral;
%let _OUTPUT_col6_table = work.W1IQIUL2;
%let _OUTPUT_col6_length = 8;
%let _OUTPUT_col6_type = ;
%let _OUTPUT_col6_format = 15.6;
%let _OUTPUT_col6_informat = ;
%let _OUTPUT_col6_label = %nrquote(General collateral reduction);
%let _OUTPUT_col6_input0 = reduction_collateral;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = reduction_collateral;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = capital_adequacy_prop;
%let _OUTPUT_col7_table = work.W1IQIUL2;
%let _OUTPUT_col7_length = 8;
%let _OUTPUT_col7_type = ;
%let _OUTPUT_col7_format = 15.6;
%let _OUTPUT_col7_informat = ;
%let _OUTPUT_col7_label = %nrquote(The capital adequacy limit, not relevant for IFRS 9);
%let _OUTPUT_col7_input0 = capital_adequacy_prop;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = capital_adequacy_prop;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = q_stop;
%let _OUTPUT_col8_table = work.W1IQIUL2;
%let _OUTPUT_col8_length = 8;
%let _OUTPUT_col8_type = ;
%let _OUTPUT_col8_format = 15.9;
%let _OUTPUT_col8_informat = ;
%let _OUTPUT_col8_label = %nrquote(Technical parameter display the level of the probability that the the whole exposure is covered by future cashflows);
%let _OUTPUT_col8_input0 = q_stop;
%let _OUTPUT_col8_exp = ;
%let _OUTPUT_col8_input = q_stop;
%let _OUTPUT_col8_input_count = 1;
%let _OUTPUT_col9_name = loaded_dt;
%let _OUTPUT_col9_table = work.W1IQIUL2;
%let _OUTPUT_col9_length = 8;
%let _OUTPUT_col9_type = ;
%let _OUTPUT_col9_format = DATETIME20.;
%let _OUTPUT_col9_informat = ;
%let _OUTPUT_col9_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT_col9_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT_col9_input_count = 0;
%let _OUTPUT_filetype = WorkTable;

%let _OUTPUT1 = work.W1IQIUL2;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/Extract_A5ZNM6KG.BV0004IN%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;
%let _OUTPUT1_col_count = 10;
%let _OUTPUT1_col0_name = information_date;
%let _OUTPUT1_col0_table = work.W1IQIUL2;
%let _OUTPUT1_col0_length = 4;
%let _OUTPUT1_col0_type = ;
%let _OUTPUT1_col0_format = FINDFDD10.;
%let _OUTPUT1_col0_informat = DDMMYY10.;
%let _OUTPUT1_col0_label = %nrquote(Information date);
%let _OUTPUT1_col0_input0 = information_date;
%let _OUTPUT1_col0_exp = ;
%let _OUTPUT1_col0_input = information_date;
%let _OUTPUT1_col0_input_count = 1;
%let _OUTPUT1_col1_name = par_unique_id;
%let _OUTPUT1_col1_table = work.W1IQIUL2;
%let _OUTPUT1_col1_length = 4;
%let _OUTPUT1_col1_type = ;
%let _OUTPUT1_col1_format = 5.;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote(Unique id %(running number%));
%let _OUTPUT1_col1_input0 = par_unique_id;
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input = par_unique_id;
%let _OUTPUT1_col1_input_count = 1;
%let _OUTPUT1_col2_name = type_of_run_cd;
%let _OUTPUT1_col2_table = work.W1IQIUL2;
%let _OUTPUT1_col2_length = 6;
%let _OUTPUT1_col2_type = $;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote(Type of run code);
%let _OUTPUT1_col2_input0 = type_of_run_cd;
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input = type_of_run_cd;
%let _OUTPUT1_col2_input_count = 1;
%let _OUTPUT1_col3_name = discount_interest_rate;
%let _OUTPUT1_col3_table = work.W1IQIUL2;
%let _OUTPUT1_col3_length = 8;
%let _OUTPUT1_col3_type = ;
%let _OUTPUT1_col3_format = 15.6;
%let _OUTPUT1_col3_informat = ;
%let _OUTPUT1_col3_label = %nrquote(The discount rate used in the model);
%let _OUTPUT1_col3_input0 = discount_interest_rate;
%let _OUTPUT1_col3_exp = ;
%let _OUTPUT1_col3_input = discount_interest_rate;
%let _OUTPUT1_col3_input_count = 1;
%let _OUTPUT1_col4_name = other_recovery_guarantor_prop;
%let _OUTPUT1_col4_table = work.W1IQIUL2;
%let _OUTPUT1_col4_length = 8;
%let _OUTPUT1_col4_type = ;
%let _OUTPUT1_col4_format = 15.6;
%let _OUTPUT1_col4_informat = ;
%let _OUTPUT1_col4_label = %nrquote(The proportion of other recovery cash flows estimated recieved from guarantors);
%let _OUTPUT1_col4_input0 = other_recovery_guarantor_prop;
%let _OUTPUT1_col4_exp = ;
%let _OUTPUT1_col4_input = other_recovery_guarantor_prop;
%let _OUTPUT1_col4_input_count = 1;
%let _OUTPUT1_col5_name = reduction_other_recovery;
%let _OUTPUT1_col5_table = work.W1IQIUL2;
%let _OUTPUT1_col5_length = 8;
%let _OUTPUT1_col5_type = ;
%let _OUTPUT1_col5_format = 15.6;
%let _OUTPUT1_col5_informat = ;
%let _OUTPUT1_col5_label = %nrquote(General reduction on estimated other recoveries);
%let _OUTPUT1_col5_input0 = reduction_other_recovery;
%let _OUTPUT1_col5_exp = ;
%let _OUTPUT1_col5_input = reduction_other_recovery;
%let _OUTPUT1_col5_input_count = 1;
%let _OUTPUT1_col6_name = reduction_collateral;
%let _OUTPUT1_col6_table = work.W1IQIUL2;
%let _OUTPUT1_col6_length = 8;
%let _OUTPUT1_col6_type = ;
%let _OUTPUT1_col6_format = 15.6;
%let _OUTPUT1_col6_informat = ;
%let _OUTPUT1_col6_label = %nrquote(General collateral reduction);
%let _OUTPUT1_col6_input0 = reduction_collateral;
%let _OUTPUT1_col6_exp = ;
%let _OUTPUT1_col6_input = reduction_collateral;
%let _OUTPUT1_col6_input_count = 1;
%let _OUTPUT1_col7_name = capital_adequacy_prop;
%let _OUTPUT1_col7_table = work.W1IQIUL2;
%let _OUTPUT1_col7_length = 8;
%let _OUTPUT1_col7_type = ;
%let _OUTPUT1_col7_format = 15.6;
%let _OUTPUT1_col7_informat = ;
%let _OUTPUT1_col7_label = %nrquote(The capital adequacy limit, not relevant for IFRS 9);
%let _OUTPUT1_col7_input0 = capital_adequacy_prop;
%let _OUTPUT1_col7_exp = ;
%let _OUTPUT1_col7_input = capital_adequacy_prop;
%let _OUTPUT1_col7_input_count = 1;
%let _OUTPUT1_col8_name = q_stop;
%let _OUTPUT1_col8_table = work.W1IQIUL2;
%let _OUTPUT1_col8_length = 8;
%let _OUTPUT1_col8_type = ;
%let _OUTPUT1_col8_format = 15.9;
%let _OUTPUT1_col8_informat = ;
%let _OUTPUT1_col8_label = %nrquote(Technical parameter display the level of the probability that the the whole exposure is covered by future cashflows);
%let _OUTPUT1_col8_input0 = q_stop;
%let _OUTPUT1_col8_exp = ;
%let _OUTPUT1_col8_input = q_stop;
%let _OUTPUT1_col8_input_count = 1;
%let _OUTPUT1_col9_name = loaded_dt;
%let _OUTPUT1_col9_table = work.W1IQIUL2;
%let _OUTPUT1_col9_length = 8;
%let _OUTPUT1_col9_type = ;
%let _OUTPUT1_col9_format = DATETIME20.;
%let _OUTPUT1_col9_informat = ;
%let _OUTPUT1_col9_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT1_col9_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT1_col9_input_count = 0;
%let _OUTPUT1_filetype = WorkTable;

/*---- Start of User Written Code  ----*/ 

* ********************* BEGIN MODIFIED PART ********************* ;
* In case the (_S) source is missing the first time the job is run, 
  use the corresponding STG sources to create the tables. 
* In case the main table has rows of the current month (2nd or later run), 
  use _H view as the source (where...)

* After changing the Code generation mode into "User written body", 
  this was included in the beginning of the modified part. 
  When need to change the extract
    0) Copy this MODIFIED PART into text editor.
    1) Change Code generation mode into "Automatic"
    3) Make the changes in the other tabs
    4) Change Code generation mode back into "User written body" 
       (Choose "No" when asked "Do you want to reload the saved user written code?".)
    5) Copy this MODIFIED PART from the text editor back here.
;  
%let _libr=%sysfunc(scan(&syslast.,1,'.')) ;
%let _tabl=%sysfunc(scan(&syslast.,2,'.')) ;
%let current_rows_in_target=0;
filename _sqlobs temp;

data _null_ ;
exists=exist("&syslast","DATA");
ext_len_target=2 ; *Snip as many chars as needed to get the target table name. ;
* Check the target libname in the following line., if not the same as source library ;
target_libr="&_libr." ;
target_tabl=substr(target_libr!!".&_tabl",1,length(target_libr!!".&_tabl")-ext_len_target) ; 
call symput('target_tabl',target_tabl) ;
call symput('_s_obs','0') ;
call symput('_main_obs','MAX') ;
file _sqlobs ;
put '* Get number of rows in main table ;';
file log ;
if not exists then do ;
  ext_len_source=2 ; *Snip as many chars as needed to get the new source table name. ;
  tablename=substr("dw_stg.&_tabl",1,length("dw_stg.&_tabl")-ext_len_source) ; 
  exists=exist(tablename,"DATA");
  if exists then do;
    call symput('syslast',tablename) ;
    call symput('_s_obs','MAX') ;
    call symput('_main_obs','0') ;
  end;
  else do ;
    put "ERROR: Table &syslast does not exist and the alternative source " tablename " does not exist either. ";
    abort abend;
  end ;
end ;
else do;
  file _sqlobs ;
  put 'proc sql noprint ; select count(*) from &target_tabl. where information_date=&active_date ; quit ;';
  put '%let current_rows_in_target=&sqlobs;';
  file log ;
end ;
run ;
%include _sqlobs ;

%put NOTE: syslast=&syslast, target_tabl=&target_tabl. current_rows_in_target=&current_rows_in_target. ; 

data _null_ ;
if &current_rows_in_target>0 then do ;
  tablename=substr("&syslast",1,length("&syslast")-2)!!'_H'; 
  exists=exist(tablename,"VIEW");
  if exists then do;
    call symput('syslast',tablename) ;
  end;
  else do ;
    put "ERROR: View &syslast does not exist. ";
    abort abend;
  end ;
end ;
run ;
%put NOTE: syslast=&syslast, target_tabl=&target_tabl., _s_obs=&_s_obs.. ; 

* ********************* END MODIFIED PART ********************* ;


%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W1IQIUL2;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W1IQIUL2 as
      select
         information_date,
         par_unique_id,
         type_of_run_cd,
         discount_interest_rate,
         other_recovery_guarantor_prop,
         reduction_other_recovery,
         reduction_collateral,
         capital_adequacy_prop,
         q_stop,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
      (OBS = &_main_obs.)
      where information_date = &active_date.
   ;
quit;

%let SYSLAST = work.W1IQIUL2;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 


/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 


/**  Step end Extract **/

/*==========================================================================* 
 * Step:            history                               A5ZNM6KG.BS0003AB * 
 * Transform:       history                                                 * 
 * Description:     Executes history management on connected table          * 
 *                                                                          * 
 * Source Table:    Extract - work.W1IQIUL2               A5ZNM6KG.BV0004IN * 
 * Target Table:    mel_ctrl.PAR_LGD_GENERAL_LLG          A5ZNM6KG.BG0006DR * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0003AB);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W1IQIUL2); 

%let _INPUT_count = 1; 
%let _INPUT = work.W1IQIUL2;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004IN%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.W1IQIUL2;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Extract_A5ZNM6KG.BV0004IN%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = mel_ctrl.PAR_LGD_GENERAL_LLG;
%let _OUTPUT_connect = null;
%let _OUTPUT_engine = BASE;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT_path = %nrquote(/dw_solution/mel/data/ctrl/mel_ctrl.PAR_LGD_GENERAL_LLG%(Table%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote(General calculation parameters used in the LGD model for loans, limits and guarantees);
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;

%let _OUTPUT0 = mel_ctrl.PAR_LGD_GENERAL_LLG;
%let _OUTPUT0_connect = null;
%let _OUTPUT0_engine = BASE;
%let _OUTPUT0_memtype = DATA;
%let _OUTPUT0_options = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_alter = %nrquote(ALTER=&alterpass);
%let _OUTPUT0_path = %nrquote(/dw_solution/mel/data/ctrl/mel_ctrl.PAR_LGD_GENERAL_LLG%(Table%));
%let _OUTPUT0_type = 1;
%let _OUTPUT0_label = %nrquote(General calculation parameters used in the LGD model for loans, limits and guarantees);
/* List of target columns to keep  */ 
%let _OUTPUT0_keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;


%let dimfields = ;
%let dimfields_count = 0;
%let dimfields0 = 0;
%let dimfields = ;

/* List of target columns to keep  */ 
%let _keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;
/* List of target columns to keep  */ 
%let keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;
%history(source=&_INPUT0.,target=&_OUTPUT0.,metapath=&_OUTPUT0_path.);

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 

/*---- Create the indexes for a table  ----*/ 
%put %str(NOTE: Creating indexes ...);
proc datasets lib = mel_ctrl nolist; 
   modify PAR_LGD_GENERAL_LLG(ALTER=&alterpass ); 
      index create primary_index = (information_date par_unique_id type_of_run_cd)
         / unique;
quit; 

%rcSet(&syserr); 



/**  Step end history **/

/*==========================================================================* 
 * Step:            Extract                               A5ZNM6KG.BS0005DZ * 
 * Transform:       Extract                                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    mel_ctrl.PAR_LGD_GENERAL_LLG_S        A5ZNM6KG.BG0006DZ * 
 * Target Table:    Extract - work.W1ITYL8Y               A5ZNM6KG.BV0004IO * 
 *                                                                          * 
 * User Written:    UserWrittenSourceCode                                   * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005DZ);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(mel_ctrl.PAR_LGD_GENERAL_LLG_S); 

%let _INPUT_count = 1;
%let _INPUT = mel_ctrl.PAR_LGD_GENERAL_LLG_S;
%let _INPUT_connect = null;
%let _INPUT_engine = BASE;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/dw_solution/mel/data/ctrl/mel_ctrl.PAR_LGD_GENERAL_LLG_S%(Table%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();
%let _INPUT_filetype = PhysicalTable;

%let _INPUT1 = mel_ctrl.PAR_LGD_GENERAL_LLG_S;
%let _INPUT1_connect = null;
%let _INPUT1_engine = BASE;
%let _INPUT1_memtype = DATA;
%let _INPUT1_options = %nrquote();
%let _INPUT1_alter = %nrquote();
%let _INPUT1_path = %nrquote(/dw_solution/mel/data/ctrl/mel_ctrl.PAR_LGD_GENERAL_LLG_S%(Table%));
%let _INPUT1_type = 1;
%let _INPUT1_label = %nrquote();
%let _INPUT1_filetype = PhysicalTable;

%let _OUTPUT_count = 1;
%let _OUTPUT = work.W1ITYL8Y;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/Extract_A5ZNM6KG.BV0004IO%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;
%let _OUTPUT_col_count = 10;
%let _OUTPUT_col0_name = information_date;
%let _OUTPUT_col0_table = work.W1ITYL8Y;
%let _OUTPUT_col0_length = 4;
%let _OUTPUT_col0_type = ;
%let _OUTPUT_col0_format = FINDFDD10.;
%let _OUTPUT_col0_informat = DDMMYY10.;
%let _OUTPUT_col0_label = %nrquote(Information date);
%let _OUTPUT_col0_exp = intnx('month', &active_date,&_s_increment,'end');
%let _OUTPUT_col0_input_count = 0;
%let _OUTPUT_col1_name = par_unique_id;
%let _OUTPUT_col1_table = work.W1ITYL8Y;
%let _OUTPUT_col1_length = 4;
%let _OUTPUT_col1_type = ;
%let _OUTPUT_col1_format = 5.;
%let _OUTPUT_col1_informat = ;
%let _OUTPUT_col1_label = %nrquote(Unique id %(running number%));
%let _OUTPUT_col1_input0 = par_unique_id;
%let _OUTPUT_col1_exp = ;
%let _OUTPUT_col1_input = par_unique_id;
%let _OUTPUT_col1_input_count = 1;
%let _OUTPUT_col2_name = type_of_run_cd;
%let _OUTPUT_col2_table = work.W1ITYL8Y;
%let _OUTPUT_col2_length = 6;
%let _OUTPUT_col2_type = $;
%let _OUTPUT_col2_format = ;
%let _OUTPUT_col2_informat = ;
%let _OUTPUT_col2_label = %nrquote(Type of run code);
%let _OUTPUT_col2_input0 = type_of_run_cd;
%let _OUTPUT_col2_exp = ;
%let _OUTPUT_col2_input = type_of_run_cd;
%let _OUTPUT_col2_input_count = 1;
%let _OUTPUT_col3_name = discount_interest_rate;
%let _OUTPUT_col3_table = work.W1ITYL8Y;
%let _OUTPUT_col3_length = 8;
%let _OUTPUT_col3_type = ;
%let _OUTPUT_col3_format = 15.6;
%let _OUTPUT_col3_informat = ;
%let _OUTPUT_col3_label = %nrquote(The discount rate used in the model);
%let _OUTPUT_col3_input0 = discount_interest_rate;
%let _OUTPUT_col3_exp = ;
%let _OUTPUT_col3_input = discount_interest_rate;
%let _OUTPUT_col3_input_count = 1;
%let _OUTPUT_col4_name = other_recovery_guarantor_prop;
%let _OUTPUT_col4_table = work.W1ITYL8Y;
%let _OUTPUT_col4_length = 8;
%let _OUTPUT_col4_type = ;
%let _OUTPUT_col4_format = 15.6;
%let _OUTPUT_col4_informat = ;
%let _OUTPUT_col4_label = %nrquote(The proportion of other recovery cash flows estimated recieved from guarantors);
%let _OUTPUT_col4_input0 = other_recovery_guarantor_prop;
%let _OUTPUT_col4_exp = ;
%let _OUTPUT_col4_input = other_recovery_guarantor_prop;
%let _OUTPUT_col4_input_count = 1;
%let _OUTPUT_col5_name = reduction_other_recovery;
%let _OUTPUT_col5_table = work.W1ITYL8Y;
%let _OUTPUT_col5_length = 8;
%let _OUTPUT_col5_type = ;
%let _OUTPUT_col5_format = 15.6;
%let _OUTPUT_col5_informat = ;
%let _OUTPUT_col5_label = %nrquote(General reduction on estimated other recoveries);
%let _OUTPUT_col5_input0 = reduction_other_recovery;
%let _OUTPUT_col5_exp = ;
%let _OUTPUT_col5_input = reduction_other_recovery;
%let _OUTPUT_col5_input_count = 1;
%let _OUTPUT_col6_name = reduction_collateral;
%let _OUTPUT_col6_table = work.W1ITYL8Y;
%let _OUTPUT_col6_length = 8;
%let _OUTPUT_col6_type = ;
%let _OUTPUT_col6_format = 15.6;
%let _OUTPUT_col6_informat = ;
%let _OUTPUT_col6_label = %nrquote(General collateral reduction);
%let _OUTPUT_col6_input0 = reduction_collateral;
%let _OUTPUT_col6_exp = ;
%let _OUTPUT_col6_input = reduction_collateral;
%let _OUTPUT_col6_input_count = 1;
%let _OUTPUT_col7_name = capital_adequacy_prop;
%let _OUTPUT_col7_table = work.W1ITYL8Y;
%let _OUTPUT_col7_length = 8;
%let _OUTPUT_col7_type = ;
%let _OUTPUT_col7_format = 15.6;
%let _OUTPUT_col7_informat = ;
%let _OUTPUT_col7_label = %nrquote(The capital adequacy limit, not relevant for IFRS 9);
%let _OUTPUT_col7_input0 = capital_adequacy_prop;
%let _OUTPUT_col7_exp = ;
%let _OUTPUT_col7_input = capital_adequacy_prop;
%let _OUTPUT_col7_input_count = 1;
%let _OUTPUT_col8_name = q_stop;
%let _OUTPUT_col8_table = work.W1ITYL8Y;
%let _OUTPUT_col8_length = 8;
%let _OUTPUT_col8_type = ;
%let _OUTPUT_col8_format = 15.9;
%let _OUTPUT_col8_informat = ;
%let _OUTPUT_col8_label = %nrquote(Technical parameter display the level of the probability that the the whole exposure is covered by future cashflows);
%let _OUTPUT_col8_input0 = q_stop;
%let _OUTPUT_col8_exp = ;
%let _OUTPUT_col8_input = q_stop;
%let _OUTPUT_col8_input_count = 1;
%let _OUTPUT_col9_name = loaded_dt;
%let _OUTPUT_col9_table = work.W1ITYL8Y;
%let _OUTPUT_col9_length = 8;
%let _OUTPUT_col9_type = ;
%let _OUTPUT_col9_format = DATETIME20.;
%let _OUTPUT_col9_informat = ;
%let _OUTPUT_col9_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT_col9_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT_col9_input_count = 0;
%let _OUTPUT_filetype = WorkTable;

%let _OUTPUT1 = work.W1ITYL8Y;
%let _OUTPUT1_connect = ;
%let _OUTPUT1_engine = ;
%let _OUTPUT1_memtype = DATA;
%let _OUTPUT1_options = %nrquote();
%let _OUTPUT1_alter = %nrquote();
%let _OUTPUT1_path = %nrquote(/Extract_A5ZNM6KG.BV0004IO%(WorkTable%));
%let _OUTPUT1_type = 1;
%let _OUTPUT1_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT1_keep = information_date par_unique_id type_of_run_cd discount_interest_rate 
        other_recovery_guarantor_prop reduction_other_recovery 
        reduction_collateral capital_adequacy_prop q_stop loaded_dt;
%let _OUTPUT1_col_count = 10;
%let _OUTPUT1_col0_name = information_date;
%let _OUTPUT1_col0_table = work.W1ITYL8Y;
%let _OUTPUT1_col0_length = 4;
%let _OUTPUT1_col0_type = ;
%let _OUTPUT1_col0_format = FINDFDD10.;
%let _OUTPUT1_col0_informat = DDMMYY10.;
%let _OUTPUT1_col0_label = %nrquote(Information date);
%let _OUTPUT1_col0_exp = intnx('month', &active_date,&_s_increment,'end');
%let _OUTPUT1_col0_input_count = 0;
%let _OUTPUT1_col1_name = par_unique_id;
%let _OUTPUT1_col1_table = work.W1ITYL8Y;
%let _OUTPUT1_col1_length = 4;
%let _OUTPUT1_col1_type = ;
%let _OUTPUT1_col1_format = 5.;
%let _OUTPUT1_col1_informat = ;
%let _OUTPUT1_col1_label = %nrquote(Unique id %(running number%));
%let _OUTPUT1_col1_input0 = par_unique_id;
%let _OUTPUT1_col1_exp = ;
%let _OUTPUT1_col1_input = par_unique_id;
%let _OUTPUT1_col1_input_count = 1;
%let _OUTPUT1_col2_name = type_of_run_cd;
%let _OUTPUT1_col2_table = work.W1ITYL8Y;
%let _OUTPUT1_col2_length = 6;
%let _OUTPUT1_col2_type = $;
%let _OUTPUT1_col2_format = ;
%let _OUTPUT1_col2_informat = ;
%let _OUTPUT1_col2_label = %nrquote(Type of run code);
%let _OUTPUT1_col2_input0 = type_of_run_cd;
%let _OUTPUT1_col2_exp = ;
%let _OUTPUT1_col2_input = type_of_run_cd;
%let _OUTPUT1_col2_input_count = 1;
%let _OUTPUT1_col3_name = discount_interest_rate;
%let _OUTPUT1_col3_table = work.W1ITYL8Y;
%let _OUTPUT1_col3_length = 8;
%let _OUTPUT1_col3_type = ;
%let _OUTPUT1_col3_format = 15.6;
%let _OUTPUT1_col3_informat = ;
%let _OUTPUT1_col3_label = %nrquote(The discount rate used in the model);
%let _OUTPUT1_col3_input0 = discount_interest_rate;
%let _OUTPUT1_col3_exp = ;
%let _OUTPUT1_col3_input = discount_interest_rate;
%let _OUTPUT1_col3_input_count = 1;
%let _OUTPUT1_col4_name = other_recovery_guarantor_prop;
%let _OUTPUT1_col4_table = work.W1ITYL8Y;
%let _OUTPUT1_col4_length = 8;
%let _OUTPUT1_col4_type = ;
%let _OUTPUT1_col4_format = 15.6;
%let _OUTPUT1_col4_informat = ;
%let _OUTPUT1_col4_label = %nrquote(The proportion of other recovery cash flows estimated recieved from guarantors);
%let _OUTPUT1_col4_input0 = other_recovery_guarantor_prop;
%let _OUTPUT1_col4_exp = ;
%let _OUTPUT1_col4_input = other_recovery_guarantor_prop;
%let _OUTPUT1_col4_input_count = 1;
%let _OUTPUT1_col5_name = reduction_other_recovery;
%let _OUTPUT1_col5_table = work.W1ITYL8Y;
%let _OUTPUT1_col5_length = 8;
%let _OUTPUT1_col5_type = ;
%let _OUTPUT1_col5_format = 15.6;
%let _OUTPUT1_col5_informat = ;
%let _OUTPUT1_col5_label = %nrquote(General reduction on estimated other recoveries);
%let _OUTPUT1_col5_input0 = reduction_other_recovery;
%let _OUTPUT1_col5_exp = ;
%let _OUTPUT1_col5_input = reduction_other_recovery;
%let _OUTPUT1_col5_input_count = 1;
%let _OUTPUT1_col6_name = reduction_collateral;
%let _OUTPUT1_col6_table = work.W1ITYL8Y;
%let _OUTPUT1_col6_length = 8;
%let _OUTPUT1_col6_type = ;
%let _OUTPUT1_col6_format = 15.6;
%let _OUTPUT1_col6_informat = ;
%let _OUTPUT1_col6_label = %nrquote(General collateral reduction);
%let _OUTPUT1_col6_input0 = reduction_collateral;
%let _OUTPUT1_col6_exp = ;
%let _OUTPUT1_col6_input = reduction_collateral;
%let _OUTPUT1_col6_input_count = 1;
%let _OUTPUT1_col7_name = capital_adequacy_prop;
%let _OUTPUT1_col7_table = work.W1ITYL8Y;
%let _OUTPUT1_col7_length = 8;
%let _OUTPUT1_col7_type = ;
%let _OUTPUT1_col7_format = 15.6;
%let _OUTPUT1_col7_informat = ;
%let _OUTPUT1_col7_label = %nrquote(The capital adequacy limit, not relevant for IFRS 9);
%let _OUTPUT1_col7_input0 = capital_adequacy_prop;
%let _OUTPUT1_col7_exp = ;
%let _OUTPUT1_col7_input = capital_adequacy_prop;
%let _OUTPUT1_col7_input_count = 1;
%let _OUTPUT1_col8_name = q_stop;
%let _OUTPUT1_col8_table = work.W1ITYL8Y;
%let _OUTPUT1_col8_length = 8;
%let _OUTPUT1_col8_type = ;
%let _OUTPUT1_col8_format = 15.9;
%let _OUTPUT1_col8_informat = ;
%let _OUTPUT1_col8_label = %nrquote(Technical parameter display the level of the probability that the the whole exposure is covered by future cashflows);
%let _OUTPUT1_col8_input0 = q_stop;
%let _OUTPUT1_col8_exp = ;
%let _OUTPUT1_col8_input = q_stop;
%let _OUTPUT1_col8_input_count = 1;
%let _OUTPUT1_col9_name = loaded_dt;
%let _OUTPUT1_col9_table = work.W1ITYL8Y;
%let _OUTPUT1_col9_length = 8;
%let _OUTPUT1_col9_type = ;
%let _OUTPUT1_col9_format = DATETIME20.;
%let _OUTPUT1_col9_informat = ;
%let _OUTPUT1_col9_label = %nrquote(Load timestamp %(date & time%));
%let _OUTPUT1_col9_exp = %sysfunc(round(%sysfunc(datetime()),1));
%let _OUTPUT1_col9_input_count = 0;
%let _OUTPUT1_filetype = WorkTable;

/*---- Start of User Written Code  ----*/ 

* ********************* BEGIN MODIFIED PART ********************* ;
* In case the (_S) source is missing the first time the job is run, 
  use the corresponding STG sources to create the tables. 

* After changing the Code generation mode into "User written body", 
  this was included in the beginning of the modified part. 
  When need to change the extract
    0) Copy this MODIFIED PART into text editor.
    1) Change Code generation mode into "Automatic"
    3) Make the changes in the other tabs
    4) Change Code generation mode back into "User written body" 
       (Choose "No" when asked "Do you want to reload the saved user written code?".)
    5) Copy this MODIFIED PART from the text editor back here.
;  
%let _libr=%sysfunc(scan(&syslast.,1,'.')) ;
%let _tabl=%sysfunc(scan(&syslast.,2,'.')) ;

data _null_ ;
if symget('_s_obs')='MAX' then do ;
  ext_len_source=2 ; *Snip as many chars as needed to get the new source table name. ;
  tablename=substr("dw_stg.&_tabl",1,length("dw_stg.&_tabl")-ext_len_source) ; 
  exists=exist(tablename,"DATA");
  if exists then do;
    call symput('syslast',tablename) ;
    call symput('_s_increment','0') ;
  end;
  else do ;
    put "ERROR: Table &syslast does not exist and the alternative source " tablename " does not exist either. ";
    abort abend;
  end ;
end ;
run ;
%include _sqlobs ;

* ********************* END MODIFIED PART ********************* ;


%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

/*---- Map the columns  ----*/ 
proc datasets lib = work nolist nowarn memtype = (data view);
   delete W1ITYL8Y;
quit;

%put %str(NOTE: Mapping columns ...);
proc sql;
   create table work.W1ITYL8Y as
      select
         (intnx('month', &active_date,&_s_increment,'end')) as information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date',
         par_unique_id,
         type_of_run_cd,
         discount_interest_rate,
         other_recovery_guarantor_prop,
         reduction_other_recovery,
         reduction_collateral,
         capital_adequacy_prop,
         q_stop,
         (%sysfunc(round(%sysfunc(datetime()),1))) as loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'
   from &SYSLAST
      where information_date = &active_date.
   ;
quit;

%let SYSLAST = work.W1ITYL8Y;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 


/*---- End of User Written Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 


/**  Step end Extract **/

/*==========================================================================* 
 * Step:            Table Loader                          A5ZNM6KG.BS0005E0 * 
 * Transform:       Table Loader (Version 2.1)                              * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Extract - work.W1ITYL8Y               A5ZNM6KG.BV0004IO * 
 * Target Table:    mel_ctrl.PAR_LGD_GENERAL_LLG_S        A5ZNM6KG.BG0006DZ * 
 *==========================================================================*/ 

%let transformID = %quote(A5ZNM6KG.BS0005E0);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.W1ITYL8Y); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%global etls_tableExist;
%global etls_numIndex;
%global etls_lastTable;
%let etls_tableExist = -1; 
%let etls_numIndex = -1; 
%let etls_lastTable = &SYSLAST; 

/*---- Define load data macro  ----*/ 

/* --------------------------------------------------------------
   Load Technique Selection: Update - Matching=SQLSet, New=AppendProc
   Blanks may replace non-blanks: true
   Constraint and index action selections: 'ASIS','ASIS','INIT','ASIS'
   Additional options selections... 
      Set unmapped to missing on updates: false 
   -------------------------------------------------------------- */
%macro etls_loader;

   %let etls_tableOptions = ;
   
   /* Determine if the target table exists  */ 
   %let etls_tableExist = %eval(%sysfunc(exist(mel_ctrl.PAR_LGD_GENERAL_LLG_S, DATA)) or 
         %sysfunc(exist(mel_ctrl.PAR_LGD_GENERAL_LLG_S, VIEW))); 
   
   %let etls_hasUpdateIndex=0; 
   
   /*---- Create a new table  ----*/ 
   %if (&etls_tableExist eq 0) %then 
   %do;  /* if table does not exist  */ 
   
      %put %str(NOTE: Creating table ...);
      
      data mel_ctrl.PAR_LGD_GENERAL_LLG_S;
         attrib information_date length = 4
            format = FINDFDD10.
            informat = DDMMYY10.
            label = 'Information date'; 
         attrib par_unique_id length = 4
            format = 5.
            label = 'Unique id (running number)'; 
         attrib type_of_run_cd length = $6
            label = 'Type of run code'; 
         attrib discount_interest_rate length = 8
            format = 15.6
            label = 'The discount rate used in the model'; 
         attrib other_recovery_guarantor_prop length = 8
            format = 15.6
            label = 'The proportion of other recovery cash flows estimated recieved from guarantors'; 
         attrib reduction_other_recovery length = 8
            format = 15.6
            label = 'General reduction on estimated other recoveries'; 
         attrib reduction_collateral length = 8
            format = 15.6
            label = 'General collateral reduction'; 
         attrib capital_adequacy_prop length = 8
            format = 15.6
            label = 'The capital adequacy limit, not relevant for IFRS 9'; 
         attrib q_stop length = 8
            format = 15.9
            label = 'Technical parameter display the level of the probability that the the whole exposure is covered by future cashflows'; 
         attrib loaded_dt length = 8
            format = DATETIME20.
            label = 'Load timestamp (date & time)'; 
         call missing(of _all_);
         stop;
      run;
      
      %rcSet(&syserr); 
      
      /*---- Create the indexes for a table  ----*/ 
      %put %str(NOTE: Creating indexes ...);
      proc datasets lib = mel_ctrl nolist; 
         modify PAR_LGD_GENERAL_LLG_S; 
            index create primary_index = (information_date par_unique_id type_of_run_cd)
               / unique nomiss;
      quit; 
      
      %rcSet(&syserr); 
      
   %end;  /* if table does not exist  */ 
   
   %let etls_recCheckExist = 0; 
   %let etls_targetHasRows = 0; 
   %macro etls_recordCheck; 
      %let etls_recCheckExist = %eval(%sysfunc(exist(mel_ctrl.PAR_LGD_GENERAL_LLG_S, DATA)) or 
            %sysfunc(exist(mel_ctrl.PAR_LGD_GENERAL_LLG_S, VIEW))); 
      
      %if (&etls_recCheckExist) %then
      %do;
         %local etls_syntaxcheck; 
         %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
         /* Turn off syntaxcheck option to perform following steps  */ 
         options nosyntaxcheck;
         
         data _null_; 
            set mel_ctrl.PAR_LGD_GENERAL_LLG_S( obs=1 ); 
            call symput("etls_targetHasRows",'1'); 
         run; 
         /* Reset syntaxcheck option to previous setting  */ 
         options &etls_syntaxcheck; 
      %end;
   %mend etls_recordCheck;
   %etls_recordCheck;
   
   
   %if (&etls_targetHasRows) %then 
   %do;  /* if has rows */ 
      proc sql ; 
         /* update existing records in the master table  */ 
         update mel_ctrl.PAR_LGD_GENERAL_LLG_S as m
            set information_date = (select information_date from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd),
                   discount_interest_rate = (select discount_interest_rate from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd),
                   other_recovery_guarantor_prop = (select other_recovery_guarantor_prop from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd),
                   reduction_other_recovery = (select reduction_other_recovery from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd),
                   reduction_collateral = (select reduction_collateral from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd),
                   capital_adequacy_prop = (select capital_adequacy_prop from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd),
                   q_stop = (select q_stop from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd),
                   loaded_dt = (select loaded_dt from &etls_lastTable as t 
                                where m.par_unique_id = t.par_unique_id and 
                                      m.type_of_run_cd = t.type_of_run_cd)
               where exists (select * from &etls_lastTable as t
                                   where m.par_unique_id = t.par_unique_id and 
                                         m.type_of_run_cd = t.type_of_run_cd);
         
         /* create a temporary table of new records from the transaction table  */ 
         create table etls_newrecords as 
            select * 
               from &etls_lastTable as t 
                  where not exists 
                     (select * from mel_ctrl.PAR_LGD_GENERAL_LLG_S
                   as m 
                                      where m.par_unique_id = t.par_unique_id and 
                                            m.type_of_run_cd = t.type_of_run_cd)
         ; 
         
      quit;
      
      %let etls_lastTable = &SYSLAST;
      
      %let etls_tableOptions = ; 
      
      %global etls_sql_pushDown;
      %let etls_sql_pushDown = &sys_sql_ip_all;
      
      %rcSet(&sqlrc); 
      
   %end; /* if has rows */ 
   
   /*---- Append  ----*/ 
   %put %str(NOTE: Appending data ...);
   
   proc append base = mel_ctrl.PAR_LGD_GENERAL_LLG_S 
      data = &etls_lastTable (&etls_tableOptions)  force ; 
    run; 
   
   %rcSet(&syserr); 
   
   proc datasets lib = work nolist nowarn memtype = (data view);
      delete etls_newrecords;
   quit;
   
%mend etls_loader;
%etls_loader;



/**  Step end Table Loader **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/*---- Start of Post-Process Code  ----*/ 

%postprocess_std;
/*---- End of Post-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

